Repository CompaniTech/compani-api, pull requests merged in 2020-12, with the labels that each got.

#1158 Com 1655 - Tabs
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1157 Com 1658
  src/helpers/categories.js
  src/helpers/programs.js
  src/models/Category.js
  src/models/Program.js
  src/routes/categories.js
  src/routes/preHandlers/categories.js
  src/routes/preHandlers/programs.js
  src/routes/programs.js
  tests/integration/categories.test.js
  tests/integration/programs.test.js
  tests/integration/seed/categoriesSeed.js
  tests/integration/seed/programsSeed.js
  tests/unit/helpers/categories.test.js
  tests/unit/helpers/programs.test.js
Labels: dev

#1164 Com 1655 - POST
  src/controllers/courseController.js
  src/helpers/courses.js
  src/helpers/translate.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1166 Refacto surcharge
  src/controllers/surchargeController.js
  src/helpers/surcharges.js
  src/helpers/translate.js
  src/routes/preHandlers/surcharges.js
  src/routes/surcharges.js
  tests/integration/surcharges.test.js
  tests/unit/helpers/surcharges.test.js
Labels: dev

#1167 COM-1660 - add learning goals
  src/helpers/courses.js
  src/models/Program.js
  src/routes/programs.js
  tests/integration/courses.test.js
  tests/integration/programs.test.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/programsSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1173 COM-1664 return description in listUserCourses and listELearningDraft
  src/helpers/courses.js
  src/helpers/subPrograms.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/subPrograms.test.js
Labels: dev

#1172 Com 1698
  src/controllers/userController.js
  src/helpers/cards.js
  src/helpers/gCloudStorage.js
  src/helpers/programs.js
  src/helpers/users.js
  src/routes/preHandlers/users.js
  src/routes/users.js
  tests/integration/cards.test.js
  tests/integration/programs.test.js
  tests/integration/seed/programsSeed.js
  tests/integration/seed/usersSeed.js
  tests/integration/users.test.js
  tests/seed/userSeed.js
  tests/unit/helpers/cards.test.js
  tests/unit/helpers/programs.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1168 Com 1659
  src/controllers/programController.js
  src/helpers/programs.js
  src/helpers/translate.js
  src/routes/preHandlers/programs.js
  src/routes/programs.js
  tests/integration/programs.test.js
  tests/integration/seed/programsSeed.js
  tests/unit/helpers/programs.test.js
Labels: dev

#1171 Com 1661
  src/controllers/courseController.js
  src/data/courseConvocation.html
  src/helpers/courses.js
  src/helpers/utils.js
  src/routes/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1174 COM-1653: allow to create user to non registered person
  src/helpers/users.js
  src/routes/preHandlers/users.js
  src/routes/users.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1176 COM-1655 - add delete route
  src/controllers/courseController.js
  src/helpers/courses.js
  src/helpers/translate.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1177 Com 1661 design
  src/data/courseConvocation.html
  src/helpers/courses.js
  src/helpers/utils.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1170 Com 1656
  src/controllers/courseController.js
  src/controllers/programController.js
  src/helpers/courses.js
  src/helpers/programs.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/programs.test.js
Labels: dev

#1175 Com 1674
  src/controllers/activityController.js
  src/controllers/programController.js
  src/helpers/activities.js
  src/helpers/programs.js
  src/routes/activities.js
  src/routes/preHandlers/activities.js
  src/routes/programs.js
  tests/integration/activities.test.js
  tests/integration/programs.test.js
  tests/unit/helpers/activities.test.js
  tests/unit/helpers/programs.test.js
Labels: dev

#1180 MES
  src/controllers/activityController.js
  src/controllers/courseController.js
  src/controllers/programController.js
  src/data/courseConvocation.html
  src/helpers/activities.js
  src/helpers/courses.js
  src/helpers/programs.js
  src/helpers/utils.js
  src/routes/activities.js
  src/routes/courses.js
  src/routes/preHandlers/activities.js
  src/routes/preHandlers/courses.js
  src/routes/programs.js
  tests/integration/activities.test.js
  tests/integration/courses.test.js
  tests/integration/programs.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/activities.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/programs.test.js
Labels: staging

#1183 COM 1715 - npm update
  package-lock.json
  package.json
Labels: dev

#1184 Com 1711
  src/helpers/constants.js
  src/helpers/users.js
  src/models/User.js
  src/routes/users.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1185 Com 1691 - refacto qcm/qcu/questionAnswers
  src/helpers/cards.js
  src/models/Card.js
  src/models/validations/cardValidation.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
  tests/unit/helpers/cards.test.js
Labels: dev

#1186 Com 1710
  src/helpers/courses.js
  src/models/User.js
  src/routes/preHandlers/users.js
  src/routes/users.js
  tests/end2end/seed/billingSeed.js
  tests/end2end/seed/planningSeed.js
  tests/integration/courses.test.js
  tests/integration/seed/balanceSeed.js
  tests/integration/seed/billsSeed.js
  tests/integration/seed/companiesSeed.js
  tests/integration/seed/contractsSeed.js
  tests/integration/seed/courseSlotsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/creditNotesSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/driveSeed.js
  tests/integration/seed/emailSeed.js
  tests/integration/seed/establishmentsSeed.js
  tests/integration/seed/eventHistoriesSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/exportSeed.js
  tests/integration/seed/finalPaySeed.js
  tests/integration/seed/internalHoursSeed.js
  tests/integration/seed/payDocumentsSeed.js
  tests/integration/seed/paySeed.js
  tests/integration/seed/paymentsSeed.js
  tests/integration/seed/smsSeed.js
  tests/integration/seed/statsSeed.js
  tests/integration/seed/taxCertificatesSeed.js
  tests/integration/seed/usersSeed.js
  tests/integration/users.test.js
  tests/seed/userSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1187 Com 1691 put
  src/controllers/cardController.js
  src/helpers/cards.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
  tests/unit/helpers/cards.test.js
Labels: dev

#1188 Com 1532 seeds
  tests/integration/bills.test.js
  tests/integration/events.test.js
  tests/integration/seed/companiesSeed.js
  tests/integration/seed/customersSeed.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/contracts.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/dpae.test.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/eventHistories.test.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/historyExport.test.js
  tests/unit/helpers/pay.test.js
  tests/unit/helpers/stat.test.js
  tests/unit/helpers/subscriptions.test.js
Labels: dev

#1191 COM-1711 set firstMobileConnection when creating a user from mobile
  src/helpers/users.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1189 Com 1691 - post
  src/controllers/cardController.js
  src/helpers/cards.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
  tests/unit/helpers/cards.test.js
Labels: dev

#1190 Com 1691 - delete
  src/controllers/cardController.js
  src/helpers/cards.js
  src/helpers/constants.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
  tests/unit/helpers/cards.test.js
Labels: dev

#1193 COM-1690 refacto orderTheSequence
  src/helpers/cards.js
  src/helpers/constants.js
  src/models/Card.js
  src/models/validations/cardValidation.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
  tests/unit/helpers/cards.test.js
Labels: dev

#1195 Com 1690 post delete orderedAnswers
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
Labels: dev

#1196 Com 1693 refacto put
  src/helpers/cards.js
  src/helpers/constants.js
  src/models/Card.js
  src/models/validations/cardValidation.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
  tests/unit/helpers/cards.test.js
Labels: dev

#1200 Com 1729
  src/data/rights.js
  src/helpers/users.js
  src/routes/preHandlers/users.js
  tests/integration/roles.test.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: bug, dev

#1198 Com 1693 post delete
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
Labels: dev

#1194 Replacing sinon mongoose
  package-lock.json
  tests/unit/helpers/activities.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/sinonMongoose.js
Labels: dev

#1202 COM-1696: populate categories
  src/helpers/programs.js
  tests/unit/helpers/programs.test.js
Labels: dev

#1203 Com 1730 encoding
  src/helpers/dpae.js
  src/helpers/file.js
Labels: dev

#1206 COM-1742: send image for subprograms from back
  src/helpers/subPrograms.js
  tests/unit/helpers/subPrograms.test.js
Labels: bug

#1209 COM-1723 - npm update hapi
  package-lock.json
  package.json
Labels: dev

#1210 COM-1731 - npm update axios
  package-lock.json
  package.json
Labels: dev

#1211 COM-1769 category list without sinon-mongoose
  tests/unit/helpers/categories.test.js
Labels: dev

#1214 Com 1689 auth
  src/controllers/authenticationController.js
  src/controllers/userController.js
  src/helpers/authentication.js
  src/helpers/authorization.js
  src/helpers/email.js
  src/helpers/users.js
  src/plugins/hapiAuthJwt2.js
  src/routes/authentication.js
  src/routes/index.js
  src/routes/users.js
  tests/integration/authentication.test.js
  tests/integration/users.test.js
  tests/unit/helpers/activities.test.js
  tests/unit/helpers/authentication.test.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/categories.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/email.test.js
  tests/unit/helpers/users.test.js
  tests/unit/sinonMongoose.js
Labels: dev

#1215 Com 1736 remove Cloudinary
  package-lock.json
  package.json
  src/controllers/cloudinaryController.js
  src/helpers/cloudinary.js
  src/routes/cloudinary.js
  src/routes/index.js
  tests/unit/helpers/cloudinary.test.js
Labels: dev

#1217 COM-1736 - move link from cloudinary to GCS
  src/data/courseConvocation.html
  src/data/interAttendanceSheet.html
  src/data/intraAttendanceSheet.html
  tests/unit/helpers/billSlips.test.js
  tests/unit/helpers/taxCertificates.test.js
Labels: dev

#1216 COM-1717 - refacto upload pay document
  src/helpers/constants.js
  src/helpers/payDocuments.js
  src/routes/payDocuments.js
  tests/integration/payDocuments.test.js
  tests/unit/helpers/payDocuments.test.js
Labels: dev

#1218 COM-1780 - set adress in history if exists
  src/helpers/eventHistories.js
  tests/unit/helpers/eventHistories.test.js
Labels: bug

#1219 COM-1713
  src/routes/preHandlers/users.js
  src/routes/users.js
  tests/integration/users.test.js
Labels: dev

#1220 COM-1781 - companies tests
  tests/unit/helpers/companies.test.js
Labels: dev
