Repository CompaniTech/compani-api, pull requests merged in 2020-08, with the labels that each got.

#966 Com 1276 document
  src/helpers/draftPay.js
  src/helpers/events.js
  src/repositories/ContractRepository.js
  src/repositories/EventRepository.js
  src/routes/contracts.js
  tests/integration/contracts.test.js
  tests/unit/helpers/dataExport.test.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/events.test.js
Labels: dev

#972 COM-1413 add activity type
  src/helpers/constants.js
  src/models/Activity.js
  src/routes/steps.js
  tests/integration/seed/activitiesSeed.js
  tests/integration/seed/programsSeed.js
  tests/integration/steps.test.js
  tests/unit/helpers/steps.test.js
Labels: dev

#974 Com 1402 package
  package-lock.json
  package.json
  src/helpers/users.js
  tests/end2end/seed/billingSeed.js
  tests/end2end/seed/planningSeed.js
  tests/integration/seed/balanceSeed.js
  tests/integration/seed/billsSeed.js
  tests/integration/seed/companiesSeed.js
  tests/integration/seed/contractsSeed.js
  tests/integration/seed/courseSlotsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/creditNotesSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/driveSeed.js
  tests/integration/seed/emailSeed.js
  tests/integration/seed/establishmentsSeed.js
  tests/integration/seed/eventHistoriesSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/exportSeed.js
  tests/integration/seed/finalPaySeed.js
  tests/integration/seed/internalHoursSeed.js
  tests/integration/seed/payDocumentsSeed.js
  tests/integration/seed/paySeed.js
  tests/integration/seed/paymentsSeed.js
  tests/integration/seed/statsSeed.js
  tests/integration/seed/taxCertificatesSeed.js
  tests/integration/seed/twilioSeed.js
  tests/integration/seed/usersSeed.js
  tests/seed/userSeed.js
  tests/unit/helpers/users.test.js
Labels: dev

#975 COM-1404-sub-program add subProgram model, creation, edition
  src/controllers/programController.js
  src/controllers/subProgramController.js
  src/helpers/programs.js
  src/helpers/steps.js
  src/helpers/subPrograms.js
  src/helpers/translate.js
  src/models/Program.js
  src/models/SubProgram.js
  src/routes/activities.js
  src/routes/index.js
  src/routes/programs.js
  src/routes/steps.js
  src/routes/subPrograms.js
  tests/integration/activities.test.js
  tests/integration/programs.test.js
  tests/integration/seed/programsSeed.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/steps.test.js
  tests/integration/subProgram.test.js
  tests/unit/helpers/programs.test.js
  tests/unit/helpers/steps.test.js
  tests/unit/helpers/subProgram.test.js
Labels: dev

#979 COM-1382 - Add address to slots in get course call for /course/id/user
  .eslintrc.js
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#984 COM-1405 - step is required
  src/models/CourseSlot.js
  src/routes/courseSlots.js
  tests/integration/courseSlots.test.js
  tests/integration/seed/courseSlotsSeed.js
  tests/unit/helpers/courseSlots.test.js
Labels: dev

#990 Com 1412
  src/models/Card.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
Labels: dev

#991 Com 1411
  src/helpers/constants.js
  src/models/Card.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
Labels: dev

#1002 Com 1452 staging
  src/data/bill.html
  src/helpers/bills.js
  tests/unit/helpers/bills.test.js
Labels: staging

#1001 Com 1327
  src/controllers/cardController.js
  src/helpers/cards.js
  src/helpers/translate.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
  tests/unit/helpers/cards.test.js
Labels: dev

#1003 Staging
  src/data/bill.html
  src/helpers/bills.js
  src/helpers/eventsValidation.js
  src/helpers/utils.js
  tests/integration/events.test.js
  tests/integration/seed/eventsSeed.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/utils.test.js
Labels: master

#1008 COM-1426 can detach step from subprogram
  src/controllers/subProgramController.js
  src/helpers/steps.js
  src/routes/preHandlers/subPrograms.js
  src/routes/subPrograms.js
  tests/integration/subPrograms.test.js
  tests/unit/helpers/steps.test.js
Labels: dev

#1009 COM-1438 add questionnaire template constants
  src/helpers/constants.js
  src/models/Card.js
Labels: dev

#1010 COM-1410 - Add QCM template
  src/helpers/constants.js
  src/models/Card.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
Labels: dev

#1012 Com 1427
  src/helpers/cards.js
  src/helpers/constants.js
  src/models/Card.js
  src/routes/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
Labels: dev

#1005 Com 1429 reuse
  src/helpers/activities.js
  src/helpers/cards.js
  src/helpers/steps.js
  src/helpers/subPrograms.js
  src/routes/activities.js
  src/routes/preHandlers/activities.js
  src/routes/preHandlers/programs.js
  src/routes/preHandlers/steps.js
  src/routes/preHandlers/subPrograms.js
  src/routes/programs.js
  src/routes/steps.js
  src/routes/subPrograms.js
  tests/integration/activities.test.js
  tests/integration/programs.test.js
  tests/integration/seed/stepsSeed.js
  tests/integration/steps.test.js
  tests/integration/subPrograms.test.js
  tests/unit/helpers/activities.test.js
  tests/unit/helpers/cards.test.js
  tests/unit/helpers/steps.test.js
  tests/unit/helpers/subProgram.test.js
Labels: dev
