Repository CompaniTech/compani-api, pull requests merged in 2020-11, with the labels that each got.

#1102 Com 1615 refresh
  src/controllers/programController.js
  src/helpers/courses.js
  src/helpers/programs.js
  src/models/Activity.js
  src/models/Course.js
  src/routes/preHandlers/programs.js
  src/routes/programs.js
  tests/integration/programs.test.js
  tests/integration/seed/programsSeed.js
  tests/unit/helpers/programs.test.js
Labels: dev

#1101 Com 1611 infinite scroll
  src/helpers/courseHistories.js
  src/routes/courseHistories.js
  tests/integration/courseHistories.test.js
  tests/integration/seed/courseHistoriesSeed.js
  tests/unit/helpers/courseHistories.test.js
Labels: dev

#1099 Com 1605
  src/controllers/contractController.js
  src/data/bicBankMatching.js
  src/data/countries.js
  src/helpers/dpae.js
  src/helpers/draftPay.js
  src/helpers/file.js
  src/helpers/taxCertificates.js
  src/models/User.js
  src/routes/contracts.js
  tests/integration/companies.test.js
  tests/integration/contracts.test.js
  tests/integration/courses.test.js
  tests/integration/events.test.js
  tests/integration/exports.test.js
  tests/integration/seed/billsSeed.js
  tests/integration/seed/contractsSeed.js
  tests/integration/seed/creditNotesSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/emailSeed.js
  tests/integration/seed/establishmentsSeed.js
  tests/integration/seed/eventHistoriesSeed.js
  tests/integration/seed/exportSeed.js
  tests/integration/seed/finalPaySeed.js
  tests/integration/seed/internalHoursSeed.js
  tests/integration/seed/paySeed.js
  tests/integration/seed/statsSeed.js
  tests/integration/seed/usersSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/dpae.test.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/taxCertificates.test.js
Labels: dev

#1103 Com 1617
  src/helpers/translate.js
  src/models/SubProgram.js
  src/routes/preHandlers/subPrograms.js
  tests/integration/activities.test.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/subPrograms.test.js
Labels: dev

#1104 COM-1612 - Create coursehistory on slot deletion
  src/controllers/courseSlotController.js
  src/helpers/constants.js
  src/helpers/courseHistories.js
  src/helpers/courseSlots.js
  src/models/CourseHistory.js
  tests/integration/courseSlots.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courseSlots.test.js
Labels: dev

#1105 Com 1616 getLearnerList
  src/controllers/userController.js
  src/helpers/users.js
  src/routes/preHandlers/users.js
  src/routes/users.js
  tests/integration/seed/usersSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1107 COM-1618 creation of CourseHistory object at updateCourseSlot()
  src/controllers/courseSlotController.js
  src/helpers/constants.js
  src/helpers/courseHistories.js
  src/helpers/courseSlots.js
  src/models/CourseHistory.js
  tests/integration/courseSlots.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courseSlots.test.js
Labels: dev

#1109 Com 1601 refacto
  src/helpers/courses.js
  src/helpers/steps.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/steps.test.js
Labels: dev

#1106 Com 1613
  src/controllers/courseController.js
  src/helpers/constants.js
  src/helpers/courseHistories.js
  src/helpers/courseSlots.js
  src/helpers/courses.js
  src/models/CourseHistory.js
  tests/integration/courses.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courseSlots.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1108 COM-1614 - Add course history on trainee deletion
  src/controllers/courseController.js
  src/helpers/constants.js
  src/helpers/courseHistories.js
  src/helpers/courses.js
  src/models/CourseHistory.js
  tests/integration/courses.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1113 Com 1600
  src/helpers/courses.js
  src/helpers/steps.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1111 COM-1619 new hour
  src/helpers/courseHistories.js
  src/models/CourseHistory.js
  tests/integration/courseSlots.test.js
  tests/unit/helpers/courseHistories.test.js
Labels: dev

#1116 Dev
  src/helpers/contracts.js
  src/helpers/courseHistories.js
  src/helpers/courses.js
  src/helpers/dpae.js
  src/helpers/steps.js
  src/models/BillNumber.js
  src/models/BillSlip.js
  src/models/BillSlipNumber.js
  src/models/Contract.js
  src/models/ContractNumber.js
  src/models/CourseHistory.js
  src/models/CreditNoteNumber.js
  src/models/PaymentNumber.js
  src/models/QuoteNumber.js
  src/models/Rum.js
  tests/end2end/seed/billingSeed.js
  tests/end2end/seed/planningSeed.js
  tests/integration/contracts.test.js
  tests/integration/courseSlots.test.js
  tests/integration/courses.test.js
  tests/integration/seed/billsSeed.js
  tests/integration/seed/contractsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/exportSeed.js
  tests/integration/seed/finalPaySeed.js
  tests/integration/seed/paySeed.js
  tests/integration/seed/statsSeed.js
  tests/integration/seed/usersSeed.js
  tests/unit/helpers/contracts.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/customers.test.js
  tests/unit/helpers/dpae.test.js
Labels: staging

#1115 Com 1647 - Refacto CourseId
  src/helpers/courseHistories.js
  src/helpers/courseSlots.js
  src/helpers/courses.js
  src/models/Course.js
  src/models/CourseSlot.js
  src/routes/courseSlots.js
  src/routes/preHandlers/courseSlot.js
  tests/integration/courseSlots.test.js
  tests/integration/courses.test.js
  tests/integration/seed/courseSlotsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courseSlots.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1118 Com 1628 - Upload Image, Video and Audio
  src/helpers/constants.js
  src/models/Card.js
  src/routes/cards.js
  tests/integration/cards.test.js
Labels: dev

#1119 COM-1626 - add paidTransportHours and absencesHours
  src/helpers/historyExport.js
  tests/integration/exports.test.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1120 COM-1631 user roles are not required anymore
  src/routes/users.js
Labels: dev

#1122 Com 1628 - Google Cloud Storage
  package-lock.json
  package.json
  src/helpers/cards.js
  src/helpers/gCloudStorage.js
  src/models/Google/Storage.js
  tests/integration/cards.test.js
  tests/unit/helpers/cards.test.js
Labels: dev

#1123 COM-1627 add QUESTIONNAIRE activity type
  src/helpers/constants.js
  src/models/Activity.js
Labels: dev

#1121 COM-1631 add filter to learnerDirectory on client side
  src/helpers/users.js
  tests/unit/helpers/users.test.js
Labels: dev

#1124 COM-1634 add misc in return course for user
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1127 Com 1650
  src/controllers/cardController.js
  src/controllers/programController.js
  src/helpers/cards.js
  src/helpers/constants.js
  src/helpers/gCloudStorage.js
  src/helpers/programs.js
  src/routes/Google/drive.js
  src/routes/administrativeDocuments.js
  src/routes/cards.js
  src/routes/companies.js
  src/routes/contracts.js
  src/routes/customers.js
  src/routes/payDocuments.js
  src/routes/preHandlers/programs.js
  src/routes/programs.js
  src/routes/taxCertificates.js
  src/routes/users.js
  src/routes/validations/utils.js
  tests/integration/cards.test.js
  tests/integration/programs.test.js
  tests/integration/users.test.js
  tests/unit/helpers/cards.test.js
  tests/unit/helpers/programs.test.js
Labels: dev

#1128 Com 1630 LearnersInfo
  src/helpers/courses.js
  src/helpers/users.js
  src/models/User.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1126 COM-1638: update profile infos
  src/helpers/authentication.js
  src/routes/preHandlers/users.js
  tests/integration/users.test.js
  tests/seed/userSeed.js
  tests/unit/helpers/authentication.test.js
Labels: dev

#1129 Com 1633
  src/controllers/courseController.js
  src/helpers/courses.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1135 Com 1641 refacto with virtual IsStrictlyELearning
  src/helpers/subPrograms.js
  tests/unit/helpers/subPrograms.test.js
Labels: dev

#1136 Com 1630 list user course
  src/controllers/courseController.js
  src/helpers/courses.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1132 Com 1625 - Ajout des tests
  src/helpers/draftPay.js
  src/helpers/historyExport.js
  src/repositories/EventRepository.js
  tests/integration/exports.test.js
  tests/integration/seed/exportSeed.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1138 Com 1603
  src/models/Activity.js
  src/models/Step.js
  src/models/SubProgram.js
  src/routes/preHandlers/subPrograms.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/subPrograms.test.js
Labels: dev

#1145 Refacto create drive
  src/controllers/userController.js
  src/helpers/users.js
  src/routes/users.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1143 Com 1672 - npm update
  package-lock.json
  package.json
Labels: dev

#1148 Com 1630 fix
  src/helpers/courses.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: bug

#1146 COM-1653: create route
  src/helpers/users.js
  src/routes/users.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1149 Com 1657 view and add categories
  src/controllers/categoryController.js
  src/helpers/categories.js
  src/helpers/translate.js
  src/models/Category.js
  src/routes/categories.js
  src/routes/index.js
  src/routes/preHandlers/categories.js
  tests/integration/categories.test.js
  tests/integration/seed/categoriesSeed.js
  tests/unit/helpers/categories.test.js
Labels: dev

#1150 Com 1654
  src/helpers/subPrograms.js
  src/models/Course.js
  src/routes/preHandlers/subPrograms.js
  src/routes/subPrograms.js
  tests/integration/subPrograms.test.js
  tests/unit/helpers/subPrograms.test.js
Labels: dev

#1152 COM-1665: externalize getprogress in back
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1153 Com 1657 update (PUT ROUTE)
  src/controllers/categoryController.js
  src/helpers/categories.js
  src/helpers/translate.js
  src/routes/categories.js
  src/routes/preHandlers/categories.js
  tests/integration/categories.test.js
  tests/unit/helpers/categories.test.js
Labels: dev

#1156 Com 1672
  package-lock.json
  package.json
Labels: dev

#1155 Com 1657 delete
  src/controllers/categoryController.js
  src/helpers/categories.js
  src/helpers/translate.js
  src/routes/categories.js
  src/routes/preHandlers/categories.js
  tests/integration/categories.test.js
  tests/unit/helpers/categories.test.js
Labels: dev

#1159 Com 1652 staging
  src/helpers/authentication.js
  src/helpers/users.js
  src/models/AdministrativeDocument.js
  src/models/Bill.js
  src/models/BillNumber.js
  src/models/BillSlip.js
  src/models/BillSlipNumber.js
  src/models/Contract.js
  src/models/ContractNumber.js
  src/models/CreditNote.js
  src/models/CreditNoteNumber.js
  src/models/Customer.js
  src/models/DistanceMatrix.js
  src/models/Establishment.js
  src/models/Event.js
  src/models/EventHistory.js
  src/models/FinalPay.js
  src/models/FundingHistory.js
  src/models/InternalHour.js
  src/models/Pay.js
  src/models/PayDocument.js
  src/models/Payment.js
  src/models/PaymentNumber.js
  src/models/QuoteNumber.js
  src/models/ReferentHistory.js
  src/models/Repetition.js
  src/models/Rum.js
  src/models/Sector.js
  src/models/SectorHistory.js
  src/models/Service.js
  src/models/Surcharge.js
  src/models/TaxCertificate.js
  src/models/ThirdPartyPayer.js
  src/models/User.js
  src/models/preHooks/validate.js
  src/routes/preHandlers/users.js
  tests/integration/users.test.js
  tests/seed/userSeed.js
  tests/unit/helpers/authentication.test.js
  tests/unit/helpers/users.test.js
Labels: staging

#1162 Refacto internal hour
  src/controllers/internalHourController.js
  src/helpers/events.js
  src/helpers/internalHours.js
  src/helpers/translate.js
  src/models/InternalHour.js
  src/routes/internalHours.js
  src/routes/preHandlers/internalHours.js
  tests/integration/internalHours.test.js
  tests/integration/seed/internalHoursSeed.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/internalHours.test.js
Labels: dev
