Repository CompaniTech/compani-api, pull requests merged in 2020-09, with the labels that each got.

#1018 COM-1439 add test for open question edition
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
Labels: dev

#1022 Com 1458
  src/controllers/stepController.js
  src/helpers/steps.js
  src/routes/preHandlers/steps.js
  src/routes/preHandlers/subPrograms.js
  src/routes/steps.js
  tests/integration/seed/stepsSeed.js
  tests/integration/steps.test.js
  tests/unit/helpers/steps.test.js
Labels: dev

#1024 COM-1459 - drag and drop cards
  src/routes/activities.js
  src/routes/preHandlers/activities.js
  src/routes/programs.js
  src/routes/steps.js
  src/routes/subPrograms.js
  tests/integration/activities.test.js
  tests/integration/programs.test.js
  tests/integration/steps.test.js
  tests/integration/subPrograms.test.js
Labels: dev

#1027 COM-1496 - remove expiresIn
  src/helpers/users.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1029 Com 1461
  src/routes/preHandlers/steps.js
  src/routes/preHandlers/subPrograms.js
  tests/integration/seed/stepsSeed.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/steps.test.js
  tests/integration/subPrograms.test.js
Labels: dev

#1030 COM-1463 routes to update activities return forbidden if activity is …
  src/routes/preHandlers/activities.js
  tests/integration/activities.test.js
  tests/integration/seed/activitiesSeed.js
Labels: dev

#1032 COM-1489 fix apa hours when funding has ended
  src/repositories/StatRepository.js
  tests/integration/seed/statsSeed.js
  tests/integration/stat.test.js
Labels: bug, dev

#1028 Com 1464 - ActivityHistory
  src/controllers/activityHistoryController.js
  src/helpers/activityHistories.js
  src/helpers/translate.js
  src/models/ActivityHistory.js
  src/routes/activityHistories.js
  src/routes/index.js
  src/routes/preHandlers/activityHistories.js
  tests/integration/activityHistories.test.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/unit/helpers/activityHistories.test.js
Labels: dev

#1036 Dev
  src/controllers/activityHistoryController.js
  src/controllers/stepController.js
  src/helpers/activityHistories.js
  src/helpers/constants.js
  src/helpers/dataExport.js
  src/helpers/historyExport.js
  src/helpers/steps.js
  src/helpers/subPrograms.js
  src/helpers/translate.js
  src/helpers/users.js
  src/models/Activity.js
  src/models/ActivityHistory.js
  src/models/Step.js
  src/models/SubProgram.js
  src/repositories/EventRepository.js
  src/repositories/StatRepository.js
  src/routes/activities.js
  src/routes/activityHistories.js
  src/routes/index.js
  src/routes/preHandlers/activities.js
  src/routes/preHandlers/activityHistories.js
  src/routes/preHandlers/cards.js
  src/routes/preHandlers/steps.js
  src/routes/preHandlers/subPrograms.js
  src/routes/programs.js
  src/routes/steps.js
  src/routes/subPrograms.js
  tests/integration/activities.test.js
  tests/integration/activityHistories.test.js
  tests/integration/cards.test.js
  tests/integration/exports.test.js
  tests/integration/programs.test.js
  tests/integration/seed/activitiesSeed.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/integration/seed/cardsSeed.js
  tests/integration/seed/exportSeed.js
  tests/integration/seed/statsSeed.js
  tests/integration/seed/stepsSeed.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/stat.test.js
  tests/integration/steps.test.js
  tests/integration/subPrograms.test.js
  tests/integration/users.test.js
  tests/unit/helpers/activityHistories.test.js
  tests/unit/helpers/dataExport.test.js
  tests/unit/helpers/historyExport.test.js
  tests/unit/helpers/steps.test.js
  tests/unit/helpers/subProgram.test.js
  tests/unit/helpers/users.test.js
Labels: staging

#1035 Com 1465 2
  src/controllers/courseController.js
  src/helpers/courses.js
  src/models/Activity.js
  src/models/Course.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1042 Staging
  src/controllers/activityHistoryController.js
  src/controllers/courseController.js
  src/controllers/stepController.js
  src/helpers/activityHistories.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/dataExport.js
  src/helpers/historyExport.js
  src/helpers/steps.js
  src/helpers/subPrograms.js
  src/helpers/translate.js
  src/helpers/users.js
  src/models/Activity.js
  src/models/ActivityHistory.js
  src/models/Course.js
  src/models/Step.js
  src/models/SubProgram.js
  src/repositories/EventRepository.js
  src/repositories/StatRepository.js
  src/routes/activities.js
  src/routes/activityHistories.js
  src/routes/index.js
  src/routes/preHandlers/activities.js
  src/routes/preHandlers/activityHistories.js
  src/routes/preHandlers/cards.js
  src/routes/preHandlers/steps.js
  src/routes/preHandlers/subPrograms.js
  src/routes/programs.js
  src/routes/steps.js
  src/routes/subPrograms.js
  tests/integration/activities.test.js
  tests/integration/activityHistories.test.js
  tests/integration/cards.test.js
  tests/integration/courses.test.js
  tests/integration/exports.test.js
  tests/integration/programs.test.js
  tests/integration/seed/activitiesSeed.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/integration/seed/cardsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/exportSeed.js
  tests/integration/seed/statsSeed.js
  tests/integration/seed/stepsSeed.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/stat.test.js
  tests/integration/steps.test.js
  tests/integration/subPrograms.test.js
  tests/integration/users.test.js
  tests/unit/helpers/activityHistories.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/dataExport.test.js
  tests/unit/helpers/historyExport.test.js
  tests/unit/helpers/steps.test.js
  tests/unit/helpers/subProgram.test.js
  tests/unit/helpers/users.test.js
Labels: master

#1047 Com 1509
  src/models/ActivityHistory.js
  src/routes/activityHistories.js
  src/routes/preHandlers/activityHistories.js
  tests/integration/activityHistories.test.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/unit/helpers/activityHistories.test.js
Labels: dev

#1048 Com 1544
  package-lock.json
  package.json
Labels: dev

#1049 COM-1507: units and integration test for open question
  src/routes/preHandlers/activityHistories.js
  tests/integration/activityHistories.test.js
  tests/integration/seed/activityHistoriesSeed.js
Labels: dev

#1054 COM-1498 rename learningGoals to description
  src/helpers/courses.js
  src/models/Program.js
  src/routes/programs.js
  tests/integration/courses.test.js
  tests/integration/programs.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev
