Repository CompaniTech/compani-api, pull requests merged in 2020-10, with the labels that each got.

#1053 Com 1509 - get ActivityHistories
  src/controllers/activityController.js
  src/helpers/activities.js
  src/helpers/translate.js
  src/routes/activities.js
  src/routes/preHandlers/activities.js
  tests/integration/activities.test.js
  tests/integration/seed/activitiesSeed.js
  tests/unit/helpers/activities.test.js
Labels: dev

#1055 COM-1534 check that startDate and endDate are on same day for a cours…
  src/routes/preHandlers/courseSlot.js
  tests/integration/courseSlots.test.js
Labels: dev

#1056 COM-1500 add questionAnswer edition
  src/helpers/constants.js
  src/models/Card.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
Labels: dev

#1057 Dev
  .github/workflows/lint.yml
  package-lock.json
  package.json
  src/controllers/activityController.js
  src/helpers/activities.js
  src/helpers/cloudinary.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/subPrograms.js
  src/helpers/translate.js
  src/models/Activity.js
  src/models/ActivityHistory.js
  src/models/Card.js
  src/models/Course.js
  src/models/Program.js
  src/models/Step.js
  src/models/SubProgram.js
  src/routes/activities.js
  src/routes/activityHistories.js
  src/routes/cards.js
  src/routes/courses.js
  src/routes/preHandlers/activities.js
  src/routes/preHandlers/activityHistories.js
  src/routes/preHandlers/cards.js
  src/routes/preHandlers/courseSlot.js
  src/routes/programs.js
  src/routes/subPrograms.js
  tests/integration/activities.test.js
  tests/integration/activityHistories.test.js
  tests/integration/cards.test.js
  tests/integration/courseSlots.test.js
  tests/integration/courses.test.js
  tests/integration/programs.test.js
  tests/integration/seed/activitiesSeed.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/integration/seed/cardsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/subPrograms.test.js
  tests/integration/users.test.js
  tests/unit/helpers/activities.test.js
  tests/unit/helpers/activityHistories.test.js
  tests/unit/helpers/cloudinary.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/subProgram.test.js
Labels: staging

#1058 Dev
  package-lock.json
  package.json
Labels: staging

#1061 Staging
  .github/workflows/lint.yml
  package-lock.json
  package.json
  src/controllers/activityController.js
  src/helpers/activities.js
  src/helpers/cloudinary.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/subPrograms.js
  src/helpers/translate.js
  src/models/Activity.js
  src/models/ActivityHistory.js
  src/models/Card.js
  src/models/Course.js
  src/models/Program.js
  src/models/Step.js
  src/models/SubProgram.js
  src/routes/activities.js
  src/routes/activityHistories.js
  src/routes/cards.js
  src/routes/courses.js
  src/routes/preHandlers/activities.js
  src/routes/preHandlers/activityHistories.js
  src/routes/preHandlers/cards.js
  src/routes/preHandlers/courseSlot.js
  src/routes/programs.js
  src/routes/subPrograms.js
  tests/integration/activities.test.js
  tests/integration/activityHistories.test.js
  tests/integration/cards.test.js
  tests/integration/courseSlots.test.js
  tests/integration/courses.test.js
  tests/integration/programs.test.js
  tests/integration/seed/activitiesSeed.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/integration/seed/cardsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/subPrograms.test.js
  tests/integration/users.test.js
  tests/unit/helpers/activities.test.js
  tests/unit/helpers/activityHistories.test.js
  tests/unit/helpers/cloudinary.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/subProgram.test.js
Labels: master

#1060 Com 1518
  src/helpers/constants.js
  src/helpers/courses.js
  src/models/Activity.js
  src/models/ActivityHistory.js
  src/routes/activityHistories.js
  tests/integration/activityHistories.test.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1062 COM-1555 - Add virtual isValid to card
  src/helpers/activities.js
  src/models/Card.js
  src/models/validations/cardValidation.js
  tests/integration/cards.test.js
  tests/integration/courses.test.js
Labels: dev

#1063 COM-1527 - Add areCardsValid virtual
  src/helpers/programs.js
  src/models/Activity.js
  tests/integration/courses.test.js
  tests/integration/programs.test.js
  tests/integration/seed/programsSeed.js
  tests/unit/helpers/programs.test.js
Labels: dev

#1064 Com 1525
  src/controllers/programController.js
  src/helpers/programs.js
  src/models/SubProgram.js
  src/routes/programs.js
  tests/integration/programs.test.js
  tests/integration/seed/programsSeed.js
  tests/unit/helpers/programs.test.js
Labels: dev

#1065 COM-1528 - Add areActivitiesValid virtual
  src/models/Activity.js
  src/models/Step.js
  tests/integration/courses.test.js
  tests/integration/programs.test.js
  tests/unit/helpers/programs.test.js
Labels: dev

#1068 COM-1574 added type to payload
  src/routes/activities.js
Labels: dev

#1067 Com 1549
  src/helpers/draftPay.js
  src/helpers/historyExport.js
  src/models/Company.js
  src/models/schemaDefinitions/pay.js
  src/repositories/ContractRepository.js
  src/routes/companies.js
  src/routes/validations/pay.js
  tests/integration/companies.test.js
  tests/integration/exports.test.js
  tests/integration/finalPay.test.js
  tests/integration/pay.test.js
  tests/integration/seed/companiesSeed.js
  tests/integration/seed/exportSeed.js
  tests/unit/helpers/draftFinalPay.test.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1069 Com 1572
  src/helpers/subscriptions.js
  src/models/Customer.js
  src/routes/customers.js
  tests/integration/seed/customersSeed.js
  tests/unit/helpers/subscriptions.test.js
Labels: dev

#1071 Com 1516
  src/controllers/courseController.js
  src/helpers/courses.js
  src/routes/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1074 COM-1572 remove sub from subHistory
  src/helpers/subscriptions.js
  src/routes/customers.js
  tests/integration/customers.test.js
  tests/unit/helpers/subscriptions.test.js
Labels: dev

#1076 Dev
  src/controllers/courseController.js
  src/controllers/programController.js
  src/helpers/activities.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/draftPay.js
  src/helpers/historyExport.js
  src/helpers/programs.js
  src/helpers/subscriptions.js
  src/helpers/users.js
  src/models/Activity.js
  src/models/ActivityHistory.js
  src/models/Card.js
  src/models/Company.js
  src/models/Customer.js
  src/models/Step.js
  src/models/SubProgram.js
  src/models/User.js
  src/models/schemaDefinitions/pay.js
  src/models/validations/cardValidation.js
  src/repositories/ContractRepository.js
  src/repositories/EventRepository.js
  src/routes/activities.js
  src/routes/activityHistories.js
  src/routes/companies.js
  src/routes/courses.js
  src/routes/customers.js
  src/routes/programs.js
  src/routes/validations/pay.js
  tests/integration/activityHistories.test.js
  tests/integration/cards.test.js
  tests/integration/companies.test.js
  tests/integration/courses.test.js
  tests/integration/customers.test.js
  tests/integration/exports.test.js
  tests/integration/finalPay.test.js
  tests/integration/pay.test.js
  tests/integration/programs.test.js
  tests/integration/seed/companiesSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/exportSeed.js
  tests/integration/seed/programsSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/draftFinalPay.test.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/historyExport.test.js
  tests/unit/helpers/programs.test.js
  tests/unit/helpers/subscriptions.test.js
  tests/unit/helpers/users.test.js
Labels: staging

#1075 COM-1549 fix phonefees if there was a phone invoice
  src/helpers/draftPay.js
  tests/unit/helpers/draftPay.test.js
Labels: dev

#1077 Com 1516 user
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1078 Dev
  src/helpers/courses.js
  src/helpers/draftPay.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/draftPay.test.js
Labels: staging

#1079 COM-1593 edited baseWelcomeContent
  src/helpers/emailOptions.js
Labels: dev

#1081 Com 1587
  src/controllers/serviceController.js
  src/helpers/services.js
  src/models/Service.js
  src/routes/preHandlers/services.js
  src/routes/services.js
  tests/integration/seed/servicesSeed.js
  tests/integration/services.test.js
  tests/unit/helpers/services.test.js
Labels: dev

#1082 Com 1596 edition
  src/controllers/cardController.js
  src/helpers/cards.js
  src/models/Card.js
  src/models/validations/cardValidation.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
  tests/unit/helpers/cards.test.js
Labels: dev

#1085 COM-1608 - from aggregation to populate
  src/helpers/customers.js
  src/repositories/CustomerRepository.js
  tests/unit/helpers/authentication.test.js
  tests/unit/helpers/customers.test.js
Labels: bug, dev

#1086 COM-1582 - add course deletion
  src/controllers/courseController.js
  src/helpers/courses.js
  src/helpers/translate.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1087 Com 1589
  src/helpers/courses.js
  src/models/ActivityHistory.js
  src/routes/activityHistories.js
  src/routes/preHandlers/activityHistories.js
  tests/integration/activities.test.js
  tests/integration/activityHistories.test.js
  tests/integration/seed/activitiesSeed.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/unit/helpers/activityHistories.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1088 Com 1596
  src/controllers/cardController.js
  src/helpers/cards.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
  tests/unit/helpers/cards.test.js
Labels: dev

#1089 COM-1587 cant add or edit event with service archived
  src/routes/preHandlers/events.js
  tests/integration/events.test.js
  tests/integration/seed/eventsSeed.js
Labels: dev

#1090 Com 1596 deleteAnswer
  src/controllers/cardController.js
  src/helpers/cards.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
Labels: dev

#1091 Com 1591
  src/data/interAttendanceSheet.html
  src/data/intraAttendanceSheet.html
  src/helpers/courses.js
  src/helpers/pdf.js
  src/helpers/utils.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1092 COM-1596 - Add tests
  src/helpers/constants.js
  tests/integration/cards.test.js
  tests/unit/helpers/cards.test.js
Labels: dev

#1093 Dev
  src/controllers/cardController.js
  src/controllers/courseController.js
  src/controllers/serviceController.js
  src/data/interAttendanceSheet.html
  src/data/intraAttendanceSheet.html
  src/helpers/cards.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/customers.js
  src/helpers/emailOptions.js
  src/helpers/pdf.js
  src/helpers/services.js
  src/helpers/subscriptions.js
  src/helpers/translate.js
  src/helpers/utils.js
  src/models/ActivityHistory.js
  src/models/Card.js
  src/models/Service.js
  src/models/validations/cardValidation.js
  src/repositories/CustomerRepository.js
  src/routes/activityHistories.js
  src/routes/cards.js
  src/routes/courses.js
  src/routes/customers.js
  src/routes/preHandlers/activityHistories.js
  src/routes/preHandlers/cards.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/customers.js
  src/routes/preHandlers/events.js
  src/routes/preHandlers/services.js
  src/routes/services.js
  tests/integration/activities.test.js
  tests/integration/activityHistories.test.js
  tests/integration/cards.test.js
  tests/integration/courses.test.js
  tests/integration/customers.test.js
  tests/integration/events.test.js
  tests/integration/seed/activitiesSeed.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/integration/seed/cardsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/servicesSeed.js
  tests/integration/services.test.js
  tests/unit/helpers/activityHistories.test.js
  tests/unit/helpers/authentication.test.js
  tests/unit/helpers/cards.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/customers.test.js
  tests/unit/helpers/services.test.js
  tests/unit/helpers/subscriptions.test.js
Labels: staging

#1095 MEP
  src/controllers/cardController.js
  src/controllers/courseController.js
  src/controllers/serviceController.js
  src/data/interAttendanceSheet.html
  src/data/intraAttendanceSheet.html
  src/helpers/cards.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/customers.js
  src/helpers/emailOptions.js
  src/helpers/pdf.js
  src/helpers/services.js
  src/helpers/subscriptions.js
  src/helpers/translate.js
  src/helpers/utils.js
  src/models/ActivityHistory.js
  src/models/Card.js
  src/models/Service.js
  src/models/validations/cardValidation.js
  src/repositories/CustomerRepository.js
  src/routes/activityHistories.js
  src/routes/cards.js
  src/routes/courses.js
  src/routes/customers.js
  src/routes/preHandlers/activityHistories.js
  src/routes/preHandlers/cards.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/customers.js
  src/routes/preHandlers/events.js
  src/routes/preHandlers/services.js
  src/routes/services.js
  tests/integration/activities.test.js
  tests/integration/activityHistories.test.js
  tests/integration/cards.test.js
  tests/integration/courses.test.js
  tests/integration/customers.test.js
  tests/integration/events.test.js
  tests/integration/seed/activitiesSeed.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/integration/seed/cardsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/servicesSeed.js
  tests/integration/services.test.js
  tests/unit/helpers/activityHistories.test.js
  tests/unit/helpers/authentication.test.js
  tests/unit/helpers/cards.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/customers.test.js
  tests/unit/helpers/services.test.js
  tests/unit/helpers/subscriptions.test.js
Labels: master

#1094 Com 1611 - CourseHistory
  src/controllers/courseSlotController.js
  src/helpers/constants.js
  src/helpers/courseHistories.js
  src/helpers/courseSlots.js
  src/models/CourseHistory.js
  tests/integration/courseSlots.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courseSlots.test.js
Labels: dev

#1096 Com 1615
  src/controllers/courseController.js
  src/controllers/programController.js
  src/helpers/courses.js
  src/helpers/programs.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/programs.test.js
Labels: dev

#1098 COM-1598:
  src/controllers/subProgramController.js
  src/helpers/subPrograms.js
  src/helpers/translate.js
  src/models/Step.js
  src/routes/preHandlers/subPrograms.js
  src/routes/subPrograms.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/subPrograms.test.js
  tests/unit/helpers/subPrograms.test.js
Labels: dev

#1097 COM-1611
  src/controllers/courseHistoryController.js
  src/helpers/courseHistories.js
  src/helpers/translate.js
  src/routes/courseHistories.js
  src/routes/index.js
  src/routes/preHandlers/courseHistories.js
  tests/integration/courseHistories.test.js
  tests/integration/seed/courseHistoriesSeed.js
  tests/unit/helpers/courseHistories.test.js
Labels: dev

#1100 COM-1552 FlashCard add back validation
  src/helpers/constants.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
Labels: dev
