Repository CompaniTech/compani-api, pull requests merged in 2021-06, with the labels that each got.

#1436 Com 2090
  src/helpers/dates.js
  src/helpers/events.js
  src/helpers/eventsValidation.js
  src/models/Event.js
  src/models/preHooks/validate.js
  src/repositories/EventRepository.js
  src/routes/preHandlers/events.js
  tests/integration/events.test.js
  tests/integration/seed/eventsSeed.js
  tests/unit/helpers/eventsValidation.test.js
Labels: dev

#1439 Com 2081 fix
  src/helpers/draftBills.js
  tests/unit/helpers/draftbills.test.js
Labels: bug, dev

#1438 Com 2095
  src/helpers/eventsValidation.js
  src/repositories/CustomerRepository.js
  src/repositories/EventRepository.js
  tests/unit/helpers/eventsValidation.test.js
Labels: dev

#1441 Com 2091
  src/helpers/eventsValidation.js
  src/models/Event.js
  src/repositories/EventRepository.js
  src/routes/preHandlers/events.js
  tests/integration/events.test.js
  tests/integration/seed/eventsSeed.js
  tests/unit/helpers/eventsValidation.test.js
Labels: dev

#1445 COM-2156: npm update
  package-lock.json
  package.json
Labels: dev

#1447 add function to create userCompany with verification
  src/helpers/userCompanies.js
  src/helpers/users.js
  tests/unit/helpers/userCompanies.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1448 Fix getEventsGroupedBy
  src/repositories/EventRepository.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/paySeed.js
Labels: dev

#1449 MES
  src/helpers/userCompanies.js
  src/helpers/users.js
  src/repositories/EventRepository.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/paySeed.js
  tests/unit/helpers/userCompanies.test.js
  tests/unit/helpers/users.test.js
Labels: staging

#1451 Com 2075 fix
  src/helpers/events.js
  src/repositories/EventRepository.js
  tests/integration/events.test.js
  tests/unit/repositories/EventRepository.test.js
Labels: dev

#1453 Com 2075 staging
  src/helpers/events.js
  src/repositories/EventRepository.js
  tests/integration/events.test.js
  tests/unit/repositories/EventRepository.test.js
Labels: staging

#1452 Com 2122 - userCompany
  src/routes/preHandlers/events.js
  tests/integration/seed/eventsSeed.js
Labels: dev

#1454 MEP intermediaire
  src/helpers/events.js
  src/repositories/EventRepository.js
  tests/integration/events.test.js
  tests/unit/repositories/EventRepository.test.js
Labels: dev

#1450 Com 2094
  src/helpers/customers.js
  src/helpers/dates.js
  src/helpers/events.js
  src/helpers/eventsRepetition.js
  tests/unit/helpers/customers.test.js
  tests/unit/helpers/dates.test.js
  tests/unit/helpers/events.test.js
Labels: dev

#1460 Com 2124 - UserCompany
  src/routes/preHandlers/stats.js
  tests/integration/seed/statsSeed.js
  tests/integration/stats.test.js
Labels: dev

#1456 Com 2139
  src/controllers/eventController.js
  src/helpers/customers.js
  src/helpers/events.js
  src/helpers/eventsValidation.js
  src/helpers/translate.js
  src/repositories/EventRepository.js
  tests/integration/events.test.js
  tests/integration/seed/eventsSeed.js
  tests/unit/helpers/customers.test.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/eventsValidation.test.js
Labels: dev

#1458 COM-2142 - Add teletransmissionId to model, creation and edition route
  src/models/ThirdPartyPayer.js
  src/routes/thirdPartyPayers.js
  tests/integration/thirdPartyPayers.test.js
Labels: dev

#1457 Com 2148
  package-lock.json
  package.json
  src/data/SourceSansPro-Bold.ttf
  src/data/SourceSansPro-Regular.ttf
  src/data/interAttendanceSheet.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/file.js
  src/helpers/pdf.js
  tests/unit/data/interAttendanceSheet.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/file.test.js
  tests/unit/helpers/pdf.test.js
Labels: dev

#1463 COM-2126 - UserCompany
  src/routes/preHandlers/pay.js
  tests/integration/seed/paySeed.js
Labels: dev

#1462 COM-2138
  src/controllers/eventController.js
  src/helpers/events.js
  src/helpers/eventsValidation.js
  src/helpers/translate.js
  src/routes/events.js
  src/routes/preHandlers/events.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/eventsValidation.test.js
Labels: dev

#1465 COM-2127: refacto UserCompany in pay preHandler
  src/routes/preHandlers/pay.js
  tests/integration/pay.test.js
Labels: dev

#1461 Com 2075 histories
  src/helpers/eventHistories.js
  src/repositories/EventHistoryRepository.js
  src/routes/eventHistories.js
  tests/integration/eventHistories.test.js
  tests/unit/helpers/eventHistories.test.js
Labels: dev

#1471 COM-2131: refacto prehandler authorizecontractcreation
  src/routes/preHandlers/contracts.js
  tests/integration/contracts.test.js
  tests/integration/seed/contractsSeed.js
Labels: dev

#1472 COM-2140: refacto deleterepetition
  src/controllers/eventController.js
  src/helpers/eventsRepetition.js
  src/routes/events.js
  src/routes/preHandlers/events.js
  tests/unit/helpers/eventsRepetition.test.js
Labels: dev

#1473 COM-2128 - use UserCompany in finalPay preHandler
  src/routes/preHandlers/finalPay.js
  tests/integration/finalPay.test.js
  tests/integration/seed/finalPaySeed.js
Labels: dev

#1476 COM-2147: refacto authorizeattendancecreation prehandler
  src/routes/preHandlers/attendances.js
  tests/integration/attendances.test.js
  tests/integration/seed/attendancesSeed.js
Labels: dev

#1475 COM-2075 - refacto get events groupBy
  src/helpers/dates.js
  src/helpers/utils.js
  src/repositories/EventRepository.js
  src/routes/preHandlers/events.js
  tests/integration/events.test.js
  tests/unit/helpers/dates.test.js
  tests/unit/helpers/utils.test.js
  tests/unit/repositories/EventRepositories.test.js
Labels: dev

#1477 Com 2094 clean
  src/helpers/customers.js
  src/helpers/dates.js
  src/helpers/events.js
  src/helpers/eventsRepetition.js
  tests/unit/helpers/customers.test.js
  tests/unit/helpers/dates.test.js
Labels: dev

#1479 COM-2179 - remove getStartOfDay and getEndOfDay
  src/helpers/dates.js
  src/helpers/events.js
  src/routes/preHandlers/events.js
  tests/unit/helpers/events.test.js
Labels: bug, dev

#1483 COM-2042 - Allow deletion of teletransmissionId
  src/models/ThirdPartyPayer.js
  src/routes/thirdPartyPayers.js
  tests/integration/seed/balanceSeed.js
  tests/integration/seed/billSlipsSeed.js
  tests/integration/seed/billsSeed.js
  tests/integration/seed/creditNotesSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/exportSeed.js
  tests/integration/seed/paymentsSeed.js
  tests/integration/seed/statsSeed.js
  tests/integration/seed/thirdPartyPayersSeed.js
  tests/integration/thirdPartyPayers.test.js
  tests/seed/thirdPartyPayerSeed.js
Labels: dev

#1485 Fix events
  src/helpers/dates.js
  src/helpers/utils.js
  tests/unit/helpers/dates.test.js
Labels: bug, dev

#1478 Com 2094 - script
  src/helpers/email.js
  src/helpers/emailOptions.js
  src/jobs/eventRepetitions.js
  tests/unit/jobs/eventRepetitions.test.js
Labels: dev

#1480 COM-2143: add teletransmissionId to create and edit funding
  src/helpers/fundings.js
  src/models/Customer.js
  src/routes/customers.js
  src/routes/preHandlers/customers.js
  tests/integration/customers.test.js
  tests/integration/seed/customersSeed.js
  tests/unit/helpers/fundings.test.js
Labels: dev

#1482 COM-2186: remove default on customerParticipationRate
  src/routes/validations/customer.js
Labels: dev

#1490 COM-2194 : npm update
  package-lock.json
  package.json
Labels: dependancies

#1492 COM-2196 fix access to interb2b course
  src/routes/preHandlers/courses.js
  tests/integration/seed/coursesSeed.js
Labels: bug, dev

#1493 MES COM-2196
  src/routes/preHandlers/courses.js
  tests/integration/seed/coursesSeed.js
Labels: staging

#1496 MEP intermediaire 24/06
  src/routes/preHandlers/courses.js
  tests/integration/seed/coursesSeed.js
Labels: master

#1501 COM-2192 - update colors
  src/data/courseConvocation.html
  src/data/pdf/attendanceSheet/interAttendanceSheet.js
  src/data/pdf/attendanceSheet/intraAttendanceSheet.js
  src/data/pdf/attendanceSheet/utils.js
  src/helpers/constants.js
  tests/unit/data/interAttendanceSheet.test.js
  tests/unit/data/intraAttendanceSheet.test.js
  tests/unit/helpers/file.test.js
Labels: staging

#1505 Staging
  src/data/courseConvocation.html
  src/data/pdf/attendanceSheet/interAttendanceSheet.js
  src/data/pdf/attendanceSheet/intraAttendanceSheet.js
  src/data/pdf/attendanceSheet/utils.js
  src/helpers/constants.js
  tests/unit/data/interAttendanceSheet.test.js
  tests/unit/data/intraAttendanceSheet.test.js
  tests/unit/helpers/file.test.js
Labels: master

#1497 COM-2153 - Use pdfMake for TaxCertificate pdf
  src/data/pdf/taxCertificates/taxCertificates.js
  src/data/taxCertificates.html
  src/helpers/taxCertificates.js
  tests/unit/data/taxCertificates.test.js
  tests/unit/helpers/taxCertificates.test.js
Labels: dev

#1498 Com 2151
  src/data/bill.html
  src/data/pdf/billing/bill.js
  src/data/pdf/billing/utils.js
  src/helpers/bills.js
  tests/unit/data/bill.test.js
  tests/unit/helpers/bills.test.js
Labels: dev

#1506 COM-2135 - Refacto userCompany in activityHistories helper
  src/helpers/activityHistories.js
  tests/unit/helpers/activityHistories.test.js
Labels: dev

#1507 COM-2176: create route
  src/controllers/customerNoteController.js
  src/helpers/customerNotes.js
  src/helpers/translate.js
  src/routes/customerNotes.js
  src/routes/preHandlers/customerNotes.js
  tests/integration/customerNotes.test.js
  tests/unit/helpers/customerNotes.test.js
Labels: dev

#1504 Com 2173
  package-lock.json
  package.json
  src/controllers/customerController.js
  src/data/pdf/customerQRCode/customerQRCode.js
  src/helpers/customers.js
  src/helpers/translate.js
  src/routes/customers.js
  tests/integration/customers.test.js
  tests/unit/data/customerQRCode.test.js
  tests/unit/helpers/customers.test.js
Labels: dev
