Repository CompaniTech/compani-api, pull requests merged in 2021-10, with the labels that each got.

#1631 [ne pas fusionner] COM-2344: update node js
  .github/workflows/lint.yml
  .github/workflows/node.js.yml
  package-lock.json
  package.json
  src/helpers/dates.js
Labels: dependancies

#1634 COM-2357 docxtemplater new syntaxe
  package-lock.json
  package.json
  src/helpers/docx.js
  tests/unit/helpers/docx.test.js
Labels: dependancies

#1637 COM-2372 add remote step type
  src/helpers/constants.js
  src/models/Step.js
  tests/integration/activities.test.js
  tests/integration/programs.test.js
  tests/integration/seed/activitiesSeed.js
  tests/integration/seed/programsSeed.js
Labels: dev

#1638 COM-2385: don't return allSettled status if no phone numbers
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1635 COM-2309-user-2 next part
  tests/integration/users.test.js
Labels: dev

#1654 Com 2414
  src/helpers/bills.js
  tests/unit/helpers/bills.test.js
Labels: bug, dev

#1668 Mep intermediaire 13/10
  src/helpers/events.js
  src/helpers/eventsRepetition.js
  src/helpers/translate.js
  tests/integration/events.test.js
  tests/integration/exports.test.js
  tests/integration/seed/eventsSeed.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/eventsRepetition.test.js
Labels: bug, master

#1661 Com 2410
  src/helpers/customers.js
  src/repositories/CustomerRepository.js
  src/repositories/utils.js
  tests/integration/contracts.test.js
  tests/unit/helpers/customers.test.js
Labels: dev

#1676 MES 18/10
  src/models/Customer.js
  src/routes/preHandlers/customers.js
  tests/integration/customers.test.js
  tests/integration/seed/customersSeed.js
Labels: staging
