Repository CompaniTech/compani-api, pull requests merged in 2021-09, with the labels that each got.

#1576 Com 2315
  src/controllers/Google/driveController.js
  src/helpers/drive.js
  src/models/Google/Drive.js
  src/routes/Google/drive.js
  tests/integration/drive.test.js
  tests/unit/helpers/drive.test.js
Labels: dev

#1577 Com 2296
  src/controllers/billingItemController.js
  src/helpers/billingItems.js
  src/helpers/constants.js
  src/helpers/translate.js
  src/models/BillingItem.js
  src/routes/billingItems.js
  src/routes/index.js
  src/routes/preHandlers/billingItems.js
  tests/integration/administrativeDocument.test.js
  tests/integration/billingItems.test.js
  tests/integration/helpers/authentication.js
  tests/integration/seed/billingItemsSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/billingItems.test.js
Labels: dev

#1581 fix seed for e2e tests
  tests/end2end/seed/billingSeed.js
Labels: dev

#1575 Com 2294
  src/helpers/constants.js
  src/helpers/historyExport.js
  src/models/Event.js
  src/routes/events.js
  tests/integration/exports.test.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1579 COM-2304: populate historiesCount
  src/helpers/questionnaires.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev

#1580 Com 2301
  src/controllers/courseController.js
  src/helpers/courses.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1583 COM-2307: valid link request
  src/controllers/companyLinkRequestController.js
  src/data/rights.js
  src/helpers/companyLinkRequests.js
  src/helpers/translate.js
  src/helpers/userCompanies.js
  src/helpers/users.js
  src/routes/companyLinkRequests.js
  tests/integration/companyLinkRequests.test.js
  tests/integration/seed/companyLinkRequestsSeed.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/companyLinkRequests.test.js
  tests/unit/helpers/userCompanies.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1585 COM-2327 - allow action in event history payload
  src/helpers/eventHistories.js
  src/models/EventHistory.js
  src/routes/eventHistories.js
  tests/integration/eventHistories.test.js
  tests/unit/helpers/eventHistories.test.js
Labels: bug, dev

#1584 COM-2302: populate trainer
  src/helpers/questionnaires.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev

#1582 Com 2298
  src/controllers/billingItemController.js
  src/controllers/billsController.js
  src/helpers/billingItems.js
  src/helpers/bills.js
  src/helpers/constants.js
  src/helpers/translate.js
  src/models/Bill.js
  src/models/CreditNote.js
  src/models/Event.js
  src/models/schemaDefinitions/billEventSurcharges.js
  src/models/schemaDefinitions/billing.js
  src/models/validations/utils.js
  src/routes/billingItems.js
  src/routes/bills.js
  src/routes/preHandlers/bills.js
  tests/end2end/seed/billingSeed.js
  tests/integration/billingItems.test.js
  tests/integration/bills.test.js
  tests/integration/seed/balanceSeed.js
  tests/integration/seed/billSlipsSeed.js
  tests/integration/seed/billingItemsSeed.js
  tests/integration/seed/billsSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/scriptsSeed.js
  tests/unit/helpers/bills.test.js
Labels: dev

#1589 COM-2341 - fix amount bill
  src/helpers/bills.js
  tests/unit/helpers/bills.test.js
Labels: bug, dev

#1586 Com 2308
  src/controllers/companyLinkRequestController.js
  src/helpers/companyLinkRequests.js
  src/helpers/translate.js
  src/routes/companyLinkRequests.js
  src/routes/preHandlers/companyLinkRequests.js
  tests/integration/companyLinkRequests.test.js
  tests/integration/seed/companyLinkRequestsSeed.js
  tests/unit/helpers/companyLinkRequests.test.js
Labels: dev

#1587 COM-2294 - handle repetitions
  src/helpers/events.js
  src/routes/events.js
  src/routes/preHandlers/events.js
  tests/integration/events.test.js
  tests/unit/helpers/events.test.js
Labels: dev

#1588 Com 2319 staging
  src/controllers/Google/driveController.js
  src/helpers/drive.js
  src/models/Google/Drive.js
  src/routes/Google/drive.js
  tests/integration/drive.test.js
  tests/unit/helpers/drive.test.js
Labels: staging

#1593 Staging
  src/controllers/Google/driveController.js
  src/helpers/drive.js
  src/models/Google/Drive.js
  src/routes/Google/drive.js
  tests/integration/drive.test.js
  tests/unit/helpers/drive.test.js
Labels: master

#1592 Com 2342
  src/helpers/customers.js
  src/models/Customer.js
  src/repositories/EventRepository.js
  tests/integration/customers.test.js
  tests/integration/seed/customersSeed.js
  tests/unit/helpers/customers.test.js
Labels: bug, dev

#1596 Com 2298 billing article
  src/helpers/bills.js
  src/models/schemaDefinitions/billing.js
  src/routes/preHandlers/bills.js
  tests/unit/helpers/bills.test.js
Labels: dev

#1591 Com 2297
  src/helpers/services.js
  src/models/Service.js
  src/routes/preHandlers/services.js
  src/routes/services.js
  tests/integration/seed/servicesSeed.js
  tests/integration/services.test.js
  tests/unit/helpers/services.test.js
Labels: dev

#1595 COM-2295: chose specific transport mode
  src/helpers/constants.js
  src/helpers/distanceMatrix.js
  src/helpers/draftPay.js
  tests/unit/helpers/distanceMatrix.test.js
  tests/unit/helpers/draftPay.test.js
Labels: dev

#1602 COM-2295: fix if specific transport is private car
  src/helpers/distanceMatrix.js
  src/helpers/draftPay.js
  tests/unit/helpers/distanceMatrix.test.js
  tests/unit/helpers/draftPay.test.js
Labels: dev

#1601 COM-2350 - Fix access rule bug for Melodie
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
Labels: dev

#1603 MES 14/09
  src/helpers/constants.js
  src/helpers/distanceMatrix.js
  src/helpers/draftPay.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/distanceMatrix.test.js
  tests/unit/helpers/draftPay.test.js
Labels: staging

#1604 COM-2348 npm update
  package-lock.json
  package.json
Labels: dependancies

#1606 COM-2353 - Fix billnumber for manual bills
  src/helpers/bills.js
  tests/unit/helpers/bills.test.js
Labels: bug

#1607 MES 15/09
  package-lock.json
  package.json
  src/helpers/bills.js
  tests/unit/helpers/bills.test.js
Labels: staging

#1609 Com 2328
  src/helpers/draftBills.js
  src/helpers/historyExport.js
  tests/unit/helpers/draftbills.test.js
Labels: dev

#1614 Com 2329
  src/helpers/bills.js
  src/helpers/draftBills.js
  src/models/Event.js
  src/models/schemaDefinitions/billing.js
  src/routes/bills.js
  src/routes/preHandlers/bills.js
  tests/integration/bills.test.js
  tests/integration/seed/billsSeed.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/draftbills.test.js
Labels: dev

#1617 Com 2310
  src/routes/preHandlers/creditNotes.js
  tests/integration/courseSlots.test.js
  tests/integration/creditNotes.test.js
  tests/integration/customerNotes.test.js
  tests/integration/customerPartners.test.js
Labels: dev

#1620 COM-2329 - Fix missing discount field in bill billingItemList
  src/helpers/bills.js
  src/models/schemaDefinitions/billing.js
  tests/unit/helpers/bills.test.js
Labels: dev

#1619 COM-2330 - Add TPP to bill pdf
  src/helpers/bills.js
  tests/unit/helpers/bills.test.js
Labels: dev

#1618 COM-2362 dont save coursesmshitory if no sms sent
  src/helpers/constants.js
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: bug, dev

#1621 COM-2324: fix bug when create media card
  src/models/Card.js
Labels: dev

#1625 COM-2354: can't have two versions with same date
  src/routes/preHandlers/services.js
  tests/integration/services.test.js
Labels: dev

#1624 Com 2345
  .eslintrc.js
  src/helpers/bills.js
  src/helpers/courses.js
  src/helpers/creditNotes.js
  src/models/CreditNote.js
  src/models/Event.js
  src/models/schemaDefinitions/billing.js
  src/routes/bills.js
  src/routes/creditNotes.js
  src/routes/preHandlers/creditNotes.js
  src/routes/validations/creditNote.js
  tests/integration/creditNotes.test.js
  tests/integration/seed/creditNotesSeed.js
  tests/unit/helpers/123Paie/absences.test.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/creditNotes.test.js
Labels: dev

#1626 MES 28/09
  .eslintrc.js
  package.json
  src/data/pdf/attendanceSheet/interAttendanceSheet.js
  src/data/pdf/attendanceSheet/intraAttendanceSheet.js
  src/data/pdf/attendanceSheet/utils.js
  src/data/pdf/billing/bill.js
  src/helpers/bills.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/creditNotes.js
  src/helpers/draftBills.js
  src/helpers/historyExport.js
  src/helpers/numbers.js
  src/helpers/questionnaires.js
  src/helpers/utils.js
  src/models/Bill.js
  src/models/Card.js
  src/models/CreditNote.js
  src/models/Event.js
  src/models/schemaDefinitions/billing.js
  src/routes/bills.js
  src/routes/creditNotes.js
  src/routes/preHandlers/bills.js
  src/routes/preHandlers/creditNotes.js
  src/routes/preHandlers/establishments.js
  src/routes/preHandlers/eventHistories.js
  src/routes/preHandlers/events.js
  src/routes/preHandlers/services.js
  src/routes/validations/creditNote.js
  tests/integration/bills.test.js
  tests/integration/courseSlots.test.js
  tests/integration/creditNotes.test.js
  tests/integration/customerNotes.test.js
  tests/integration/customerPartners.test.js
  tests/integration/establishments.test.js
  tests/integration/eventHistories.test.js
  tests/integration/events.test.js
  tests/integration/exports.test.js
  tests/integration/finalPay.test.js
  tests/integration/helpers.test.js
  tests/integration/seed/billsSeed.js
  tests/integration/seed/creditNotesSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/finalPaySeed.js
  tests/integration/seed/questionnairesSeed.js
  tests/integration/services.test.js
  tests/seed/authCompaniesSeed.js
  tests/unit/data/bill.test.js
  tests/unit/data/interAttendanceSheet.test.js
  tests/unit/data/intraAttendanceSheet.test.js
  tests/unit/helpers/123Paie/absences.test.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/creditNotes.test.js
  tests/unit/helpers/draftbills.test.js
  tests/unit/helpers/numbers.test.js
  tests/unit/helpers/questionnaires.test.js
  tests/unit/helpers/utils.test.js
Labels: staging

#1628 MEP 29/09
  .eslintrc.js
  package.json
  src/data/pdf/attendanceSheet/interAttendanceSheet.js
  src/data/pdf/attendanceSheet/intraAttendanceSheet.js
  src/data/pdf/attendanceSheet/utils.js
  src/data/pdf/billing/bill.js
  src/helpers/bills.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/creditNotes.js
  src/helpers/draftBills.js
  src/helpers/historyExport.js
  src/helpers/numbers.js
  src/helpers/questionnaires.js
  src/helpers/utils.js
  src/models/Bill.js
  src/models/Card.js
  src/models/CreditNote.js
  src/models/Event.js
  src/models/schemaDefinitions/billing.js
  src/routes/bills.js
  src/routes/creditNotes.js
  src/routes/preHandlers/bills.js
  src/routes/preHandlers/creditNotes.js
  src/routes/preHandlers/establishments.js
  src/routes/preHandlers/eventHistories.js
  src/routes/preHandlers/events.js
  src/routes/preHandlers/services.js
  src/routes/validations/creditNote.js
  tests/integration/bills.test.js
  tests/integration/courseSlots.test.js
  tests/integration/creditNotes.test.js
  tests/integration/customerNotes.test.js
  tests/integration/customerPartners.test.js
  tests/integration/establishments.test.js
  tests/integration/eventHistories.test.js
  tests/integration/events.test.js
  tests/integration/exports.test.js
  tests/integration/finalPay.test.js
  tests/integration/helpers.test.js
  tests/integration/seed/billsSeed.js
  tests/integration/seed/creditNotesSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/finalPaySeed.js
  tests/integration/seed/questionnairesSeed.js
  tests/integration/services.test.js
  tests/seed/authCompaniesSeed.js
  tests/unit/data/bill.test.js
  tests/unit/data/interAttendanceSheet.test.js
  tests/unit/data/intraAttendanceSheet.test.js
  tests/unit/helpers/123Paie/absences.test.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/creditNotes.test.js
  tests/unit/helpers/draftbills.test.js
  tests/unit/helpers/numbers.test.js
  tests/unit/helpers/questionnaires.test.js
  tests/unit/helpers/utils.test.js
Labels: master

#1632 COM-2399 - allow empty date
  src/routes/validations/customer.js
  tests/integration/customers.test.js
Labels: bug, dev
