Repository CompaniTech/compani-api, pull requests merged in 2021-11, with the labels that each got.

#1694 COM-2429 - Fix deletion
  src/helpers/contracts.js
  src/helpers/eventsValidation.js
  tests/unit/helpers/contracts.test.js
  tests/unit/helpers/eventsValidation.test.js
Labels: bug, dev

#1695 COM-2467 - do not call methods if no event
  src/helpers/delivery.js
  src/repositories/EventRepository.js
  tests/unit/helpers/delivery.test.js
Labels: bug, dev

#1697 Suite MES- 02/11
  src/helpers/delivery.js
  src/repositories/EventRepository.js
  tests/unit/helpers/delivery.test.js
Labels: staging

#1698 COM-2488 update
  package-lock.json
  package.json
Labels: dependancies

#1703 COM-2504 - clean user model
  src/models/User.js
  src/routes/users.js
Labels: dev

#1706 COM-2470 - Add virtual for mobile
  src/helpers/events.js
Labels: dev

#1707 COM-2474 - Prevent event creation and update if customer is absent
  src/helpers/customerAbsences.js
  src/helpers/eventsValidation.js
  src/helpers/translate.js
  tests/unit/customerAbsences.test.js
  tests/unit/helpers/eventsValidation.test.js
Labels: dev

#1708 COM-2480: block slot addition and edition
  src/routes/preHandlers/courseSlot.js
  tests/integration/courseSlots.test.js
  tests/integration/seed/courseSlotsSeed.js
Labels: dev

#1709 COM-2481: block trainee addition and deletion in an archived course
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
Labels: dev

#1710 COM-2486: refacto progress
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1711 COM-2484: add integration test
  tests/integration/courses.test.js
Labels: dev

#1716 Fix pdfmake test
  package-lock.json
  tests/unit/helpers/pdf.test.js
Labels: dev

#1718 COM-2493 - Delete and update customer absences after customer stop
  src/helpers/customerAbsences.js
  src/helpers/customers.js
  tests/integration/customers.test.js
  tests/integration/seed/customersSeed.js
  tests/unit/helpers/customerAbsences.test.js
  tests/unit/helpers/customers.test.js
Labels: dev

#1721 MES 22-11
  package-lock.json
  package.json
  src/controllers/customerAbsenceController.js
  src/controllers/eventController.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/customerAbsences.js
  src/helpers/customers.js
  src/helpers/delivery.js
  src/helpers/events.js
  src/helpers/eventsValidation.js
  src/helpers/translate.js
  src/models/Course.js
  src/models/CustomerAbsence.js
  src/models/ThirdPartyPayer.js
  src/models/User.js
  src/routes/attendanceSheets.js
  src/routes/courses.js
  src/routes/customerAbsences.js
  src/routes/events.js
  src/routes/index.js
  src/routes/preHandlers/attendanceSheets.js
  src/routes/preHandlers/attendances.js
  src/routes/preHandlers/courseSlot.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/customerAbsences.js
  src/routes/preHandlers/events.js
  src/routes/preHandlers/teletransmission.js
  src/routes/teletransmission.js
  src/routes/users.js
  tests/integration/attendanceSheets.test.js
  tests/integration/attendances.test.js
  tests/integration/courseSlots.test.js
  tests/integration/courses.test.js
  tests/integration/customerAbsences.test.js
  tests/integration/customers.test.js
  tests/integration/events.test.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/integration/seed/attendancesSeed.js
  tests/integration/seed/courseSlotsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/customerAbsencesSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/teletransmissionSeed.js
  tests/integration/teletransmission.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/customerAbsences.test.js
  tests/unit/helpers/customers.test.js
  tests/unit/helpers/delivery.test.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/eventsValidation.test.js
  tests/unit/helpers/pdf.test.js
Labels: staging

#1722 COM-2473 remove events before creating absence
  src/helpers/events.js
  tests/integration/events.test.js
Labels: bug, dev

#1724 MEP 23/11/2021
  package-lock.json
  package.json
  src/controllers/customerAbsenceController.js
  src/controllers/eventController.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/customerAbsences.js
  src/helpers/customers.js
  src/helpers/delivery.js
  src/helpers/events.js
  src/helpers/eventsRepetition.js
  src/helpers/eventsValidation.js
  src/helpers/translate.js
  src/jobs/eventRepetitions.js
  src/models/Course.js
  src/models/CustomerAbsence.js
  src/models/ThirdPartyPayer.js
  src/models/User.js
  src/routes/attendanceSheets.js
  src/routes/courses.js
  src/routes/customerAbsences.js
  src/routes/events.js
  src/routes/index.js
  src/routes/preHandlers/attendanceSheets.js
  src/routes/preHandlers/attendances.js
  src/routes/preHandlers/courseSlot.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/customerAbsences.js
  src/routes/preHandlers/events.js
  src/routes/preHandlers/teletransmission.js
  src/routes/teletransmission.js
  src/routes/users.js
  tests/integration/attendanceSheets.test.js
  tests/integration/attendances.test.js
  tests/integration/courseSlots.test.js
  tests/integration/courses.test.js
  tests/integration/customerAbsences.test.js
  tests/integration/customers.test.js
  tests/integration/events.test.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/integration/seed/attendancesSeed.js
  tests/integration/seed/courseSlotsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/customerAbsencesSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/teletransmissionSeed.js
  tests/integration/teletransmission.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/customerAbsences.test.js
  tests/unit/helpers/customers.test.js
  tests/unit/helpers/delivery.test.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/eventsRepetition.test.js
  tests/unit/helpers/eventsValidation.test.js
  tests/unit/helpers/pdf.test.js
  tests/unit/jobs/eventRepetitions.test.js
Labels: master

#1725 COM-2533 - npm update
  .eslintrc.js
  package-lock.json
  package.json
  src/helpers/historyExport.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/cards.test.js
  tests/unit/helpers/contracts.test.js
  tests/unit/helpers/creditNotes.test.js
  tests/unit/helpers/customers.test.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/quotes.test.js
  tests/unit/helpers/sectorHistories.test.js
  tests/unit/helpers/subPrograms.test.js
Labels: dependancies

#1727 COM-2514: replace moment with luxon in coursehistories
  package-lock.json
  package.json
  src/helpers/companiDates.js
  src/helpers/courseHistories.js
  tests/unit/helpers/companiDates.test.js
Labels: dev
