Repository CompaniTech/compani-api, pull requests merged in 2021-04, with the labels that each got.

#1352 Add test:withTag to package.json
  package.json
Labels: dev

#1350 COM-1974: create new routes for questionnaires
  src/controllers/questionnaireController.js
  src/data/rights.js
  src/helpers/constants.js
  src/helpers/questionnaires.js
  src/helpers/translate.js
  src/models/Questionnaire.js
  src/routes/index.js
  src/routes/questionnaires.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/questionnairesSeed.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev

#1351 Com 1979
  src/models/Course.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/integration/seed/attendancesSeed.js
  tests/integration/seed/courseHistoriesSeed.js
  tests/integration/seed/courseSlotsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/programsSeed.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/seed/usersSeed.js
  tests/seed/userSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1355 proposition to change pr checklist
  .github/pull_request_template.md
Labels: dev

#1353 COM-1974: can't create a questionnaire if already one in draft
  src/helpers/translate.js
  src/routes/preHandlers/questionnaires.js
  src/routes/questionnaires.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/questionnairesSeed.js
Labels: dev

#1354 Com 1977
  src/controllers/activityController.js
  src/controllers/activityHistoryController.js
  src/controllers/administrativeDocumentController.js
  src/controllers/attendanceController.js
  src/controllers/attendanceSheetController.js
  src/controllers/balanceController.js
  src/controllers/billSlipController.js
  src/controllers/billsController.js
  src/controllers/categoryController.js
  src/controllers/courseHistoryController.js
  src/controllers/courseSlotController.js
  src/controllers/emailController.js
  src/controllers/eventHistoryController.js
  src/controllers/exportController.js
  src/controllers/finalPayController.js
  src/controllers/internalHourController.js
  src/controllers/partnerOrganizationController.js
  src/controllers/paymentController.js
  src/controllers/sectorController.js
  src/controllers/serviceController.js
  src/controllers/surchargeController.js
  src/controllers/taxCertificateController.js
  src/controllers/thirdPartyPayerController.js
  src/controllers/versionController.js
  src/data/rights.js
  src/helpers/partnerOrganizations.js
  src/helpers/translate.js
  src/models/PartnerOrganization.js
  src/routes/index.js
  src/routes/partnerOrganizations.js
  src/routes/preHandlers/partnerOrganizations.js
  src/routes/preHandlers/subPrograms.js
  tests/integration/partnerOrganizations.test.js
  tests/integration/seed/partnerOrganizationsSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/partnerOrganizations.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1357 Com 1980
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
Labels: dev

#1359 Com 1987
  tests/unit/helpers/events.test.js
  tests/unit/helpers/eventsRepetition.test.js
  tests/unit/helpers/eventsValidation.test.js
  tests/unit/helpers/subscriptions.test.js
Labels: dev

#1356 Com 1975
  src/controllers/questionnaireController.js
  src/helpers/questionnaires.js
  src/helpers/translate.js
  src/routes/preHandlers/questionnaires.js
  src/routes/questionnaires.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/questionnairesSeed.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev

#1360 COM-1980-fix - Add salesRepresentative identity to course
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1361 Com 1977 list
  src/controllers/partnerOrganizationController.js
  src/data/rights.js
  src/helpers/partnerOrganizations.js
  src/helpers/translate.js
  src/routes/partnerOrganizations.js
  src/routes/payments.js
  tests/integration/partnerOrganizations.test.js
  tests/integration/seed/partnerOrganizationsSeed.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/partnerOrganizations.test.js
Labels: dev

#1362 Change check version
  src/helpers/constants.js
  src/helpers/version.js
  src/routes/version.js
  tests/integration/version.test.js
  tests/unit/helpers/version.test.js
Labels: dev

#1363 COM-1981 - populate for salesRepresentative
  src/repositories/CourseRepository.js
Labels: dev

#1364 Com 1988 2
  src/controllers/activityController.js
  src/controllers/cardController.js
  src/controllers/questionnaireController.js
  src/helpers/activities.js
  src/helpers/cards.js
  src/helpers/questionnaires.js
  src/models/Questionnaire.js
  src/routes/activities.js
  src/routes/cards.js
  src/routes/preHandlers/activities.js
  src/routes/preHandlers/cards.js
  src/routes/preHandlers/questionnaires.js
  src/routes/questionnaires.js
  tests/integration/activities.test.js
  tests/integration/cards.test.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/activitiesSeed.js
  tests/integration/seed/cardsSeed.js
  tests/integration/seed/questionnairesSeed.js
  tests/unit/helpers/activities.test.js
  tests/unit/helpers/cards.test.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev

#1365 COM-2007 fix creation of sectorHistory on second contract or on updat…
  src/helpers/dates.js
  src/helpers/sectorHistories.js
  tests/integration/seed/usersSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/dates.test.js
  tests/unit/helpers/sectorHistories.test.js
Labels: dev

#1366 Com 1978
  src/controllers/partnerOrganizationController.js
  src/helpers/partnerOrganizations.js
  src/helpers/translate.js
  src/routes/partnerOrganizations.js
  src/routes/preHandlers/partnerOrganizations.js
  tests/integration/partnerOrganizations.test.js
  tests/integration/seed/partnerOrganizationsSeed.js
  tests/unit/helpers/partnerOrganizations.test.js
Labels: dev

#1367 Com 1976
  src/helpers/translate.js
  src/routes/preHandlers/questionnaires.js
  src/routes/questionnaires.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/questionnairesSeed.js
Labels: dev

#1370 Com 1997 - npm update
  .github/workflows/lint.yml
  .github/workflows/node.js.yml
  package-lock.json
  package.json
Labels: dev

#1371 COM-2030 - refacto event validation
  src/helpers/contracts.js
  src/helpers/dates.js
  src/helpers/eventsValidation.js
  tests/integration/events.test.js
  tests/unit/helpers/dates.test.js
  tests/unit/helpers/eventsValidation.test.js
Labels: dev

#1373 Com 2001
  src/helpers/constants.js
  src/helpers/translate.js
  src/models/Questionnaire.js
  src/routes/preHandlers/questionnaires.js
  tests/integration/questionnaires.test.js
Labels: dev

#1372 Com 1995
  src/controllers/questionnaireController.js
  src/helpers/questionnaires.js
  src/routes/preHandlers/questionnaires.js
  src/routes/questionnaires.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/questionnairesSeed.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev

#1374 Com 2004
  .github/pull_request_template.md
  src/controllers/partnerOrganizationController.js
  src/helpers/constants.js
  src/helpers/partnerOrganizations.js
  src/helpers/translate.js
  src/models/Partner.js
  src/models/PartnerOrganization.js
  src/routes/partnerOrganizations.js
  src/routes/preHandlers/partnerOrganizations.js
  tests/integration/partnerOrganizations.test.js
  tests/integration/seed/partnerOrganizationsSeed.js
  tests/unit/helpers/partnerOrganizations.test.js
Labels: dev

#1376 COM-2027: change title in name
  src/helpers/questionnaires.js
  src/models/Questionnaire.js
  src/routes/preHandlers/questionnaires.js
  src/routes/questionnaires.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/cardsSeed.js
  tests/integration/seed/questionnairesSeed.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev

#1375 Com 2014
  src/controllers/questionnaireController.js
  src/controllers/questionnaireHistoryController.js
  src/helpers/questionnaireHistories.js
  src/helpers/questionnaires.js
  src/helpers/translate.js
  src/models/Questionnaire.js
  src/models/QuestionnaireHistory.js
  src/routes/index.js
  src/routes/preHandlers/activityHistories.js
  src/routes/preHandlers/questionnaireHistories.js
  src/routes/preHandlers/utils.js
  src/routes/questionnaireHistories.js
  tests/integration/questionnaireHistories.test.js
  tests/integration/seed/questionnaireHistoriesSeed.js
  tests/unit/helpers/questionnaireHistories.test.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev

#1379 MES intermédiaire
  src/controllers/questionnaireController.js
  src/controllers/questionnaireHistoryController.js
  src/helpers/constants.js
  src/helpers/questionnaireHistories.js
  src/helpers/questionnaires.js
  src/helpers/translate.js
  src/models/Questionnaire.js
  src/models/QuestionnaireHistory.js
  src/routes/index.js
  src/routes/preHandlers/activityHistories.js
  src/routes/preHandlers/questionnaireHistories.js
  src/routes/preHandlers/questionnaires.js
  src/routes/preHandlers/utils.js
  src/routes/questionnaireHistories.js
  src/routes/questionnaires.js
  tests/integration/questionnaireHistories.test.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/cardsSeed.js
  tests/integration/seed/questionnaireHistoriesSeed.js
  tests/integration/seed/questionnairesSeed.js
  tests/unit/helpers/questionnaireHistories.test.js
  tests/unit/helpers/questionnaires.test.js
Labels: staging

#1377 Com 1960
  src/controllers/contractController.js
  src/controllers/payController.js
  src/helpers/123paie/absences.js
  src/helpers/123paie/contracts.js
  src/helpers/123paie/identification.js
  src/helpers/123paie/pay.js
  src/helpers/dpae.js
  src/helpers/historyExport.js
  src/helpers/utils.js
  src/models/schemaDefinitions/pay.js
  src/routes/pay.js
  tests/integration/pay.test.js
  tests/integration/seed/paySeed.js
  tests/unit/helpers/123Paie/absences.test.js
  tests/unit/helpers/123Paie/contracts.test.js
  tests/unit/helpers/123Paie/identification.test.js
  tests/unit/helpers/123Paie/pay.test.js
  tests/unit/helpers/dpae.test.js
Labels: dev

#1381 COM-2004: firstname is optional
  src/models/Partner.js
  src/routes/partnerOrganizations.js
  tests/integration/partnerOrganizations.test.js
Labels: dev

#1378 Com 1993
  src/controllers/helperController.js
  src/data/rights.js
  src/helpers/authorization.js
  src/helpers/dataExport.js
  src/helpers/helpers.js
  src/helpers/translate.js
  src/helpers/users.js
  src/models/Customer.js
  src/models/Helper.js
  src/models/User.js
  src/routes/helpers.js
  src/routes/index.js
  src/routes/preHandlers/balances.js
  src/routes/preHandlers/customers.js
  src/routes/preHandlers/helpers.js
  src/routes/preHandlers/users.js
  src/routes/users.js
  tests/integration/balances.test.js
  tests/integration/customers.test.js
  tests/integration/exports.test.js
  tests/integration/helpers.test.js
  tests/integration/seed/balanceSeed.js
  tests/integration/seed/billsSeed.js
  tests/integration/seed/creditNotesSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/exportSeed.js
  tests/integration/seed/helpersSeed.js
  tests/integration/seed/taxCertificatesSeed.js
  tests/integration/users.test.js
  tests/seed/userSeed.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/dataExport.test.js
  tests/unit/helpers/helpers.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1380 Com 2005
  src/controllers/customerPartnerController.js
  src/controllers/partnerController.js
  src/data/rights.js
  src/helpers/customerPartners.js
  src/helpers/partners.js
  src/helpers/translate.js
  src/models/CustomerPartner.js
  src/routes/customerPartners.js
  src/routes/index.js
  src/routes/partners.js
  src/routes/preHandlers/customerPartners.js
  tests/integration/customerPartners.test.js
  tests/integration/partners.test.js
  tests/integration/seed/customerPartnersSeed.js
  tests/integration/seed/partnersSeed.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/customerPartners.test.js
  tests/unit/helpers/partners.test.js
Labels: dev

#1384 MEP
  .github/pull_request_template.md
  .github/workflows/lint.yml
  .github/workflows/node.js.yml
  package-lock.json
  package.json
  src/controllers/contractController.js
  src/controllers/partnerOrganizationController.js
  src/controllers/payController.js
  src/controllers/questionnaireController.js
  src/controllers/questionnaireHistoryController.js
  src/helpers/123paie/absences.js
  src/helpers/123paie/contracts.js
  src/helpers/123paie/identification.js
  src/helpers/123paie/pay.js
  src/helpers/constants.js
  src/helpers/contracts.js
  src/helpers/dates.js
  src/helpers/dpae.js
  src/helpers/eventsValidation.js
  src/helpers/historyExport.js
  src/helpers/partnerOrganizations.js
  src/helpers/questionnaireHistories.js
  src/helpers/questionnaires.js
  src/helpers/translate.js
  src/helpers/utils.js
  src/models/Partner.js
  src/models/PartnerOrganization.js
  src/models/Questionnaire.js
  src/models/QuestionnaireHistory.js
  src/models/schemaDefinitions/pay.js
  src/routes/index.js
  src/routes/partnerOrganizations.js
  src/routes/pay.js
  src/routes/preHandlers/activityHistories.js
  src/routes/preHandlers/partnerOrganizations.js
  src/routes/preHandlers/questionnaireHistories.js
  src/routes/preHandlers/questionnaires.js
  src/routes/preHandlers/utils.js
  src/routes/questionnaireHistories.js
  src/routes/questionnaires.js
  tests/integration/events.test.js
  tests/integration/partnerOrganizations.test.js
  tests/integration/pay.test.js
  tests/integration/questionnaireHistories.test.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/cardsSeed.js
  tests/integration/seed/partnerOrganizationsSeed.js
  tests/integration/seed/paySeed.js
  tests/integration/seed/questionnaireHistoriesSeed.js
  tests/integration/seed/questionnairesSeed.js
  tests/unit/helpers/123Paie/absences.test.js
  tests/unit/helpers/123Paie/contracts.test.js
  tests/unit/helpers/123Paie/identification.test.js
  tests/unit/helpers/123Paie/pay.test.js
  tests/unit/helpers/dates.test.js
  tests/unit/helpers/dpae.test.js
  tests/unit/helpers/eventsValidation.test.js
  tests/unit/helpers/partnerOrganizations.test.js
  tests/unit/helpers/questionnaireHistories.test.js
  tests/unit/helpers/questionnaires.test.js
Labels: master

#1385 Com 1999
  src/controllers/establishmentController.js
  src/helpers/dataExport.js
  src/helpers/establishments.js
  src/routes/establishments.js
  src/routes/preHandlers/establishments.js
  tests/unit/helpers/dataExport.test.js
  tests/unit/helpers/establishments.test.js
Labels: dev

#1386 COM-2053: npm update
  package-lock.json
  package.json
Labels: dev

#1387 Com 2035
  src/controllers/courseController.js
  src/data/rights.js
  src/helpers/courses.js
  src/helpers/translate.js
  src/models/Questionnaire.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  src/routes/questionnaires.js
  tests/integration/courses.test.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/courses.test.js
Labels: dev
