Repository CompaniTech/compani-api, pull requests merged in 2021-05, with the labels that each got.

#1388 COM-2037: return end of course questionnaire
  src/controllers/questionnaireController.js
  src/helpers/questionnaires.js
  src/routes/preHandlers/questionnaires.js
  src/routes/questionnaires.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev

#1389 Com 2034
  src/helpers/users.js
  src/models/User.js
  src/routes/preHandlers/users.js
  src/routes/users.js
  src/routes/validations/utils.js
  tests/integration/seed/usersSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1395 COM-2057 - Remove pentecote, pentecote's monday and mother's day from…
  src/extensions/moment.js
Labels: dev

#1391 Com 2036
  src/controllers/questionnaireController.js
  src/helpers/courses.js
  src/helpers/questionnaires.js
  src/routes/preHandlers/questionnaires.js
  src/routes/questionnaires.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/questionnairesSeed.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev

#1393 Com 2040
  src/controllers/helperController.js
  src/data/rights.js
  src/helpers/helpers.js
  src/helpers/translate.js
  src/models/Helper.js
  src/routes/helpers.js
  tests/integration/helpers.test.js
  tests/integration/seed/balanceSeed.js
  tests/integration/seed/billsSeed.js
  tests/integration/seed/creditNotesSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/exportSeed.js
  tests/integration/seed/helpersSeed.js
  tests/integration/seed/taxCertificatesSeed.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/helpers.test.js
Labels: dev

#1394 COM-2041: allow title edition
  src/routes/preHandlers/activities.js
  src/routes/preHandlers/steps.js
  tests/integration/activities.test.js
  tests/integration/steps.test.js
Labels: dev

#1398 COM-2039: minor bug
  src/helpers/questionnaires.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev

#1400 COM-2037: display questionnaire when last slot is started
  src/helpers/questionnaires.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev

#1401 Com 2050
  tests/unit/helpers/distanceMatrix.test.js
  tests/unit/helpers/mandates.test.js
  tests/unit/helpers/taxCertificates.test.js
  tests/unit/helpers/thirdPartyPayers.test.js
  tests/unit/jobs/billDispatch.test.js
Labels: dev

#1402 COM-2051: change last tests and remove sinon-mongoose
  package-lock.json
  package.json
  tests/unit/helpers/pay.test.js
  tests/unit/helpers/subPrograms.test.js
  tests/unit/helpers/subscriptions.test.js
Labels: dev

#1397 COM-2012: remove media on GCS
  src/helpers/activities.js
  src/helpers/questionnaires.js
  tests/integration/activities.test.js
  tests/integration/questionnaires.test.js
  tests/unit/helpers/activities.test.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev

#1399 Com 2034
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/notifications.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/notifications.test.js
Labels: dev

#1405 COM-2077 - npm update
  package-lock.json
  package.json
Labels: dev

#1407 Com 2069
  src/controllers/customerPartnerController.js
  src/helpers/customerPartners.js
  src/helpers/translate.js
  src/models/CustomerPartner.js
  src/routes/customerPartners.js
  src/routes/preHandlers/customerPartners.js
  tests/integration/customerPartners.test.js
  tests/integration/seed/customerPartnersSeed.js
  tests/unit/helpers/customerPartners.test.js
Labels: dev

#1408 COM-2065: remove status
  src/helpers/dataExport.js
  tests/integration/exports.test.js
  tests/unit/helpers/dataExport.test.js
Labels: dev

#1411 COM-2081 fix bills for customer with 0 participationrate
  src/helpers/draftBills.js
  tests/unit/helpers/draftbills.test.js
Labels: dev

#1412 COM-2070: remove customer partner
  src/controllers/customerPartnerController.js
  src/helpers/customerPartners.js
  src/helpers/translate.js
  src/routes/customerPartners.js
  src/routes/preHandlers/customerPartners.js
  tests/integration/customerPartners.test.js
  tests/unit/helpers/customerPartners.test.js
Labels: dev

#1409 Com 2078 - MEP Intermédiaire
  src/controllers/userController.js
  src/helpers/notifications.js
  src/helpers/users.js
  src/routes/preHandlers/users.js
  src/routes/users.js
  tests/integration/users.test.js
  tests/seed/userSeed.js
  tests/unit/helpers/notifications.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1410 Com 2079
  src/helpers/eventHistories.js
  src/helpers/events.js
  src/helpers/utils.js
  src/models/EventHistory.js
  tests/integration/eventHistories.test.js
  tests/integration/seed/eventHistoriesSeed.js
  tests/unit/helpers/eventHistories.test.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/utils.test.js
Labels: dev

#1418 MEP intermediaire
  src/controllers/userController.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/notifications.js
  src/helpers/users.js
  src/routes/preHandlers/users.js
  src/routes/users.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/integration/users.test.js
  tests/seed/userSeed.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/notifications.test.js
  tests/unit/helpers/users.test.js
Labels: master

#1414 COM-2066 - Refacto customer deletion
  src/controllers/customerController.js
  src/helpers/customers.js
  src/models/Customer.js
  src/routes/customers.js
  src/routes/preHandlers/customers.js
  tests/integration/customers.test.js
  tests/unit/helpers/customers.test.js
Labels: dev

#1419 COM-2072: send email in course helper when add trainee
  src/controllers/courseController.js
  src/helpers/courses.js
  src/helpers/email.js
  src/helpers/translate.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/email.test.js
Labels: dev

#1413 COM-2067: add status in customer
  src/helpers/constants.js
  src/models/BillNumber.js
  src/models/Company.js
  src/models/Customer.js
  src/models/CustomerPartner.js
Labels: dev

#1420 Com 2073
  src/controllers/eventController.js
  src/data/rights.js
  src/helpers/constants.js
  src/helpers/dates.js
  src/helpers/eventHistories.js
  src/helpers/eventTimeStamping.js
  src/helpers/eventsValidation.js
  src/helpers/translate.js
  src/models/EventHistory.js
  src/routes/events.js
  src/routes/preHandlers/events.js
  tests/integration/customerPartners.test.js
  tests/integration/events.test.js
  tests/integration/helpers.test.js
  tests/integration/partners.test.js
  tests/integration/seed/eventsSeed.js
  tests/unit/data/rights.test.js
  tests/unit/helpers/eventHistories.test.js
  tests/unit/helpers/eventTimeStamping.test.js
Labels: dev

#1417 Com 2101
  src/helpers/users.js
  src/jobs/billDispatch.js
  src/models/Customer.js
  src/models/preHooks/validate.js
  src/repositories/BillRepository.js
  src/routes/preHandlers/activityHistories.js
  src/routes/preHandlers/contracts.js
  src/routes/preHandlers/customers.js
  src/routes/preHandlers/pay.js
  src/routes/preHandlers/payDocuments.js
  src/routes/preHandlers/programs.js
  src/routes/preHandlers/stats.js
  src/routes/preHandlers/users.js
  tests/integration/contracts.test.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: bug, dev

#1422 Com 2068
  src/controllers/partnerController.js
  src/data/rights.js
  src/helpers/partners.js
  src/helpers/translate.js
  src/models/Partner.js
  src/routes/partners.js
  src/routes/preHandlers/partners.js
  tests/integration/partners.test.js
  tests/integration/seed/partnersSeed.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/partners.test.js
Labels: dev

#1426 COM-2104 - replace googleapis by @googleapis/drive
  package-lock.json
  package.json
  src/models/Google/Drive.js
Labels: dev

#1427 add validation for type and groupby on route get
  src/routes/events.js
  tests/integration/events.test.js
Labels: dev

#1429 COM-2107: npm update
  package-lock.json
  package.json
Labels: dev

#1432 COM-2093: add status to put route
  src/helpers/constants.js
  src/helpers/customers.js
  src/models/Customer.js
  src/routes/customers.js
  src/routes/preHandlers/customers.js
  tests/integration/customers.test.js
  tests/integration/seed/customersSeed.js
Labels: dev

#1435 Com 2100
  src/helpers/users.js
  src/routes/preHandlers/users.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev
