Repository CompaniTech/compani-api, pull requests merged in 2021-03, with the labels that each got.

#1310 MEP
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/controllers/Google/driveController.js
  src/controllers/taxCertificateController.js
  src/helpers/administrativeDocument.js
  src/helpers/companies.js
  src/helpers/contracts.js
  src/helpers/customers.js
  src/helpers/drive.js
  src/helpers/gDriveStorage.js
  src/helpers/mandates.js
  src/helpers/payDocuments.js
  src/helpers/payments.js
  src/helpers/sectors.js
  src/helpers/taxCertificates.js
  src/helpers/translate.js
  src/helpers/users.js
  src/helpers/xml.js
  src/jobs/eventRepetitions.js
  src/models/Google/Drive.js
  src/repositories/CompanyRepository.js
  src/repositories/EventRepository.js
  src/routes/preHandlers/attendances.js
  src/routes/preHandlers/courseSlot.js
  src/routes/preHandlers/sectors.js
  src/routes/preHandlers/users.js
  src/routes/scripts.js
  src/routes/sectors.js
  src/routes/users.js
  tests/integration/attendances.test.js
  tests/integration/authentication.test.js
  tests/integration/companies.test.js
  tests/integration/courseSlots.test.js
  tests/integration/drive.test.js
  tests/integration/payDocuments.test.js
  tests/integration/sectors.test.js
  tests/integration/seed/attendancesSeed.js
  tests/integration/seed/courseSlotsSeed.js
  tests/integration/seed/sectorsSeed.js
  tests/integration/taxCertificates.test.js
  tests/integration/users.test.js
  tests/unit/helpers/administrativeDocument.test.js
  tests/unit/helpers/companies.test.js
  tests/unit/helpers/contracts.test.js
  tests/unit/helpers/creditNotes.test.js
  tests/unit/helpers/customers.test.js
  tests/unit/helpers/drive.test.js
  tests/unit/helpers/gdriveStorage.test.js
  tests/unit/helpers/mandates.test.js
  tests/unit/helpers/payDocuments.test.js
  tests/unit/helpers/payments.test.js
  tests/unit/helpers/quotes.test.js
  tests/unit/helpers/sectorHistories.test.js
  tests/unit/helpers/sectors.test.js
  tests/unit/helpers/taxCertificates.test.js
  tests/unit/helpers/users.test.js
  tests/unit/helpers/xml.test.js
  tests/unit/jobs/eventRepetitions.test.js
Labels: master

#1311 API - npm update
  package-lock.json
  package.json
Labels: dev

#1312 Com 1923
  src/helpers/constants.js
  src/helpers/draftPay.js
  src/helpers/surcharges.js
  src/models/Surcharge.js
  src/models/schemaDefinitions/pay.js
  src/routes/surcharges.js
  src/routes/validations/pay.js
  tests/integration/seed/surchargesSeed.js
  tests/integration/surcharges.test.js
  tests/unit/data/bills.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/historyExport.test.js
  tests/unit/helpers/surcharges.test.js
Labels: dev

#1313 COM-1944 - Fix bug where user with trainer and client_admin role could‘nt access course histories
  src/routes/preHandlers/courseHistories.js
  src/routes/preHandlers/courses.js
  tests/integration/courseHistories.test.js
  tests/integration/courses.test.js
  tests/integration/seed/courseHistoriesSeed.js
  tests/integration/seed/coursesSeed.js
Labels: dev

#1315 COM-1924: add cash as a payment method
  src/helpers/constants.js
  src/models/Payment.js
Labels: dev

#1314 COM-1910 - Prevent step deletion if step is linked to courseSlot
  src/helpers/programs.js
  src/models/Step.js
  src/routes/preHandlers/subPrograms.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/subPrograms.test.js
  tests/unit/helpers/programs.test.js
Labels: dev

#1316 Com 1947
  src/helpers/draftPay.js
  tests/unit/helpers/draftPay.test.js
Labels: dev

#1317 COM-1894: populate firstmobileconnection
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1319 Com 1940
  src/helpers/draftBills.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/draftbills.test.js
Labels: dev

#1318 COM-1949 - fix update contract startdate
  src/controllers/contractController.js
  src/helpers/contracts.js
  src/helpers/subPrograms.js
  tests/integration/contracts.test.js
  tests/integration/exports.test.js
  tests/integration/seed/authenticationSeed.js
  tests/integration/seed/contractsSeed.js
  tests/unit/helpers/contracts.test.js
Labels: bug, dev

#1320 COM-1950 - trainer can add non registered trainees
  src/data/rights.js
  src/routes/preHandlers/users.js
  src/routes/users.js
  tests/integration/users.test.js
Labels: bug, dev

#1322 Com 1851 live coding
  src/controllers/attendanceController.js
  src/routes/attendances.js
  src/routes/preHandlers/attendances.js
Labels: dev

#1323 COM-1949 - cannot create version before previous version startDate
  src/controllers/contractController.js
  src/helpers/contracts.js
  src/helpers/gDriveStorage.js
  tests/integration/contracts.test.js
  tests/integration/seed/contractsSeed.js
  tests/unit/helpers/contracts.test.js
Labels: bug, dev

#1324 MES
  package-lock.json
  package.json
  src/controllers/attendanceController.js
  src/controllers/authenticationController.js
  src/controllers/contractController.js
  src/data/rights.js
  src/helpers/constants.js
  src/helpers/contracts.js
  src/helpers/courses.js
  src/helpers/draftBills.js
  src/helpers/draftPay.js
  src/helpers/gDriveStorage.js
  src/helpers/programs.js
  src/helpers/subPrograms.js
  src/helpers/surcharges.js
  src/helpers/translate.js
  src/models/Payment.js
  src/models/Step.js
  src/models/Surcharge.js
  src/models/schemaDefinitions/pay.js
  src/routes/attendances.js
  src/routes/preHandlers/attendances.js
  src/routes/preHandlers/courseHistories.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/subPrograms.js
  src/routes/preHandlers/users.js
  src/routes/surcharges.js
  src/routes/users.js
  src/routes/validations/pay.js
  tests/integration/contracts.test.js
  tests/integration/courseHistories.test.js
  tests/integration/courses.test.js
  tests/integration/exports.test.js
  tests/integration/seed/authenticationSeed.js
  tests/integration/seed/contractsSeed.js
  tests/integration/seed/courseHistoriesSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/seed/surchargesSeed.js
  tests/integration/subPrograms.test.js
  tests/integration/surcharges.test.js
  tests/integration/users.test.js
  tests/unit/data/bills.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/contracts.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/draftbills.test.js
  tests/unit/helpers/historyExport.test.js
  tests/unit/helpers/programs.test.js
  tests/unit/helpers/surcharges.test.js
Labels: staging

#1325 MEP 1603
  package-lock.json
  package.json
  src/controllers/attendanceController.js
  src/controllers/authenticationController.js
  src/controllers/contractController.js
  src/data/rights.js
  src/helpers/constants.js
  src/helpers/contracts.js
  src/helpers/courses.js
  src/helpers/draftBills.js
  src/helpers/draftPay.js
  src/helpers/gDriveStorage.js
  src/helpers/programs.js
  src/helpers/subPrograms.js
  src/helpers/surcharges.js
  src/helpers/translate.js
  src/models/Payment.js
  src/models/Step.js
  src/models/Surcharge.js
  src/models/schemaDefinitions/pay.js
  src/routes/attendances.js
  src/routes/preHandlers/attendances.js
  src/routes/preHandlers/courseHistories.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/subPrograms.js
  src/routes/preHandlers/users.js
  src/routes/surcharges.js
  src/routes/users.js
  src/routes/validations/pay.js
  tests/integration/contracts.test.js
  tests/integration/courseHistories.test.js
  tests/integration/courses.test.js
  tests/integration/exports.test.js
  tests/integration/seed/authenticationSeed.js
  tests/integration/seed/contractsSeed.js
  tests/integration/seed/courseHistoriesSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/seed/surchargesSeed.js
  tests/integration/subPrograms.test.js
  tests/integration/surcharges.test.js
  tests/integration/users.test.js
  tests/unit/data/bills.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/contracts.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/draftbills.test.js
  tests/unit/helpers/historyExport.test.js
  tests/unit/helpers/programs.test.js
  tests/unit/helpers/surcharges.test.js
Labels: master

#1326 COM-1967 - npm update
  package-lock.json
  package.json
Labels: dev

#1328 Com 1952
  src/helpers/balances.js
  tests/unit/helpers/balances.test.js
Labels: dev

#1331 COM-1946: send billed and credit note event
  src/controllers/eventController.js
  src/helpers/events.js
  src/routes/events.js
  src/routes/preHandlers/events.js
  tests/integration/events.test.js
  tests/unit/helpers/events.test.js
Labels: dev

#1327 COM-1925 - Allow client_admin and coach to access attendanceSheets
  src/data/rights.js
  src/routes/attendances.js
  src/routes/preHandlers/attendances.js
  tests/integration/attendanceSheets.test.js
  tests/integration/attendances.test.js
  tests/integration/seed/attendancesSeed.js
  tests/unit/helpers/authorization.test.js
Labels: dev

#1336 COM-1957: allow user to access draft elearning programs which for he/she is tester
  src/controllers/subProgramController.js
  src/helpers/subPrograms.js
  src/routes/preHandlers/subPrograms.js
  src/routes/subPrograms.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/subPrograms.test.js
  tests/unit/helpers/subPrograms.test.js
Labels: dev

#1337 COM-1957: access to subprogram when user is a tester
  src/routes/preHandlers/subPrograms.js
  src/routes/subPrograms.js
  tests/integration/subPrograms.test.js
Labels: dev

#1338 MES
  src/controllers/programController.js
  src/controllers/subProgramController.js
  src/helpers/programs.js
  src/helpers/subPrograms.js
  src/helpers/translate.js
  src/models/Program.js
  src/routes/preHandlers/programs.js
  src/routes/preHandlers/subPrograms.js
  src/routes/programs.js
  src/routes/subPrograms.js
  tests/integration/programs.test.js
  tests/integration/seed/programsSeed.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/subPrograms.test.js
  tests/unit/helpers/programs.test.js
  tests/unit/helpers/subPrograms.test.js
Labels: staging

#1339 MEP intermediaire
  src/controllers/programController.js
  src/controllers/subProgramController.js
  src/helpers/programs.js
  src/helpers/subPrograms.js
  src/helpers/translate.js
  src/models/Program.js
  src/routes/preHandlers/programs.js
  src/routes/preHandlers/subPrograms.js
  src/routes/programs.js
  src/routes/subPrograms.js
  tests/integration/programs.test.js
  tests/integration/seed/programsSeed.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/subPrograms.test.js
  tests/unit/helpers/programs.test.js
  tests/unit/helpers/subPrograms.test.js
Labels: master

#1340 Com 1961
  src/helpers/administrativeDocument.js
  tests/unit/helpers/administrativeDocument.test.js
  tests/unit/helpers/customers.test.js
Labels: dev

#1343 COM-1951: remove questionnaire
  src/helpers/constants.js
  src/models/Activity.js
  tests/integration/seed/coursesSeed.js
Labels: dev

#1342 COM-1954 add route to remove refund
  src/controllers/paymentController.js
  src/helpers/payments.js
  src/helpers/translate.js
  src/routes/payments.js
  src/routes/preHandlers/payments.js
  tests/integration/payments.test.js
  tests/unit/helpers/payments.test.js
Labels: dev

#1341 Com 1926
  src/controllers/attendanceController.js
  src/controllers/attendanceSheetController.js
  src/helpers/attendanceSheets.js
  src/helpers/attendances.js
  src/routes/attendanceSheets.js
  src/routes/attendances.js
  src/routes/preHandlers/attendanceSheets.js
  src/routes/preHandlers/attendances.js
  tests/integration/attendanceSheets.test.js
  tests/integration/attendances.test.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/integration/seed/attendancesSeed.js
  tests/unit/helpers/attendanceSheets.test.js
  tests/unit/helpers/attendances.test.js
Labels: dev

#1346 COM-1961: remove return from create administrative document
  src/controllers/administrativeDocumentController.js
  src/helpers/administrativeDocument.js
  tests/unit/helpers/administrativeDocument.test.js
Labels: dev

#1348 COM-1983 - npm update
  package-lock.json
  package.json
Labels: dev

#1349 COM-1986: sinonmongoose
  tests/unit/helpers/fundings.test.js
  tests/unit/helpers/referentHistories.test.js
Labels: dev
