Repository CompaniTech/compani-api, pull requests merged in 2021-02, with the labels that each got.

#1276 update checklist
  .github/pull_request_template.md
Labels: dev

#1279 MEP
  package-lock.json
  package.json
  src/controllers/courseController.js
  src/helpers/activityHistories.js
  src/helpers/courses.js
  src/helpers/dpae.js
  src/helpers/events.js
  src/helpers/eventsRepetition.js
  src/helpers/repetitions.js
  src/helpers/users.js
  src/helpers/version.js
  src/models/User.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/users.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/integration/users.test.js
  tests/integration/version.test.js
  tests/unit/helpers/activityHistories.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courseSlots.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/dpae.test.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/eventsRepetition.test.js
  tests/unit/helpers/internalHours.test.js
  tests/unit/helpers/programs.test.js
  tests/unit/helpers/repetitions.test.js
  tests/unit/helpers/services.test.js
  tests/unit/helpers/stat.test.js
  tests/unit/helpers/steps.test.js
  tests/unit/helpers/subPrograms.test.js
  tests/unit/helpers/users.test.js
  tests/unit/helpers/version.test.js
Labels: master

#1278 COM-1872: npm update
  package-lock.json
  package.json
Labels: dev

#1280 COM-1846: add areAnswersCommutative to card model and add prehandler
  src/models/Card.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
Labels: dev

#1282 COM-1848: add isMandatory to card model and add prehandler
  src/models/Card.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
Labels: dev

#1281 COM-1851 populate picture for attendanceTable
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1283 COM-1850: add signature on attendance sheet
  src/data/interAttendanceSheet.html
  src/data/intraAttendanceSheet.html
Labels: dev

#1285 Com 1851 postget
  src/controllers/attendanceController.js
  src/data/rights.js
  src/helpers/attendances.js
  src/helpers/translate.js
  src/models/Attendance.js
  src/routes/attendances.js
  src/routes/index.js
  src/routes/preHandlers/attendances.js
  tests/integration/attendanceSheets.test.js
  tests/integration/attendances.test.js
  tests/integration/seed/attendancesSeed.js
  tests/unit/helpers/attendances.test.js
  tests/unit/helpers/authorization.test.js
Labels: dev

#1287 COM-1887 - Fix pupeteer exception error
  src/helpers/pdf.js
Labels: dev

#1288 Com 1851 remove attendance
  src/controllers/attendanceController.js
  src/helpers/attendances.js
  src/helpers/translate.js
  src/routes/attendances.js
  src/routes/preHandlers/attendances.js
  tests/integration/attendances.test.js
  tests/unit/helpers/attendances.test.js
Labels: dev

#1290 COM-1908 dont take step.subprogram for granted
  src/helpers/activityHistories.js
  src/routes/preHandlers/activityHistories.js
  tests/unit/helpers/activityHistories.test.js
Labels: dev

#1291 Dev
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/controllers/attendanceController.js
  src/data/interAttendanceSheet.html
  src/data/intraAttendanceSheet.html
  src/data/rights.js
  src/helpers/activityHistories.js
  src/helpers/attendances.js
  src/helpers/courses.js
  src/helpers/pdf.js
  src/helpers/translate.js
  src/models/Attendance.js
  src/models/Card.js
  src/routes/attendances.js
  src/routes/cards.js
  src/routes/index.js
  src/routes/preHandlers/activityHistories.js
  src/routes/preHandlers/attendances.js
  src/routes/preHandlers/cards.js
  tests/integration/attendanceSheets.test.js
  tests/integration/attendances.test.js
  tests/integration/cards.test.js
  tests/integration/seed/attendancesSeed.js
  tests/unit/helpers/activityHistories.test.js
  tests/unit/helpers/attendances.test.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/cards.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/surcharges.test.js
  tests/unit/helpers/users.test.js
Labels: staging

#1293 COM-1912 - npm update
  package-lock.json
  package.json
Labels: dev

#1294 COM-1895 - disable slot deletion if attendance exist
  src/helpers/translate.js
  src/routes/preHandlers/courseSlot.js
  tests/integration/courseSlots.test.js
  tests/integration/seed/courseSlotsSeed.js
Labels: dev

#1295 Update checklist in PR template
  .github/pull_request_template.md
Labels: dev

#1297 Com 1920
  src/routes/preHandlers/events.js
  tests/integration/events.test.js
Labels: dev

#1300 Com 1920 staging
  src/routes/preHandlers/events.js
  tests/integration/events.test.js
Labels: staging

#1301 MEP
  src/routes/preHandlers/events.js
  tests/integration/events.test.js
Labels: master

#1296 COM-1878 - Allow duplicate name for team of different structure
  src/helpers/sectors.js
  src/routes/preHandlers/sectors.js
  src/routes/sectors.js
  tests/integration/sectors.test.js
  tests/integration/seed/sectorsSeed.js
  tests/unit/helpers/sectors.test.js
Labels: dev

#1298 Com 1852
  src/helpers/users.js
  src/routes/preHandlers/attendances.js
  src/routes/preHandlers/users.js
  src/routes/users.js
  tests/integration/attendances.test.js
  tests/integration/seed/attendancesSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1299 COM-1879 - Fix gDrive call: always call from gDriveStorageHelper
  src/controllers/Google/driveController.js
  src/helpers/administrativeDocument.js
  src/helpers/companies.js
  src/helpers/contracts.js
  src/helpers/customers.js
  src/helpers/drive.js
  src/helpers/gDriveStorage.js
  src/helpers/mandates.js
  src/helpers/payDocuments.js
  src/helpers/taxCertificates.js
  src/helpers/users.js
  src/helpers/xml.js
  src/models/Google/Drive.js
  tests/integration/authentication.test.js
  tests/integration/companies.test.js
  tests/integration/drive.test.js
  tests/integration/payDocuments.test.js
  tests/integration/taxCertificates.test.js
  tests/integration/users.test.js
  tests/unit/helpers/administrativeDocument.test.js
  tests/unit/helpers/companies.test.js
  tests/unit/helpers/contracts.test.js
  tests/unit/helpers/customers.test.js
  tests/unit/helpers/drive.test.js
  tests/unit/helpers/gdriveStorage.test.js
  tests/unit/helpers/mandates.test.js
  tests/unit/helpers/payDocuments.test.js
  tests/unit/helpers/taxCertificates.test.js
  tests/unit/helpers/users.test.js
  tests/unit/helpers/xml.test.js
Labels: dev

#1303 Com 1884
  tests/unit/helpers/quotes.test.js
  tests/unit/helpers/sectorHistories.test.js
Labels: dev

#1305 Com 1883
  src/helpers/payments.js
  tests/unit/helpers/creditNotes.test.js
  tests/unit/helpers/payments.test.js
Labels: dev
