Repository CompaniTech/compani-api, pull requests merged in 2021-12, with the labels that each got.

#1735 Com 2563
  src/routes/events.js
  tests/integration/events.test.js
Labels: bug, dev

#1732 COM-2471 - Add isCancelled
  src/helpers/eventHistories.js
  src/routes/eventHistories.js
  src/routes/validations/utils.js
  tests/integration/eventHistories.test.js
  tests/integration/seed/eventHistoriesSeed.js
  tests/unit/helpers/eventHistories.test.js
Labels: dev

#1734 COM-2562 keep only positive break duration
  src/helpers/draftPay.js
  tests/unit/helpers/draftPay.test.js
Labels: dev

#1731 COM-2520: allow trainer to update and create learner
  src/data/rights.js
  src/routes/preHandlers/users.js
  src/routes/users.js
  tests/integration/users.test.js
Labels: dev

#1736 COM-2548 - Fix error throwing on funding conflict
  src/helpers/fundings.js
  src/helpers/translate.js
Labels: dev

#1737 COM-2284: remove password for users seeds
  tests/integration/seed/coursesSeed.js
Labels: dev

#1740 COM-2569: npm update
  package-lock.json
  package.json
  src/models/Google/Drive.js
Labels: dependancies

#1741 COM-2516: send notification for new elearning course
  src/controllers/programController.js
  src/helpers/constants.js
  src/helpers/notifications.js
  src/helpers/programs.js
  src/helpers/subPrograms.js
  src/routes/programs.js
  tests/integration/programs.test.js
  tests/unit/helpers/notifications.test.js
  tests/unit/helpers/programs.test.js
  tests/unit/helpers/subPrograms.test.js
Labels: dev

#1745 COM-2516: not size rather than where
  src/helpers/notifications.js
  tests/unit/helpers/notifications.test.js
Labels: dev

#1743 COM-2442: delete archived customer events is forbidden
  src/helpers/translate.js
  src/repositories/EventRepository.js
  src/routes/preHandlers/events.js
  tests/integration/events.test.js
  tests/integration/seed/eventsSeed.js
  tests/unit/helpers/eventsValidation.test.js
Labels: dev

#1750 MES pour MEP mobile
  package-lock.json
  package.json
  src/controllers/customerAbsenceController.js
  src/controllers/programController.js
  src/data/pdf/courseConvocation.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/customerAbsences.js
  src/helpers/notifications.js
  src/helpers/programs.js
  src/helpers/subPrograms.js
  src/helpers/surcharges.js
  src/helpers/translate.js
  src/models/Course.js
  src/models/Google/Drive.js
  src/models/Surcharge.js
  src/repositories/EventRepository.js
  src/routes/courses.js
  src/routes/customerAbsences.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/customerAbsences.js
  src/routes/preHandlers/events.js
  src/routes/programs.js
  tests/integration/courses.test.js
  tests/integration/customerAbsences.test.js
  tests/integration/events.test.js
  tests/integration/helpers/authentication.js
  tests/integration/programs.test.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/customerAbsencesSeed.js
  tests/integration/seed/eventsSeed.js
  tests/unit/data/courseConvocation.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/customerAbsences.test.js
  tests/unit/helpers/eventsValidation.test.js
  tests/unit/helpers/notifications.test.js
  tests/unit/helpers/programs.test.js
  tests/unit/helpers/subPrograms.test.js
  tests/unit/helpers/surcharges.test.js
Labels: staging

#1748 COM-2554 - prevent tpp billing for cancelledEvent
  src/helpers/draftBills.js
  src/repositories/EventRepository.js
  tests/unit/helpers/draftbills.test.js
Labels: dev

#1747 COM-2559: add issameorbefore luxon
  package.json
  src/helpers/dates/companiDates.js
  src/routes/preHandlers/courseSlot.js
  tests/unit/helpers/dates/companiDates.test.js
Labels: dev

#1758 COM-2285: refacto populateDB
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/finalPaySeed.js
  tests/integration/seed/helpersSeed.js
Labels: dev

#1760 COM-2286: refacto populateDB
  tests/integration/seed/internalHoursSeed.js
  tests/integration/seed/partnerOrganizationsSeed.js
  tests/integration/seed/partnersSeed.js
  tests/integration/seed/payDocumentsSeed.js
  tests/integration/seed/paySeed.js
  tests/integration/seed/paymentsSeed.js
  tests/integration/seed/programsSeed.js
Labels: dev

#1761 MES 20/12
  .github/pull_request_template.md
  package.json
  src/controllers/customerAbsenceController.js
  src/helpers/courses.js
  src/helpers/customerAbsences.js
  src/helpers/dates/companiDates.js
  src/helpers/dates/luxon.js
  src/helpers/draftBills.js
  src/helpers/events.js
  src/helpers/translate.js
  src/repositories/EventRepository.js
  src/routes/customerAbsences.js
  src/routes/preHandlers/courseSlot.js
  src/routes/preHandlers/customerAbsences.js
  src/routes/preHandlers/events.js
  tests/integration/customerAbsences.test.js
  tests/integration/events.test.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/finalPaySeed.js
  tests/integration/seed/helpersSeed.js
  tests/integration/seed/internalHoursSeed.js
  tests/integration/seed/partnerOrganizationsSeed.js
  tests/integration/seed/partnersSeed.js
  tests/integration/seed/payDocumentsSeed.js
  tests/integration/seed/paySeed.js
  tests/integration/seed/paymentsSeed.js
  tests/integration/seed/programsSeed.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/customerAbsences.test.js
  tests/unit/helpers/dates/companiDates.test.js
  tests/unit/helpers/dates/companiDuration.test.js
  tests/unit/helpers/draftbills.test.js
  tests/unit/helpers/events.test.js
Labels: staging

#1762 MES avec pipeline 20/12
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/controllers/customerAbsenceController.js
  src/controllers/programController.js
  src/data/pdf/courseConvocation.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/customerAbsences.js
  src/helpers/dates/companiDates.js
  src/helpers/dates/luxon.js
  src/helpers/draftBills.js
  src/helpers/events.js
  src/helpers/notifications.js
  src/helpers/programs.js
  src/helpers/subPrograms.js
  src/helpers/surcharges.js
  src/helpers/translate.js
  src/models/Course.js
  src/models/Google/Drive.js
  src/models/Surcharge.js
  src/repositories/EventRepository.js
  src/routes/courses.js
  src/routes/customerAbsences.js
  src/routes/preHandlers/courseSlot.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/customerAbsences.js
  src/routes/preHandlers/events.js
  src/routes/programs.js
  tests/integration/courses.test.js
  tests/integration/customerAbsences.test.js
  tests/integration/events.test.js
  tests/integration/helpers/authentication.js
  tests/integration/programs.test.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/customerAbsencesSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/finalPaySeed.js
  tests/integration/seed/helpersSeed.js
  tests/integration/seed/internalHoursSeed.js
  tests/integration/seed/partnerOrganizationsSeed.js
  tests/integration/seed/partnersSeed.js
  tests/integration/seed/payDocumentsSeed.js
  tests/integration/seed/paySeed.js
  tests/integration/seed/paymentsSeed.js
  tests/integration/seed/programsSeed.js
  tests/unit/data/courseConvocation.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/customerAbsences.test.js
  tests/unit/helpers/dates/companiDates.test.js
  tests/unit/helpers/dates/companiDuration.test.js
  tests/unit/helpers/draftbills.test.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/eventsValidation.test.js
  tests/unit/helpers/notifications.test.js
  tests/unit/helpers/programs.test.js
  tests/unit/helpers/subPrograms.test.js
  tests/unit/helpers/surcharges.test.js
Labels: master

#1764 COM-2578 new proposition for checklists
  .github/pull_request_template.md
Labels: dev
