Repository CompaniTech/compani-api, pull requests merged in 2021-01, with the labels that each got.

#1222 Com 1781 activities unit tests
  tests/unit/helpers/activities.test.js
Labels: dev

#1228 Staging
  src/helpers/version.js
  tests/unit/helpers/activities.test.js
  tests/unit/helpers/version.test.js
Labels: bug, master

#1221 COM-1713: don't send refreshToken after create account
  src/models/User.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1224 Com 1789
  package-lock.json
  package.json
  src/extensions/moment.js
  src/helpers/draftPay.js
  tests/integration/finalPay.test.js
  tests/integration/pay.test.js
  tests/integration/seed/finalPaySeed.js
  tests/integration/seed/paySeed.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/draftbills.test.js
  tests/unit/helpers/surcharges.test.js
  tests/unit/helpers/utils.test.js
Labels: dev

#1230 COM-1744 - add extension for absence
  src/models/Event.js
  src/routes/events.js
  src/routes/preHandlers/events.js
  tests/integration/events.test.js
  tests/integration/seed/eventsSeed.js
Labels: dev

#1232 Com 1741
  tests/unit/data/rights.test.js
Labels: dev

#1229 COM-1771: check update version
  src/controllers/versionController.js
  src/helpers/version.js
  src/routes/version.js
  tests/integration/version.test.js
  tests/unit/helpers/version.test.js
Labels: dev

#1231 Com 1751 upload attendanceSheets
  src/controllers/attendanceSheetController.js
  src/controllers/userController.js
  src/helpers/attendanceSheets.js
  src/helpers/gCloudStorage.js
  src/helpers/translate.js
  src/models/AttendanceSheet.js
  src/models/Course.js
  src/routes/attendanceSheets.js
  src/routes/index.js
  src/routes/preHandlers/attendanceSheets.js
  tests/integration/attendanceSheets.test.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/unit/helpers/attendanceSheets.test.js
Labels: dev

#1233 Com 1770
  src/helpers/constants.js
  src/helpers/email.js
  src/helpers/emailOptions.js
  src/routes/email.js
  src/routes/preHandlers/email.js
  tests/integration/email.test.js
  tests/unit/helpers/email.test.js
Labels: dev

#1238 Com 1771 staging
  src/controllers/versionController.js
  src/helpers/version.js
  src/routes/version.js
  tests/integration/version.test.js
  tests/unit/helpers/version.test.js
Labels: staging

#1235 Com 1751 new model
  src/helpers/attendanceSheets.js
  src/models/AttendanceSheet.js
  src/models/Course.js
  tests/integration/attendanceSheets.test.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/unit/helpers/attendanceSheets.test.js
Labels: dev

#1234 COM-1752 filter courses
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1241 COM-1804 fix memory leak when error from puppeteer
  src/helpers/pdf.js
  tests/unit/helpers/pdf.test.js
Labels: dev

#1239 Com 1759
  src/controllers/activityHistoryController.js
  src/helpers/activityHistories.js
  src/helpers/translate.js
  src/routes/activityHistories.js
  src/routes/preHandlers/activityHistories.js
  tests/integration/activityHistories.test.js
  tests/unit/helpers/activityHistories.test.js
Labels: dev

#1236 Com 1747
  src/helpers/pay.js
  src/helpers/sectorHistories.js
  src/repositories/SectorHistoryRepository.js
  tests/unit/helpers/pay.test.js
  tests/unit/helpers/sectorHistories.test.js
Labels: dev

#1243 COM-1744 - Add extension in absence export
  src/helpers/historyExport.js
  src/repositories/EventRepository.js
  tests/integration/exports.test.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1237 Com 1744 edition
  src/helpers/events.js
  src/repositories/EventRepository.js
  src/routes/preHandlers/events.js
Labels: dev

#1242 Com 1751 delete attendanceSheet
  src/controllers/attendanceSheetController.js
  src/data/rights.js
  src/helpers/attendanceSheets.js
  src/helpers/gCloudStorage.js
  src/helpers/translate.js
  src/routes/attendanceSheets.js
  src/routes/preHandlers/attendanceSheets.js
  tests/integration/attendanceSheets.test.js
  tests/unit/helpers/attendanceSheets.test.js
  tests/unit/helpers/authorization.test.js
Labels: dev

#1247 Com 1753
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1248 COM-1795 - Fix Apple Logo
  src/helpers/emailOptions.js
Labels: dev

#1252 Dev
  src/helpers/emailOptions.js
Labels: staging

#1250 COM-1828 - npm update
  package-lock.json
  package.json
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courseSlots.test.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/stat.test.js
  tests/unit/helpers/steps.test.js
Labels: dev

#1246 COM-1771: ⚠️ NE PAS MERGÉ TANT QUE L'APPLI N'A PAS ÉTÉ PUBLIÉE SUR LES STORES !!!!!
  src/helpers/users.js
  src/helpers/version.js
  tests/integration/users.test.js
  tests/integration/version.test.js
  tests/unit/helpers/users.test.js
  tests/unit/helpers/version.test.js
Labels: dev

#1258 Com 1833 staging
  src/helpers/draftFinalPay.js
  src/helpers/pay.js
  tests/unit/helpers/draftFinalPay.test.js
  tests/unit/helpers/pay.test.js
Labels: staging

#1259 Com 1799
  src/helpers/activityHistories.js
  tests/unit/helpers/activityHistories.test.js
Labels: dev

#1257 Com 1831
  src/helpers/events.js
  src/helpers/eventsRepetition.js
  src/helpers/repetitions.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/eventsRepetition.test.js
  tests/unit/helpers/repetitions.test.js
Labels: dev

#1245 COM-1745 - Add prolongation in 123Paie
  src/helpers/dpae.js
  tests/unit/helpers/dpae.test.js
Labels: dev

#1254 Com 1756
  src/helpers/users.js
  src/models/User.js
  tests/unit/helpers/users.test.js
Labels: dev

#1261 COM-1813: code verification if forgot password
  src/controllers/authenticationController.js
  src/helpers/authentication.js
  src/helpers/constants.js
  src/helpers/email.js
  src/helpers/emailOptions.js
  src/models/IdentityVerification.js
  src/routes/authentication.js
  tests/integration/authentication.test.js
  tests/unit/helpers/authentication.test.js
Labels: dev

#1256 COM-1806: return description and learningGoals
  src/helpers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1264 Com 1754
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
Labels: dev

#1262 COM-1817 populate activities
  src/helpers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1265 COM-1800 get user identity
  src/helpers/activityHistories.js
  tests/unit/helpers/activityHistories.test.js
Labels: dev

#1269 COM-1808: populate contact & trainer
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1267 Com 1813 2
  src/controllers/authenticationController.js
  src/helpers/authentication.js
  src/helpers/constants.js
  src/models/IdentityVerification.js
  src/routes/authentication.js
  tests/integration/authentication.test.js
  tests/integration/seed/authenticationSeed.js
  tests/unit/helpers/authentication.test.js
Labels: dev

#1268 Com 1754
  src/controllers/courseController.js
  src/helpers/courses.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1272 Com 1814
  src/helpers/authentication.js
  src/helpers/constants.js
  src/helpers/email.js
  src/helpers/sms.js
  tests/integration/authentication.test.js
  tests/integration/seed/usersSeed.js
  tests/unit/helpers/authentication.test.js
  tests/unit/helpers/sms.test.js
Labels: dev

#1270 Com 1818
  src/controllers/courseController.js
  src/helpers/courses.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1275 Com 1785 - sinon mongoose
  tests/unit/helpers/services.test.js
  tests/unit/helpers/subPrograms.test.js
Labels: dev

#1271 Com 1816
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/users.js
  tests/integration/courses.test.js
  tests/integration/users.test.js
Labels: dev
