Repository CompaniTech/compani-api, pull requests merged in 2022-07, with the labels that each got.

#1981 MES 04/07
  src/controllers/repetitionController.js
  src/helpers/courses.js
  src/helpers/delivery.js
  src/helpers/repetitions.js
  src/helpers/translate.js
  src/models/CourseSlot.js
  src/routes/index.js
  src/routes/preHandlers/courseBills.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/repetitions.js
  src/routes/repetitions.js
  tests/integration/courseBills.test.js
  tests/integration/courses.test.js
  tests/integration/helpers/initializeDB.js
  tests/integration/repetitions.test.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/repetitionsSeed.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/repetitions.test.js
Labels: staging

#1982 COM-2916: refacto prehandler + add companyRepresentative
  src/helpers/courses.js
  src/models/Course.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1973 Com 2888
  src/helpers/constants.js
  src/helpers/file.js
  src/helpers/pdf.js
  tests/end2end/seed/billingSeed.js
  tests/end2end/seed/planningSeed.js
  tests/unit/helpers/file.test.js
Labels: dev, tests

#1986 COM-2914: add exclTaxes on pdf for bill and credit note
  src/data/pdf/courseBilling/utils.js
  tests/unit/data/courseBill.test.js
  tests/unit/data/courseCreditNote.test.js
Labels: dev

#1984 Com 2913
  src/helpers/vendorHistoryExport.js
  tests/integration/exports.test.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: dev

#1988 COM-2914: respect figma
  src/data/pdf/courseBilling/utils.js
  tests/unit/data/courseBill.test.js
  tests/unit/data/courseCreditNote.test.js
Labels: dev

#1992 COM-2913: romain's review
  src/helpers/vendorHistoryExport.js
  tests/integration/exports.test.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: dev

#1990 Com 2915
  src/data/pdf/attendanceSheet/interAttendanceSheet.js
  src/data/pdf/attendanceSheet/intraAttendanceSheet.js
  src/data/pdf/attendanceSheet/utils.js
  src/data/pdf/completionCertificate.js
  src/data/pdf/courseBilling/utils.js
  tests/unit/data/completionCertificate.test.js
  tests/unit/data/courseBill.test.js
  tests/unit/data/courseCreditNote.test.js
  tests/unit/data/interAttendanceSheet.test.js
  tests/unit/data/intraAttendanceSheet.test.js
Labels: dev

#1991 COM-2918: update contact
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1996 COM-2915 less space on completion certificate
  src/data/pdf/completionCertificate.js
  tests/unit/data/completionCertificate.test.js
Labels: dev

#1997 Com 2954
  src/controllers/exportController.js
  src/helpers/constants.js
  src/helpers/vendorHistoryExport.js
  tests/integration/exports.test.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: dev

#2000 MES 25/07/2022
  src/controllers/exportController.js
  src/data/pdf/attendanceSheet/interAttendanceSheet.js
  src/data/pdf/attendanceSheet/intraAttendanceSheet.js
  src/data/pdf/attendanceSheet/utils.js
  src/data/pdf/completionCertificate.js
  src/data/pdf/courseBilling/utils.js
  src/helpers/bills.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/customers.js
  src/helpers/dates/companiDates.js
  src/helpers/file.js
  src/helpers/pdf.js
  src/helpers/repetitions.js
  src/helpers/translate.js
  src/helpers/vendorHistoryExport.js
  src/models/Course.js
  src/routes/bills.js
  src/routes/courses.js
  src/routes/customers.js
  src/routes/preHandlers/bills.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/repetitions.js
  src/routes/repetitions.js
  tests/end2end/seed/billingSeed.js
  tests/end2end/seed/planningSeed.js
  tests/integration/bills.test.js
  tests/integration/courses.test.js
  tests/integration/exports.test.js
  tests/integration/repetitions.test.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/repetitionsSeed.js
  tests/unit/data/completionCertificate.test.js
  tests/unit/data/courseBill.test.js
  tests/unit/data/courseCreditNote.test.js
  tests/unit/data/interAttendanceSheet.test.js
  tests/unit/data/intraAttendanceSheet.test.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/customers.test.js
  tests/unit/helpers/file.test.js
  tests/unit/helpers/repetitions.test.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: staging

#2001 Com 2893 intl
  src/helpers/utils.js
  tests/unit/helpers/utils.test.js
Labels: bug

#2002 MES 28/07 Feature big number bills
  src/controllers/balanceController.js
  src/data/pdf/billing/bill.js
  src/data/pdf/billing/creditNote.js
  src/data/pdf/billing/utils.js
  src/helpers/balances.js
  src/helpers/billSlips.js
  src/helpers/bills.js
  src/helpers/courseBills.js
  src/helpers/courses.js
  src/helpers/creditNotes.js
  src/helpers/draftBills.js
  src/helpers/historyExport.js
  src/helpers/numbers.js
  src/helpers/taxCertificates.js
  src/helpers/utils.js
  src/models/Bill.js
  src/models/CreditNote.js
  src/models/Event.js
  src/models/FundingHistory.js
  src/models/schemaDefinitions/billing.js
  src/repositories/BillRepository.js
  src/repositories/CreditNoteRepository.js
  src/repositories/EventRepository.js
  src/repositories/PaymentRepository.js
  src/routes/bills.js
  src/routes/validations/creditNote.js
  tests/integration/bills.test.js
  tests/integration/creditNotes.test.js
  tests/integration/seed/billsSeed.js
  tests/integration/seed/creditNotesSeed.js
  tests/integration/seed/repetitionsSeed.js
  tests/unit/data/bill.test.js
  tests/unit/data/bills.js
  tests/unit/helpers/balances.test.js
  tests/unit/helpers/billSlips.test.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/creditNotes.test.js
  tests/unit/helpers/draftbills.test.js
  tests/unit/helpers/historyExport.test.js
  tests/unit/helpers/numbers.test.js
  tests/unit/helpers/utils.test.js
Labels: dev
