Repository CompaniTech/compani-api, pull requests merged in 2022-05, with the labels that each got.

#1918 COM-2835 - block course deletion if billed
  src/helpers/courses.js
  src/helpers/translate.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
Labels: bug, dev

#1919 COM-2835 - fix tests
  tests/unit/helpers/courses.test.js
Labels: bug, dev

#1923 fix-typo-shell: minutes on 2 digits
  tests/unit/helpers/delivery.test.js
Labels: dev

#1922 MES 04/05/2022
  src/helpers/courses.js
  src/helpers/translate.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/delivery.test.js
Labels: staging

#1926 COM-2838 - case if event duration is 0
  src/helpers/draftBills.js
  tests/unit/helpers/draftbills.test.js
Labels: bug, dev

#1924 COM-2814: add new columns in course export
  src/helpers/courseBills.js
  src/helpers/historyExport.js
  src/repositories/CourseRepository.js
  tests/integration/exports.test.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1912 Com 2828
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: bug, dev

#1928 COM-2832 - format quantity in pdf
  src/helpers/bills.js
  src/helpers/utils.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/utils.test.js
Labels: dev

#1929 COM-2817: refacto slot creation
  src/controllers/courseSlotController.js
  src/helpers/courseSlots.js
  src/routes/courseSlots.js
  src/routes/preHandlers/courseSlot.js
  tests/integration/courseSlots.test.js
  tests/integration/seed/courseSlotsSeed.js
  tests/unit/helpers/courseSlots.test.js
Labels: dev

#1932 COM-2850 change table height
  src/data/pdf/attendanceSheet/intraAttendanceSheet.js
  tests/unit/data/intraAttendanceSheet.test.js
Labels: bug, dev

#1933 COM-2840 - add log on route
  server.js
  src/helpers/constants.js
Labels: dev

#1930 COM-2837: step is required
  src/helpers/courses.js
  src/routes/courseSlots.js
  src/routes/preHandlers/courseSlot.js
  tests/integration/courseSlots.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1934 COM-2819: delete user if no activity histories
  src/helpers/translate.js
  src/helpers/users.js
  src/routes/preHandlers/users.js
  tests/integration/seed/usersSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#1935 COM-2841 - update sector history after ending contract
  src/helpers/sectorHistories.js
  tests/unit/helpers/sectorHistories.test.js
Labels: bug, dev

#1936 COM-2854 - update command to launch server
  package.json
Labels: dev

#1939 MES - 16/05/2022
  package.json
  server.js
  src/controllers/courseSlotController.js
  src/controllers/userController.js
  src/data/pdf/attendanceSheet/intraAttendanceSheet.js
  src/helpers/bills.js
  src/helpers/constants.js
  src/helpers/courseBills.js
  src/helpers/courseHistories.js
  src/helpers/courseSlots.js
  src/helpers/courses.js
  src/helpers/draftBills.js
  src/helpers/historyExport.js
  src/helpers/sectorHistories.js
  src/helpers/translate.js
  src/helpers/users.js
  src/helpers/utils.js
  src/models/CourseHistory.js
  src/repositories/CourseRepository.js
  src/routes/courseSlots.js
  src/routes/courses.js
  src/routes/preHandlers/courseSlot.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/users.js
  src/routes/users.js
  tests/integration/courseSlots.test.js
  tests/integration/exports.test.js
  tests/integration/seed/courseSlotsSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/usersSeed.js
  tests/integration/users.test.js
  tests/unit/data/intraAttendanceSheet.test.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courseSlots.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/draftbills.test.js
  tests/unit/helpers/historyExport.test.js
  tests/unit/helpers/sectorHistories.test.js
  tests/unit/helpers/users.test.js
Labels: staging

#1942 Com 2862
  src/helpers/dates/companiDates.js
  src/helpers/historyExport.js
  tests/integration/exports.test.js
  tests/unit/helpers/dates/companiDates.test.js
  tests/unit/helpers/historyExport.test.js
Labels: bug, dev

#1941 COM-2853: refacto course bill model
  src/helpers/courseBills.js
  src/helpers/courseCreditNotes.js
  src/helpers/historyExport.js
  src/models/CourseBill.js
  src/models/CourseFundingOrganisation.js
  src/repositories/CourseRepository.js
  src/routes/courseBills.js
  src/routes/preHandlers/courseBills.js
  tests/integration/courseBills.test.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/courseCreditNotesSeed.js
  tests/integration/seed/courseFundingOrganisationsSeed.js
  tests/integration/seed/coursePaymentsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/courseBills.test.js
  tests/unit/helpers/courseCreditNotes.test.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1946 Com 2812
  src/helpers/courseBills.js
  tests/integration/courseBills.test.js
  tests/integration/seed/courseBillsSeed.js
  tests/unit/helpers/courseBills.test.js
Labels: dev

#1947 COM-2813: populate payer
  src/helpers/courseBills.js
  tests/unit/helpers/courseBills.test.js
Labels: dev

#1943 COM-2848: remove dates on slot
  src/controllers/courseSlotController.js
  src/helpers/courseSlots.js
  src/routes/courseSlots.js
  tests/integration/courseSlots.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courseSlots.test.js
Labels: dev

#1952 COM-2870 add CRE code for event with no timestamp even cancelled ones
  src/helpers/delivery.js
  tests/unit/helpers/delivery.test.js
Labels: dev

#1950 COM-2844: refacto address
  src/data/pdf/courseBilling/utils.js
  src/helpers/courseBills.js
  src/helpers/courseCreditNotes.js
  src/models/CourseFundingOrganisation.js
  src/routes/courseFundingOrganisations.js
  tests/integration/courseFundingOrganisations.test.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/courseFundingOrganisationsSeed.js
  tests/integration/seed/exportsSeed.js
  tests/unit/data/courseBill.test.js
  tests/unit/data/courseCreditNote.test.js
  tests/unit/helpers/courseBills.test.js
  tests/unit/helpers/courseCreditNotes.test.js
Labels: dev
