Repository CompaniTech/compani-api, pull requests merged in 2022-09, with the labels that each got.

#2013 COM-2988 - update PR template link
  .github/pull_request_template.md
Labels: dev

#2014 COM-2931: refacto colors
  src/helpers/constants.js
  tests/unit/data/courseConvocation.test.js
  tests/unit/data/interAttendanceSheet.test.js
  tests/unit/data/intraAttendanceSheet.test.js
Labels: dev

#2019 COM-2981: block trainees addition if max reached
  src/helpers/translate.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
Labels: dev

#2017 COM-2983: block activity in non-elearning steps
  src/helpers/steps.js
  src/routes/preHandlers/steps.js
  tests/integration/programs.test.js
  tests/integration/seed/activitiesSeed.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/programsSeed.js
  tests/integration/seed/stepsSeed.js
  tests/integration/steps.test.js
  tests/unit/helpers/steps.test.js
Labels: dev

#2020 COM-2982: can edit max trainees
  src/helpers/translate.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
Labels: dev

#2025 Com 2989
  src/controllers/courseController.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2027 Com 3015
  src/helpers/events.js
  src/helpers/eventsValidation.js
  tests/integration/seed/eventsSeed.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/eventsValidation.test.js
Labels: bug, dev

#2028 MES intermediaire 21/09
  src/helpers/events.js
  src/helpers/eventsValidation.js
  tests/integration/seed/eventsSeed.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/eventsValidation.test.js
Labels: master

#2031 COM-3015 dont check contract if assigning repetition to sector
  src/helpers/eventsValidation.js
  tests/unit/helpers/eventsValidation.test.js
Labels: bug, dev

#2032 Com 3002
  src/models/CourseSmsHistory.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
Labels: dev

#2035 Com 2977
  src/helpers/courses.js
  src/routes/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2038 Com 3008
  src/controllers/attendanceController.js
  src/helpers/attendances.js
  src/routes/attendances.js
  src/routes/preHandlers/attendances.js
  tests/integration/attendances.test.js
  tests/integration/seed/attendancesSeed.js
  tests/unit/helpers/attendances.test.js
Labels: dev

#2039 COM-2998: remove course/id/user route
  src/controllers/courseController.js
  src/helpers/courses.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2037 Com 2994
  src/controllers/courseController.js
  src/helpers/courses.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2042 COM-3021 - fix sum on bill
  src/helpers/bills.js
  tests/unit/helpers/bills.test.js
Labels: bug, dev

#2045 MES (mep mobile) 30/09
  src/controllers/attendanceController.js
  src/controllers/courseController.js
  src/helpers/attendances.js
  src/helpers/bills.js
  src/helpers/contracts.js
  src/helpers/courses.js
  src/helpers/eventsValidation.js
  src/models/CourseSmsHistory.js
  src/routes/attendances.js
  src/routes/courses.js
  src/routes/preHandlers/attendances.js
  src/routes/preHandlers/courses.js
  tests/integration/attendances.test.js
  tests/integration/courses.test.js
  tests/integration/seed/attendancesSeed.js
  tests/unit/helpers/attendances.test.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/contracts.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/eventsValidation.test.js
Labels: staging

#2043 Com 3022
  src/repositories/EventRepository.js
  tests/unit/repositories/EventRepositories.test.js
Labels: bug
