Repository CompaniTech/compani-api, pull requests merged in 2022-03, with the labels that each got.

#1836 Com 2710
  src/helpers/subscriptions.js
  src/models/schemaDefinitions/subscription.js
  src/routes/customers.js
  src/routes/preHandlers/customers.js
  tests/integration/customers.test.js
  tests/integration/seed/customersSeed.js
  tests/unit/helpers/subscriptions.test.js
Labels: dev

#1837 Com 2703
  src/helpers/courseBills.js
  src/helpers/historyExport.js
  src/models/CourseBill.js
  src/routes/courseBills.js
  tests/integration/courseBills.test.js
  tests/integration/exports.test.js
  tests/integration/seed/courseBillsSeed.js
  tests/unit/helpers/courseBills.test.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1838 COM-2710 - Add saturday to subscription history and data export
  src/helpers/dataExport.js
  src/routes/customers.js
  tests/end2end/seed/billingSeed.js
  tests/integration/customers.test.js
  tests/integration/exports.test.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/dataExport.test.js
Labels: dev

#1839 Com 2704
  src/controllers/courseBillController.js
  src/helpers/courseBills.js
  src/helpers/translate.js
  src/models/CourseBill.js
  src/routes/courseBills.js
  src/routes/preHandlers/courseBills.js
  tests/integration/courseBills.test.js
  tests/integration/seed/courseBillsSeed.js
  tests/unit/helpers/courseBills.test.js
Labels: dev

#1843 Com 2730
  src/helpers/courseBills.js
  src/helpers/historyExport.js
  src/models/CourseBill.js
  src/models/CourseBillsNumber.js
  src/routes/courseBills.js
  src/routes/preHandlers/courseBills.js
  src/routes/validations/utils.js
  tests/integration/courseBills.test.js
  tests/integration/exports.test.js
  tests/integration/helpers/authentication.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/courseBills.test.js
  tests/unit/helpers/historyExport.test.js
  tests/unit/helpers/utilsValidation.test.js
Labels: dev

#1847 COM-2738: refacto to change item in purchase
  src/controllers/courseBillController.js
  src/helpers/courseBills.js
  src/models/CourseBill.js
  src/routes/courseBills.js
  src/routes/preHandlers/courseBills.js
  tests/integration/courseBills.test.js
  tests/integration/seed/courseBillsSeed.js
  tests/unit/helpers/courseBills.test.js
Labels: dev

#1845 COM-2729 - Add teletransmissionType and companyCode to Tpp
  src/models/ThirdPartyPayer.js
  src/routes/thirdPartyPayers.js
  tests/integration/thirdPartyPayers.test.js
  tests/unit/helpers/utilsValidation.test.js
Labels: dev

#1846 COM-2734 - Add misc to credit note pdf
  src/data/pdf/billing/creditNote.js
  src/helpers/creditNotes.js
  tests/unit/data/creditNote.test.js
Labels: dev

#1850 Com 2732
  src/controllers/courseBillController.js
  src/data/pdf/courseBilling/courseBill.js
  src/helpers/constants.js
  src/helpers/courseBills.js
  src/routes/courseBills.js
  src/routes/preHandlers/courseBills.js
  tests/integration/courseBills.test.js
  tests/integration/seed/courseBillsSeed.js
  tests/unit/data/courseBill.test.js
  tests/unit/helpers/courseBills.test.js
Labels: dev

#1854 COM-2732: add margin
  src/data/pdf/courseBilling/courseBill.js
  tests/unit/data/courseBill.test.js
Labels: dev

#1852 COM-2725 - Authorize auxiliary to update helper
  src/data/rights.js
  src/routes/helpers.js
  src/routes/preHandlers/helpers.js
  tests/integration/helpers.test.js
Labels: dev

#1861 MES-18-03
  src/controllers/courseBillController.js
  src/data/pdf/billing/creditNote.js
  src/data/pdf/courseBilling/courseBill.js
  src/data/rights.js
  src/helpers/constants.js
  src/helpers/courseBills.js
  src/helpers/courses.js
  src/helpers/creditNotes.js
  src/helpers/dates/companiDates.js
  src/helpers/eventsRepetition.js
  src/helpers/historyExport.js
  src/helpers/programs.js
  src/helpers/repetitions.js
  src/helpers/stats.js
  src/helpers/subPrograms.js
  src/helpers/utils.js
  src/models/CourseBill.js
  src/models/CourseBillsNumber.js
  src/models/Step.js
  src/models/SubProgram.js
  src/models/ThirdPartyPayer.js
  src/repositories/CourseRepository.js
  src/routes/courseBills.js
  src/routes/events.js
  src/routes/helpers.js
  src/routes/preHandlers/courseBills.js
  src/routes/preHandlers/helpers.js
  src/routes/preHandlers/steps.js
  src/routes/preHandlers/subPrograms.js
  src/routes/preHandlers/users.js
  src/routes/steps.js
  src/routes/thirdPartyPayers.js
  src/routes/validations/utils.js
  tests/integration/courseBills.test.js
  tests/integration/events.test.js
  tests/integration/exports.test.js
  tests/integration/helpers.test.js
  tests/integration/helpers/authentication.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/steps.test.js
  tests/integration/subPrograms.test.js
  tests/integration/thirdPartyPayers.test.js
  tests/unit/data/courseBill.test.js
  tests/unit/data/creditNote.test.js
  tests/unit/helpers/courseBills.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/dates/companiDates.test.js
  tests/unit/helpers/eventsRepetition.test.js
  tests/unit/helpers/historyExport.test.js
  tests/unit/helpers/programs.test.js
  tests/unit/helpers/subPrograms.test.js
  tests/unit/helpers/utils.test.js
  tests/unit/helpers/utilsValidation.test.js
Labels: staging

#1860 COM-2734 - Fix Corentin's reviews
  src/data/pdf/billing/creditNote.js
  tests/unit/data/creditNote.test.js
Labels: dev

#1862 MES-21-03
  src/data/pdf/billing/creditNote.js
  src/routes/preHandlers/courseBills.js
  tests/integration/courseBills.test.js
  tests/integration/seed/courseBillsSeed.js
  tests/unit/data/creditNote.test.js
Labels: staging

#1865 MES 22-03
  src/helpers/events.js
  src/routes/thirdPartyPayers.js
  tests/integration/seed/thirdPartyPayersSeed.js
  tests/integration/thirdPartyPayers.test.js
  tests/unit/helpers/events.test.js
Labels: master

#1868 Com 2767
  tests/end2end/seed/billingSeed.js
  tests/end2end/seed/planningSeed.js
Labels: dev, tests

#1870 COM-2760: can update vendor company
  src/controllers/vendorCompanyController.js
  src/helpers/translate.js
  src/helpers/vendorCompanies.js
  src/routes/establishments.js
  src/routes/validations/utils.js
  src/routes/vendorCompanies.js
  tests/integration/vendorCompanies.test.js
  tests/unit/helpers/vendorCompanies.test.js
Labels: dev

#1869 Com 2758
  src/controllers/courseController.js
  src/data/pdf/completionCertificate.js
  src/data/pdf/fonts/Calibri-Bold.TTF
  src/data/pdf/fonts/Calibri-Italic.ttf
  src/data/pdf/fonts/Calibri-Regular.ttf
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/pdf.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/data/completionCertificate.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1872 COM-2754: return bills for companies
  src/controllers/courseBillController.js
  src/helpers/constants.js
  src/helpers/courseBills.js
  src/routes/courseBills.js
  src/routes/preHandlers/courseBills.js
  tests/integration/courseBills.test.js
  tests/unit/helpers/courseBills.test.js
Labels: dev

#1873 Com 2770
  tests/end2end/seed/billingSeed.js
Labels: dev, tests

#1874 COM-2751: block funder deletion if used
  src/controllers/courseFundingOrganisationController.js
  src/helpers/courseFundingOrganisations.js
  src/models/CourseFundingOrganisation.js
  src/routes/preHandlers/courseFundingOrganisation.js
  tests/integration/courseFundingOrganisations.test.js
  tests/integration/seed/courseFundingOrganisationsSeed.js
  tests/unit/helpers/courseFundingOrganisations.test.js
Labels: dev

#1875 COM-2756: move type from post route payload to put route payload
  src/models/Company.js
  src/routes/companies.js
  tests/integration/companies.test.js
Labels: dev

#1877 COM-2758: return boolean to display download button
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev
