Repository CompaniTech/compani-api, pull requests merged in 2022-10, with the labels that each got.

#2047 MES 03/10/22
  src/repositories/EventRepository.js
  tests/unit/repositories/EventRepositories.test.js
Labels: staging

#2046 COM-3022: add integration test
  tests/integration/events.test.js
  tests/integration/seed/eventsSeed.js
Labels: tests

#2048 COM-3213 CompaniDuration accepts iso string
  src/helpers/dates/companiDurations.js
  tests/unit/helpers/dates/companiDuration.test.js
Labels: dev

#2051 COM-3200: populate slots
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2049 COM-3220: coach can update company representative
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
Labels: bug

#2054 Com 3215
  src/helpers/dates/companiDates.js
  src/helpers/steps.js
  tests/unit/helpers/dates/companiDates.test.js
Labels: dev

#2059 COM-3225: return identity
  .github/pull_request_template.md
  src/helpers/attendanceSheets.js
  tests/unit/helpers/attendanceSheets.test.js
Labels: dev

#2062 MES 14/10
  .github/pull_request_template.md
  src/helpers/attendanceSheets.js
  src/helpers/courses.js
  src/helpers/dates.js
  src/helpers/dates/companiDates.js
  src/helpers/dates/companiDurations.js
  src/helpers/delivery.js
  src/helpers/draftBills.js
  src/helpers/draftPay.js
  src/helpers/eventsRepetition.js
  src/helpers/historyExport.js
  src/helpers/repetitions.js
  src/helpers/stats.js
  src/helpers/steps.js
  src/helpers/utils.js
  src/repositories/EventRepository.js
  src/routes/preHandlers/bills.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/repetitions.js
  tests/integration/courses.test.js
  tests/integration/events.test.js
  tests/integration/repetitions.test.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/creditNotesSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/repetitionsSeed.js
  tests/integration/seed/statsSeed.js
  tests/unit/helpers/attendanceSheets.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/dates/companiDates.test.js
  tests/unit/helpers/dates/companiDuration.test.js
  tests/unit/helpers/delivery.test.js
  tests/unit/helpers/sectorHistories.test.js
  tests/unit/helpers/stat.test.js
Labels: staging

#2067 COM-3248: add toISO method
  src/helpers/dates/companiDurations.js
  tests/unit/helpers/dates/companiDuration.test.js
Labels: dev

#2071 Com 3246
  src/helpers/constants.js
  src/helpers/dates/companiDurations.js
  src/helpers/utils.js
  tests/unit/helpers/dates/companiDuration.test.js
  tests/unit/helpers/utils.test.js
Labels: dev

#2074 Com 3259 2
  src/data/pdf/attendanceSheet/interAttendanceSheet.js
  src/data/pdf/attendanceSheet/intraAttendanceSheet.js
  src/data/pdf/courseBilling/courseBill.js
  src/data/pdf/courseBilling/courseCreditNote.js
  src/data/pdf/courseBilling/utils.js
  src/helpers/courseBills.js
  src/helpers/courseCreditNotes.js
  src/helpers/courses.js
  tests/unit/data/courseBill.test.js
  tests/unit/data/courseCreditNote.test.js
  tests/unit/data/interAttendanceSheet.test.js
  tests/unit/data/intraAttendanceSheet.test.js
  tests/unit/helpers/courseBills.test.js
  tests/unit/helpers/courseCreditNotes.test.js
  tests/unit/helpers/courses.test.js
Labels: bug, dev

#2077 Com 3259 3
  src/data/pdf/completionCertificate.js
  src/data/pdf/customerQRCode.js
  src/data/pdf/customerQRCode/customerQRCode.js
  src/data/pdf/taxCertificates.js
  src/helpers/courses.js
  src/helpers/customers.js
  src/helpers/file.js
  src/helpers/pdf.js
  src/helpers/taxCertificates.js
  tests/unit/data/bill.test.js
  tests/unit/data/completionCertificate.test.js
  tests/unit/data/creditNote.test.js
  tests/unit/data/customerQRCode.test.js
  tests/unit/data/taxCertificates.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/customers.test.js
  tests/unit/helpers/file.test.js
  tests/unit/helpers/taxCertificates.test.js
Labels: bug, dev

#2080 COM-3267 accept millis on objet format in companiDuration parser
  src/helpers/constants.js
  tests/unit/helpers/dates/companiDuration.test.js
Labels: bug

#2081 COM-3265: remove formatHourWithMinute
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/utils.js
Labels: dev
