Repository CompaniTech/compani-api, pull requests merged in 2022-01, with the labels that each got.

#1768 COM-2578 add checkbox to check if we fold section
  .github/pull_request_template.md
Labels: dev

#1774 MES intermediaire 0501
  src/helpers/draftBills.js
  src/routes/preHandlers/sms.js
  tests/integration/seed/smsSeed.js
  tests/integration/sms.test.js
  tests/unit/helpers/draftbills.test.js
Labels: staging

#1775 MES intermediaire 05-01 (pipeline)
  src/helpers/draftBills.js
  src/routes/preHandlers/sms.js
  tests/integration/seed/smsSeed.js
  tests/integration/sms.test.js
  tests/unit/helpers/draftbills.test.js
Labels: master

#1777 Com 2617
  src/controllers/exportController.js
  src/data/rights.js
  src/helpers/constants.js
  src/helpers/historyExport.js
  src/routes/exports.js
  src/routes/preHandlers/exports.js
  tests/integration/exports.test.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1780 COM-2618: add new fields in course export
  src/helpers/historyExport.js
  src/models/CourseSlot.js
  tests/integration/exports.test.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1779 Com 2613
  src/controllers/attendanceController.js
  src/data/rights.js
  src/helpers/attendances.js
  src/models/CourseSlot.js
  src/routes/attendanceSheets.js
  src/routes/attendances.js
  src/routes/preHandlers/attendances.js
  tests/integration/attendances.test.js
  tests/integration/seed/attendancesSeed.js
  tests/unit/helpers/attendances.test.js
  tests/unit/helpers/authorization.test.js
Labels: dev

#1785 COM-2613 remove step in response of unscubscribed route
  src/helpers/attendances.js
  tests/unit/helpers/attendances.test.js
Labels: dev

#1782 Com 2619
  src/controllers/exportController.js
  src/helpers/constants.js
  src/helpers/courses.js
  src/helpers/historyExport.js
  src/helpers/utils.js
  tests/integration/exports.test.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/historyExport.test.js
  tests/unit/helpers/utils.test.js
Labels: dev

#1789 COM-2620: add new fields about presence
  src/helpers/historyExport.js
  tests/integration/exports.test.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1796 fix test removing comma
  tests/integration/exports.test.js
Labels: master

#1797 COM-2614: refacto progress in step and course
  src/helpers/courses.js
  src/helpers/steps.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/steps.test.js
Labels: dev

#1799 Com 2655
  .github/workflows/node.js.yml
Labels: dev
