Repository CompaniTech/compani-api, pull requests merged in 2022-04, with the labels that each got.

#1880 COM-2761: add margin
  src/data/pdf/attendanceSheet/utils.js
  tests/unit/data/interAttendanceSheet.test.js
  tests/unit/data/intraAttendanceSheet.test.js
Labels: dev

#1882 Com 2755
  src/controllers/coursePaymentController.js
  src/helpers/courseBills.js
  src/helpers/coursePayments.js
  src/models/CourseBill.js
  src/models/CoursePayment.js
  src/models/CoursePaymentNumber.js
  src/routes/coursePayments.js
  src/routes/index.js
  src/routes/preHandlers/coursePayments.js
  tests/integration/coursePayments.test.js
  tests/integration/helpers/authentication.js
  tests/integration/seed/coursePaymentsSeed.js
  tests/unit/helpers/courseBills.test.js
  tests/unit/helpers/coursePayments.test.js
Labels: dev

#1888 COM-2785 - add log before controller execution
  src/controllers/attendanceController.js
  src/controllers/balanceController.js
  src/controllers/billsController.js
  src/controllers/companyController.js
  src/controllers/courseController.js
  src/controllers/customerController.js
  src/controllers/eventController.js
  src/controllers/exportController.js
  src/controllers/payController.js
  src/controllers/statController.js
  src/controllers/teletransmissionController.js
Labels: bug, dev

#1890 COM-2771: edit course payment
  src/controllers/coursePaymentController.js
  src/helpers/coursePayments.js
  src/helpers/translate.js
  src/routes/coursePayments.js
  src/routes/preHandlers/coursePayments.js
  tests/integration/coursePayments.test.js
  tests/integration/seed/coursePaymentsSeed.js
  tests/unit/helpers/coursePayments.test.js
Labels: dev

#1892 COM-2784 - take timestamp into account when event is not billed
  src/helpers/delivery.js
  tests/unit/helpers/delivery.test.js
Labels: bug, dev

#1894 COM-2785 - add log on route
  src/controllers/billsController.js
  src/controllers/courseBillController.js
  src/controllers/courseController.js
  src/controllers/creditNoteController.js
  src/controllers/customerController.js
  src/controllers/eventController.js
  src/controllers/taxCertificateController.js
Labels: dev

#1895 COM-2800 - downgrade docxtemplater to fix bug
  package-lock.json
  package.json
Labels: dependancies

#1896 Com 2799
  src/helpers/delivery.js
  tests/unit/helpers/delivery.test.js
Labels: bug, dev

#1897 Com 2773
  src/helpers/courseBills.js
  src/routes/preHandlers/courseCreditNotes.js
  tests/integration/courseCreditNotes.test.js
  tests/unit/helpers/courseBills.test.js
Labels: dev

#1898 Com 2802
  src/helpers/draftBills.js
  tests/unit/helpers/draftbills.test.js
Labels: bug, dev

#1901 Com 2810
  src/helpers/dates/companiDates.js
  src/helpers/draftFinalPay.js
  src/helpers/draftPay.js
  src/helpers/events.js
  src/repositories/EventRepository.js
  tests/unit/helpers/draftFinalPay.test.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/events.test.js
Labels: bug, dev

#1903 Com 2810 2
  src/helpers/draftPay.js
  src/repositories/EventRepository.js
  tests/unit/helpers/draftPay.test.js
Labels: bug, dev

#1905 MES 25/04 - add perf in paie to MES
  src/helpers/dates/companiDates.js
  src/helpers/draftFinalPay.js
  src/helpers/draftPay.js
  src/helpers/events.js
  src/repositories/EventRepository.js
  tests/unit/helpers/draftFinalPay.test.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/events.test.js
Labels: master

#1902 COM-2792: new field estimatedstartdate on model and export
  src/helpers/historyExport.js
  src/models/Course.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/exports.test.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1906 Com 2805
  src/helpers/draftBills.js
  src/helpers/numbers.js
  src/helpers/utils.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/draftbills.test.js
  tests/unit/helpers/numbers.test.js
  tests/unit/helpers/utils.test.js
Labels: bug, dev

#1909 Com 2822
  src/helpers/dates.js
  src/helpers/eventHistories.js
  src/helpers/events.js
  src/helpers/utils.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/utils.test.js
Labels: bug, dev

#1908 COM-2823 add limit to countDocument in countSubscriptionsUsage
  src/helpers/customers.js
  src/models/Customer.js
  tests/integration/customers.test.js
  tests/integration/seed/customersSeed.js
  tests/unit/helpers/customers.test.js
Labels: dev

#1910 Com 2824
  src/helpers/courses.js
  src/helpers/customers.js
  src/helpers/draftBills.js
  src/helpers/events.js
  src/helpers/historyExport.js
  tests/unit/helpers/customers.test.js
  tests/unit/helpers/draftbills.test.js
Labels: bug, dev
