Repository CompaniTech/compani-api, pull requests merged in 2022-08, with the labels that each got.

#2005 Com 2287
  tests/integration/seed/questionnaireHistoriesSeed.js
  tests/integration/seed/questionnairesSeed.js
  tests/integration/seed/rolesSeed.js
  tests/integration/seed/sectorsSeed.js
  tests/integration/seed/smsSeed.js
  tests/integration/seed/statsSeed.js
Labels: dev, tests

#2006 COM-2966 fix contract versino deletion
  src/helpers/contracts.js
  tests/integration/contracts.test.js
  tests/unit/helpers/contracts.test.js
Labels: bug, dev

#2007 MES intermediaire 08/08
  src/helpers/contracts.js
  tests/integration/contracts.test.js
  tests/unit/helpers/contracts.test.js
Labels: bug, master

#2008 Com 2971
  src/helpers/delivery.js
  src/helpers/draftBills.js
  tests/unit/helpers/draftbills.test.js
Labels: bug, dev

#2010 COM-2394 - CUSTOMERS ROUTES
  src/routes/preHandlers/customers.js
  tests/end2end/seed/billingSeed.js
  tests/integration/customers.test.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/events.test.js
Labels: dev

#2012 COM-2968 fix survey card initialisation
  src/models/Card.js
  tests/integration/activities.test.js
  tests/integration/thirdPartyPayers.test.js
Labels: bug, dev
