Repository CompaniTech/compani-api, pull requests merged in 2022-02, with the labels that each got.

#1801 COM-2615: return presence progress
  src/helpers/courses.js
  src/helpers/dates/companiDurations.js
  src/helpers/steps.js
  src/helpers/utils.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/dates/companiDuration.test.js
  tests/unit/helpers/steps.test.js
  tests/unit/helpers/utils.test.js
Labels: dev

#1803 COM-2642: return slots in steps
  src/helpers/courses.js
  src/helpers/steps.js
  tests/unit/helpers/courses.test.js
Labels: dev

#1805 COM-2653: isBusinessDay function
  src/helpers/constants.js
  src/helpers/dates/companiDates.js
  tests/unit/helpers/dates/companiDates.test.js
Labels: dev

#1808 Com 2651
  src/helpers/dates/companiDates.js
  src/helpers/stats.js
  src/repositories/StatRepository.js
  tests/unit/helpers/dates/companiDates.test.js
  tests/unit/helpers/stat.test.js
Labels: dev

#1810 MEP mobile
  .github/workflows/node.js.yml
  src/controllers/attendanceController.js
  src/controllers/courseFundingOrganisationController.js
  src/data/rights.js
  src/helpers/attendances.js
  src/helpers/constants.js
  src/helpers/courseFundingOrganisations.js
  src/helpers/courses.js
  src/helpers/dates/companiDates.js
  src/helpers/dates/companiDurations.js
  src/helpers/dates/holidays.js
  src/helpers/stats.js
  src/helpers/steps.js
  src/helpers/translate.js
  src/helpers/utils.js
  src/models/CourseFundingOrganisation.js
  src/repositories/StatRepository.js
  src/routes/attendances.js
  src/routes/courseFundingOrganisations.js
  src/routes/index.js
  src/routes/preHandlers/attendances.js
  src/routes/preHandlers/courseFundingOrganisation.js
  tests/integration/attendances.test.js
  tests/integration/courseFundingOrganisations.test.js
  tests/integration/helpers/authentication.js
  tests/integration/seed/attendancesSeed.js
  tests/integration/seed/courseFundingOrganisationsSeed.js
  tests/unit/helpers/attendances.test.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/courseFundingOrganisations.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/dates/companiDates.test.js
  tests/unit/helpers/dates/companiDuration.test.js
  tests/unit/helpers/stat.test.js
  tests/unit/helpers/steps.test.js
  tests/unit/helpers/utils.test.js
Labels: staging

#1811 COM-2677 - fix funding display
  src/helpers/bills.js
  src/helpers/dates/companiDates.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/dates/companiDates.test.js
Labels: bug, dev

#1812 MES intermediaire 08/02
  src/helpers/bills.js
  src/helpers/dates/companiDates.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/dates/companiDates.test.js
Labels: master

#1813 COM-2665: create and list billing item
  src/controllers/courseBillingItemController.js
  src/controllers/courseFundingOrganisationController.js
  src/helpers/courseBillingItems.js
  src/helpers/translate.js
  src/models/CourseBillingItem.js
  src/models/CourseFundingOrganisation.js
  src/routes/courseBillingItems.js
  src/routes/index.js
  src/routes/preHandlers/courseBillingItems.js
  tests/integration/courseBillingItems.test.js
  tests/integration/helpers/authentication.js
  tests/integration/seed/courseBillingItemsSeed.js
  tests/unit/helpers/courseBillingItemps.test.js
Labels: dev

#1816 Com 2679
  src/helpers/dataExport.js
  src/helpers/historyExport.js
  src/helpers/utils.js
  tests/integration/exports.test.js
  tests/unit/helpers/dataExport.test.js
  tests/unit/helpers/historyExport.test.js
Labels: bug

#1818 COM-2663: add new field in course slot export
  src/helpers/historyExport.js
  tests/integration/exports.test.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1815 Com 2657
  src/models/CreditNote.js
  src/routes/validations/creditNote.js
  tests/integration/creditNotes.test.js
Labels: dev

#1817 Com 2662
  src/helpers/historyExport.js
  tests/integration/exports.test.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1822 COM-2662: move columns
  src/helpers/historyExport.js
  tests/integration/exports.test.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1824 COM-2679: change column name
  src/helpers/historyExport.js
  tests/integration/exports.test.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1821 COM-2657 - Add billingItemList to CreditNotes
  src/helpers/creditNotes.js
  src/models/Bill.js
  src/models/CreditNote.js
  src/models/schemaDefinitions/billing.js
  src/routes/creditNotes.js
  src/routes/preHandlers/creditNotes.js
  src/routes/validations/creditNote.js
  tests/integration/creditNotes.test.js
  tests/integration/seed/creditNotesSeed.js
  tests/unit/helpers/creditNotes.test.js
Labels: dev

#1825 Com 2669
  src/helpers/creditNotes.js
  src/routes/bills.js
  src/routes/validations/billingItem.js
  src/routes/validations/creditNote.js
  tests/integration/creditNotes.test.js
  tests/integration/seed/creditNotesSeed.js
  tests/unit/helpers/creditNotes.test.js
Labels: dev

#1828 MES 21/02
  src/controllers/courseBillingItemController.js
  src/controllers/courseFundingOrganisationController.js
  src/data/pdf/billing/bill.js
  src/data/pdf/billing/creditNote.js
  src/data/pdf/billing/utils.js
  src/helpers/courseBillingItems.js
  src/helpers/creditNotes.js
  src/helpers/dataExport.js
  src/helpers/dates/companiIntervals.js
  src/helpers/events.js
  src/helpers/eventsRepetition.js
  src/helpers/historyExport.js
  src/helpers/stats.js
  src/helpers/translate.js
  src/helpers/utils.js
  src/models/Bill.js
  src/models/CourseBillingItem.js
  src/models/CourseFundingOrganisation.js
  src/models/CreditNote.js
  src/models/Event.js
  src/models/User.js
  src/models/schemaDefinitions/billing.js
  src/models/schemaDefinitions/identity.js
  src/repositories/EventRepository.js
  src/repositories/SectorHistoryRepository.js
  src/repositories/StatRepository.js
  src/routes/bills.js
  src/routes/courseBillingItems.js
  src/routes/creditNotes.js
  src/routes/customers.js
  src/routes/index.js
  src/routes/preHandlers/courseBillingItems.js
  src/routes/preHandlers/creditNotes.js
  src/routes/validations/billingItem.js
  src/routes/validations/creditNote.js
  tests/integration/courseBillingItems.test.js
  tests/integration/creditNotes.test.js
  tests/integration/events.test.js
  tests/integration/exports.test.js
  tests/integration/helpers/authentication.js
  tests/integration/seed/courseBillingItemsSeed.js
  tests/integration/seed/creditNotesSeed.js
  tests/integration/seed/exportsSeed.js
  tests/unit/data/billingUtils.test.js
  tests/unit/data/creditNote.test.js
  tests/unit/helpers/courseBillingItemps.test.js
  tests/unit/helpers/creditNotes.test.js
  tests/unit/helpers/dataExport.test.js
  tests/unit/helpers/dates/companiIntervals.test.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/historyExport.test.js
  tests/unit/helpers/stat.test.js
  tests/unit/repositories/EventRepositories.test.js
Labels: staging

#1830 COM-2696: create routes
  src/controllers/courseBillController.js
  src/helpers/courseBills.js
  src/helpers/translate.js
  src/models/CourseBill.js
  src/routes/courseBills.js
  src/routes/index.js
  src/routes/preHandlers/courseBills.js
  tests/integration/courseBills.test.js
  tests/integration/helpers/authentication.js
  tests/integration/seed/courseBillsSeed.js
  tests/unit/helpers/courseBills.test.js
Labels: dev

#1829 Com 2709
  src/helpers/dataExport.js
  src/helpers/subscriptions.js
  src/models/schemaDefinitions/subscription.js
  src/routes/customers.js
  src/routes/preHandlers/customers.js
  tests/end2end/seed/billingSeed.js
  tests/end2end/seed/planningSeed.js
  tests/integration/bills.test.js
  tests/integration/customers.test.js
  tests/integration/exports.test.js
  tests/integration/seed/balanceSeed.js
  tests/integration/seed/billsSeed.js
  tests/integration/seed/contractsSeed.js
  tests/integration/seed/creditNotesSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/finalPaySeed.js
  tests/integration/seed/paySeed.js
  tests/integration/seed/paymentsSeed.js
  tests/integration/seed/servicesSeed.js
  tests/integration/seed/teletransmissionSeed.js
  tests/unit/helpers/dataExport.test.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/quotes.test.js
  tests/unit/helpers/subscriptions.test.js
Labels: dev

#1831 Com 2713
  src/helpers/historyExport.js
  tests/unit/helpers/historyExport.test.js
Labels: bug, dev

#1832 Com 2697
  src/controllers/courseBillController.js
  src/controllers/exportController.js
  src/helpers/courseBills.js
  src/helpers/historyExport.js
  src/helpers/translate.js
  src/models/Course.js
  src/routes/courseBills.js
  src/routes/preHandlers/courseBills.js
  tests/integration/courseBills.test.js
  tests/integration/exports.test.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/courseBills.test.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1833 COM-2702: add count field
  src/helpers/courseBills.js
  src/models/CourseBill.js
  src/routes/courseBills.js
  tests/integration/courseBills.test.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/courseBills.test.js
  tests/unit/helpers/historyExport.test.js
Labels: dev

#1834 Com 2689
  src/helpers/customers.js
  src/routes/customers.js
  src/routes/preHandlers/customers.js
  tests/integration/customers.test.js
  tests/integration/seed/customersSeed.js
  tests/unit/helpers/customers.test.js
Labels: dev
