Repository CompaniTech/compani-api, pull requests merged in 2022-12, with the labels that each got.

#2123 Feature inter courses companies
  src/controllers/courseController.js
  src/helpers/constants.js
  src/helpers/courseBills.js
  src/helpers/courseHistories.js
  src/helpers/courses.js
  src/helpers/questionnaires.js
  src/helpers/translate.js
  src/helpers/users.js
  src/models/Course.js
  src/models/CourseHistory.js
  src/routes/courses.js
  src/routes/preHandlers/attendanceSheets.js
  src/routes/preHandlers/attendances.js
  src/routes/preHandlers/courseBills.js
  src/routes/preHandlers/courseHistories.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/users.js
  src/routes/users.js
  tests/integration/attendanceSheets.test.js
  tests/integration/attendances.test.js
  tests/integration/courseBills.test.js
  tests/integration/courses.test.js
  tests/integration/exports.test.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/integration/seed/attendancesSeed.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/courseCreditNotesSeed.js
  tests/integration/seed/courseHistoriesSeed.js
  tests/integration/seed/courseSlotsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/questionnaireHistoriesSeed.js
  tests/integration/seed/questionnairesSeed.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/seed/usersSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/courseBills.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/questionnaires.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#2126 COM-3322 - displays only validated invoices in courseHistoryExport
  src/helpers/vendorHistoryExport.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: dev

#2127 Com 3306
  src/helpers/vendorHistoryExport.js
  tests/integration/exports.test.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: dev

#2131 COM-3328: use company in attendance get
  src/controllers/attendanceController.js
  src/controllers/exportController.js
  src/helpers/attendances.js
  src/helpers/courses.js
  src/helpers/vendorHistoryExport.js
  src/models/Attendance.js
  src/repositories/CourseRepository.js
  src/routes/preHandlers/courses.js
  tests/unit/helpers/attendances.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: dev

#2135 COM-3328: fix for trainers
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: bug

#2136 MES-2 12/12 fix
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: master

#2138 Com 3332
  src/helpers/attendanceSheets.js
  src/models/AttendanceSheet.js
  src/routes/attendanceSheets.js
  src/routes/preHandlers/attendanceSheets.js
  tests/integration/attendanceSheets.test.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/attendanceSheets.test.js
Labels: dev

#2139 COM-3323: remove populate
  src/helpers/users.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#2141 Com 3336
  src/models/User.js
  tests/integration/companyLinkRequests.test.js
  tests/integration/contracts.test.js
  tests/integration/courses.test.js
  tests/integration/helpers/authentication.js
  tests/integration/payDocuments.test.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/integration/seed/attendancesSeed.js
  tests/integration/seed/balanceSeed.js
  tests/integration/seed/billsSeed.js
  tests/integration/seed/companiesSeed.js
  tests/integration/seed/contractsSeed.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/courseSlotsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/creditNotesSeed.js
  tests/integration/seed/customerAbsencesSeed.js
  tests/integration/seed/customerPartnersSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/driveSeed.js
  tests/integration/seed/emailSeed.js
  tests/integration/seed/establishmentsSeed.js
  tests/integration/seed/eventHistoriesSeed.js
  tests/integration/seed/eventsSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/finalPaySeed.js
  tests/integration/seed/helpersSeed.js
  tests/integration/seed/internalHoursSeed.js
  tests/integration/seed/payDocumentsSeed.js
  tests/integration/seed/paySeed.js
  tests/integration/seed/paymentsSeed.js
  tests/integration/seed/questionnairesSeed.js
  tests/integration/seed/repetitionsSeed.js
  tests/integration/seed/scriptsSeed.js
  tests/integration/seed/sectorsSeed.js
  tests/integration/seed/smsSeed.js
  tests/integration/seed/statsSeed.js
  tests/integration/seed/taxCertificatesSeed.js
  tests/integration/seed/userCompaniesSeed.js
  tests/integration/seed/usersSeed.js
  tests/integration/userCompanies.test.js
  tests/integration/users.test.js
  tests/seed/authUsersSeed.js
Labels: dev

#2142 Com 3341
  src/helpers/users.js
  tests/integration/seed/userCompaniesSeed.js
  tests/integration/seed/usersSeed.js
  tests/integration/userCompanies.test.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#2144 COM-3347 - update github action mongodb version
  .github/workflows/integration.js.yml
Labels: dev
