Repository CompaniTech/compani-api, pull requests merged in 2023-02, with the labels that each got.

#2174 Com 3346
  src/helpers/courseHistories.js
  tests/unit/helpers/courseHistories.test.js
Labels: bug

#2173 Com 3384
  package.json
  src/helpers/userCompanies.js
  src/helpers/users.js
  src/routes/preHandlers/users.js
  tests/integration/exports.test.js
  tests/integration/seed/seedsVerification.test.js
  tests/integration/seed/userCompaniesSeed.js
  tests/integration/seed/usersSeed.js
  tests/integration/userCompanies.test.js
  tests/seed/authSectorsSeed.js
  tests/unit/helpers/userCompanies.test.js
Labels: dev

#2177 MES 06/02
  .github/workflows/integration.js.yml
  .github/workflows/lint.yml
  package-lock.json
  package.json
  src/helpers/courseBills.js
  src/helpers/courseHistories.js
  src/helpers/courses.js
  src/helpers/dates/companiDurations.js
  src/helpers/dates/utils.js
  src/helpers/translate.js
  src/helpers/userCompanies.js
  src/helpers/users.js
  src/helpers/utils.js
  src/repositories/CourseRepository.js
  src/routes/preHandlers/companyLinkRequests.js
  src/routes/preHandlers/courseSlot.js
  src/routes/preHandlers/userCompanies.js
  src/routes/preHandlers/users.js
  tests/integration/companyLinkRequests.test.js
  tests/integration/courseBills.test.js
  tests/integration/courseSlots.test.js
  tests/integration/exports.test.js
  tests/integration/repetitions.test.js
  tests/integration/seed/companyLinkRequestsSeed.js
  tests/integration/seed/repetitionsSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/integration/seed/userCompaniesSeed.js
  tests/integration/seed/usersSeed.js
  tests/integration/userCompanies.test.js
  tests/integration/users.test.js
  tests/seed/authSectorsSeed.js
  tests/seed/authUsersSeed.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/dates/companiDuration.test.js
  tests/unit/helpers/dates/utils.test.js
  tests/unit/helpers/userCompanies.test.js
  tests/unit/helpers/utils.test.js
Labels: master

#2178 COM-3333: add company in query
  src/controllers/attendanceSheetController.js
  src/helpers/attendanceSheets.js
  src/helpers/vendorHistoryExport.js
  src/models/AttendanceSheet.js
  src/routes/attendanceSheets.js
  src/routes/preHandlers/attendanceSheets.js
  src/routes/preHandlers/courses.js
  tests/unit/helpers/attendanceSheets.test.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: dev

#2181 MES 08/02
  package.json
Labels: master

#2182 Com 3387
  src/controllers/courseController.js
  src/controllers/exportController.js
  src/controllers/questionnaireController.js
  src/helpers/courses.js
  src/helpers/questionnaireHistories.js
  src/helpers/questionnaires.js
  src/helpers/vendorHistoryExport.js
  src/models/QuestionnaireHistory.js
  tests/integration/questionnaireHistories.test.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/questionnaireHistoriesSeed.js
  tests/integration/seed/questionnairesSeed.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/questionnaireHistories.test.js
  tests/unit/helpers/questionnaires.test.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: dev

#2183 COM-3397 change company of questionnaire history in export
  src/helpers/vendorHistoryExport.js
  tests/integration/exports.test.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: dev

#2185 Com 3392
  src/helpers/courses.js
  src/helpers/users.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#2184 Com 3388
  src/helpers/questionnaires.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/questionnairesSeed.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev

#2186 COM-3393: fix wrong start date in error message
  src/helpers/userCompanies.js
  tests/integration/seed/usersSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/userCompanies.test.js
Labels: dev

#2189 decomment tests
  tests/integration/users.test.js
Labels: tests

#2192 COM-3402: filter trainee progress by company
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2194 COM-3367: use company at registration
  src/helpers/courses.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2193 Com 3398
  src/controllers/stepController.js
  src/controllers/subProgramController.js
  src/helpers/courses.js
  src/helpers/steps.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/steps.test.js
Labels: dev

#2196 COM-3356: create attendance sheet with company at registration
  src/helpers/attendanceSheets.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/unit/helpers/attendanceSheets.test.js
Labels: dev

#2195 COM-3359: use good company in attendance sheet
  src/helpers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev
