Repository CompaniTech/compani-api, pull requests merged in 2023-10, with the labels that each got.

#2298 Com 3555
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
Labels: dev

#2300 COM-3450 - update customer seed
  tests/integration/seed/customersSeed.js
Labels: dev

#2299 Com 3556
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
Labels: dev

#2301 COM-3560: can download attendance sheet
  src/data/pdf/attendanceSheet/intraAttendanceSheet.js
  src/helpers/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/data/intraAttendanceSheet.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2303 COM-3562: can edit slot
  src/routes/preHandlers/courseSlot.js
  tests/integration/courseSlots.test.js
  tests/integration/seed/courseSlotsSeed.js
Labels: dev

#2305 COM-3558: can delete trainee
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
Labels: dev

#2306 COM-3566: return type for courses list
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2307 Com 3580
  src/helpers/questionnaires.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/questionnairesSeed.js
Labels: dev

#2308 COM-3564: can get history
  src/routes/preHandlers/courseHistories.js
  tests/integration/courseHistories.test.js
  tests/integration/seed/courseHistoriesSeed.js
Labels: dev

#2309 MES 17/10/23
  src/data/pdf/attendanceSheet/intraAttendanceSheet.js
  src/data/pdf/billing/bill.js
  src/helpers/companies.js
  src/helpers/courses.js
  src/helpers/historyExport.js
  src/helpers/questionnaires.js
  src/models/User.js
  src/routes/companies.js
  src/routes/courses.js
  src/routes/preHandlers/companies.js
  src/routes/preHandlers/courseHistories.js
  src/routes/preHandlers/courseSlot.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/users.js
  tests/integration/companies.test.js
  tests/integration/courseHistories.test.js
  tests/integration/courseSlots.test.js
  tests/integration/courses.test.js
  tests/integration/exports.test.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/courseHistoriesSeed.js
  tests/integration/seed/courseSlotsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/customersSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/questionnairesSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/integration/seed/trainingContractsSeed.js
  tests/integration/users.test.js
  tests/seed/authUsersSeed.js
  tests/unit/data/intraAttendanceSheet.test.js
  tests/unit/helpers/companies.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/historyExport.test.js
Labels: staging

#2310 COM-3581: can get attendances
  src/routes/preHandlers/attendances.js
  tests/integration/attendances.test.js
  tests/integration/seed/attendancesSeed.js
Labels: dev

#2312 COM-3585: refacto attendance sheet model + adapt for intra holding co…
  src/helpers/attendanceSheets.js
  src/models/AttendanceSheet.js
  src/models/preHooks/validate.js
  src/routes/preHandlers/attendanceSheets.js
  src/routes/preHandlers/courses.js
  tests/integration/attendanceSheets.test.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/unit/helpers/attendanceSheets.test.js
Labels: dev

#2314 COM-3582: can add attendance for not registered trainee but from cour…
  src/routes/preHandlers/attendances.js
  tests/integration/attendances.test.js
  tests/integration/seed/attendancesSeed.js
Labels: dev

#2315 COM-3584: fix error message
  src/helpers/translate.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
Labels: bug

#2316 MES 31-10-23
  src/data/rights.js
  src/helpers/attendanceSheets.js
  src/helpers/translate.js
  src/models/AttendanceSheet.js
  src/models/preHooks/validate.js
  src/routes/preHandlers/attendanceSheets.js
  src/routes/preHandlers/attendances.js
  src/routes/preHandlers/courses.js
  tests/integration/attendanceSheets.test.js
  tests/integration/attendances.test.js
  tests/integration/courses.test.js
  tests/integration/holdings.test.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/integration/seed/attendancesSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/unit/helpers/attendanceSheets.test.js
  tests/unit/helpers/authorization.test.js
Labels: staging
