Repository CompaniTech/compani-api, pull requests merged in 2023-01, with the labels that each got.

#2145 COM-3348 - Improve perf on course history exports
  src/helpers/courses.js
  src/helpers/vendorHistoryExport.js
  tests/integration/pay.test.js
  tests/integration/seed/paySeed.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: bug, dev

#2149 Com 3361
  src/controllers/courseController.js
  src/helpers/courseHistories.js
  src/helpers/courses.js
  src/models/CourseHistory.js
  tests/integration/seed/userCompaniesSeed.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2154 Com 3365
  src/helpers/userCompanies.js
  src/helpers/users.js
  src/models/User.js
  src/routes/preHandlers/sms.js
  src/routes/preHandlers/users.js
  src/routes/users.js
  tests/integration/seed/usersSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/userCompanies.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#2162 Com 3375
  package-lock.json
  package.json
Labels: dependancies

#2160 Com 3353
  src/helpers/users.js
  src/routes/users.js
  tests/integration/courseBills.test.js
  tests/integration/seed/usersSeed.js
  tests/integration/users.test.js
  tests/seed/authUsersSeed.js
  tests/unit/helpers/users.test.js
Labels: dev

#2165 COM-3382 - can't remove courseSlot dates if attendances
  src/helpers/translate.js
  src/routes/preHandlers/courseSlot.js
  tests/integration/courseSlots.test.js
Labels: bug

#2163 COM-3381
  package-lock.json
  package.json
  tests/integration/courseBills.test.js
  tests/integration/repetitions.test.js
  tests/integration/seed/repetitionsSeed.js
Labels: dependancies

#2172 COM-3339: can request attachement for a detached user
  src/routes/preHandlers/companyLinkRequests.js
  tests/integration/companyLinkRequests.test.js
  tests/integration/courseBills.test.js
  tests/integration/seed/companyLinkRequestsSeed.js
  tests/integration/users.test.js
  tests/seed/authUsersSeed.js
Labels: bug
