Repository CompaniTech/compani-api, pull requests merged in 2023-07, with the labels that each got.

#2257 COM-3489: can create user
  src/routes/preHandlers/email.js
  src/routes/preHandlers/users.js
  tests/integration/email.test.js
  tests/integration/seed/emailSeed.js
  tests/integration/users.test.js
Labels: dev

#2258 Com 3499
  src/helpers/vendorCompanies.js
  src/models/VendorCompany.js
  src/routes/preHandlers/vendorCompanies.js
  src/routes/vendorCompanies.js
  tests/integration/vendorCompanies.test.js
  tests/unit/helpers/vendorCompanies.test.js
Labels: dev

#2260 Com 3501
  tests/integration/courseBills.test.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/courseCreditNotesSeed.js
  tests/integration/seed/courseFundingOrganisationsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/seedsVerification.test.js
Labels: tests

#2263 Com 3500
  src/data/rights.js
  src/routes/courseBillingItems.js
  src/routes/courseFundingOrganisations.js
  src/routes/vendorCompanies.js
  tests/integration/seed/vendorCompaniesSeed.js
  tests/integration/vendorCompanies.test.js
  tests/unit/helpers/authorization.test.js
Labels: dev

#2262 Com 3505
  src/helpers/users.js
  src/models/Company.js
  src/routes/companies.js
  src/routes/preHandlers/companies.js
  tests/integration/companies.test.js
  tests/integration/seed/companiesSeed.js
  tests/unit/helpers/users.test.js
Labels: dev

#2264 COM-3504 - populate BillingRepresentative + add prehandler check
  src/helpers/companies.js
  src/routes/companies.js
  src/routes/preHandlers/companies.js
  tests/integration/companies.test.js
  tests/unit/helpers/companies.test.js
Labels: dev

#2266 MES 27/07/2023
  src/data/rights.js
  src/helpers/companies.js
  src/helpers/users.js
  src/models/Company.js
  src/routes/companies.js
  src/routes/courseBillingItems.js
  src/routes/courseFundingOrganisations.js
  src/routes/preHandlers/companies.js
  src/routes/preHandlers/users.js
  src/routes/vendorCompanies.js
  tests/integration/companies.test.js
  tests/integration/courseBills.test.js
  tests/integration/seed/companiesSeed.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/courseCreditNotesSeed.js
  tests/integration/seed/courseFundingOrganisationsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/integration/seed/vendorCompaniesSeed.js
  tests/integration/users.test.js
  tests/integration/vendorCompanies.test.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/companies.test.js
  tests/unit/helpers/users.test.js
Labels: staging

#2265 Com 3515
  tests/integration/seed/coursePaymentsSeed.js
  tests/integration/seed/seedsVerification.test.js
Labels: tests
