Repository CompaniTech/compani-api, pull requests merged in 2023-08, with the labels that each got.

#2271 COM-3355 - dependancies
  .eslintrc.js
  package-lock.json
  package.json
Labels: dev, dependancies

#2272 COM-3355 - MAJ mongodb / mongoose / mongoose-autopopulate
  package-lock.json
  package.json
  src/config/mongoose.js
  src/helpers/contracts.js
  src/helpers/sectorHistories.js
  src/helpers/trainingContracts.js
  src/helpers/vendorHistoryExport.js
  src/repositories/CourseRepository.js
  tests/integration/exports.test.js
  tests/integration/seed/balanceSeed.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/eventHistoriesSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/unit/helpers/activities.test.js
  tests/unit/helpers/activityHistories.test.js
  tests/unit/helpers/attendances.test.js
  tests/unit/helpers/balances.test.js
  tests/unit/helpers/bills.test.js
  tests/unit/helpers/companies.test.js
  tests/unit/helpers/courseSlots.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/dataExport.test.js
  tests/unit/helpers/draftFinalPay.test.js
  tests/unit/helpers/draftPay.test.js
  tests/unit/helpers/eventHistories.test.js
  tests/unit/helpers/events.test.js
  tests/unit/helpers/eventsRepetition.test.js
  tests/unit/helpers/historyExport.test.js
  tests/unit/helpers/questionnaires.test.js
  tests/unit/helpers/sectorHistories.test.js
  tests/unit/helpers/services.test.js
  tests/unit/helpers/vendorCompanies.test.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: dev, dependancies

#2273 Com 3516
  tests/integration/seed/companiesSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/integration/seed/userCompaniesSeed.js
Labels: tests

#2282 COM-3521 - restrictive questionnnaire card templates
  src/routes/questionnaires.js
  tests/integration/questionnaires.test.js
Labels: dev

#2279 COM-3537: can download attendance sheet without trainees
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2278 COM-3538: can archive and unarchive course easily
  src/helpers/courses.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev
