Repository CompaniTech/compani-api, pull requests merged in 2023-09, with the labels that each got.

#2276 Com 3535
  src/helpers/programs.js
  src/helpers/translate.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/subPrograms.js
  tests/integration/courses.test.js
  tests/integration/seed/activitiesSeed.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/integration/seed/attendancesSeed.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/courseCreditNotesSeed.js
  tests/integration/seed/courseFundingOrganisationsSeed.js
  tests/integration/seed/courseHistoriesSeed.js
  tests/integration/seed/coursePaymentsSeed.js
  tests/integration/seed/courseSlotsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/programsSeed.js
  tests/integration/seed/questionnaireHistoriesSeed.js
  tests/integration/seed/questionnairesSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/integration/seed/subProgramsSeed.js
  tests/integration/seed/userCompaniesSeed.js
  tests/integration/seed/usersSeed.js
  tests/integration/subPrograms.test.js
  tests/unit/helpers/programs.test.js
Labels: dev

#2281 COM-3513: can see courses table
  src/helpers/courses.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2286 COM-3539: holding admin as company representative
  src/helpers/users.js
  src/routes/preHandlers/courses.js
  src/routes/users.js
  tests/integration/courses.test.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#2287 Com 3545
  tests/integration/exports.test.js
  tests/integration/seed/emailSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/integration/seed/trainingContractsSeed.js
Labels: tests

#2288 Com 3543
  src/controllers/authenticationController.js
  src/helpers/authentication.js
  src/routes/authentication.js
  src/routes/preHandlers/authentication.js
  tests/integration/authentication.test.js
  tests/integration/seed/usersSeed.js
  tests/unit/helpers/authentication.test.js
Labels: dev

#2290 COM-3568 - throw 401 if missing refresh token
  src/helpers/authentication.js
  src/routes/authentication.js
  src/routes/preHandlers/authentication.js
  tests/integration/authentication.test.js
  tests/integration/seed/emailSeed.js
  tests/unit/helpers/authentication.test.js
Labels: bug, dev

#2291 Com 3551
  src/helpers/constants.js
  src/models/Course.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
Labels: dev

#2294 COM-3570: use get
  src/data/pdf/billing/bill.js
Labels: bug

#2292 Com 3553
  src/helpers/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/integration/seed/trainingContractsSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2296 Com 3559
  src/models/User.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/users.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/integration/users.test.js
Labels: dev
