Repository CompaniTech/compani-api, pull requests merged in 2023-03, with the labels that each got.

#2199 Com 3406
  src/helpers/courseHistories.js
  tests/unit/helpers/courseHistories.test.js
Labels: dev

#2198 Com 3352
  src/helpers/attendances.js
  src/routes/preHandlers/attendances.js
  tests/integration/attendances.test.js
  tests/integration/seed/attendancesSeed.js
  tests/unit/helpers/attendances.test.js
  tests/unit/helpers/courseHistories.test.js
Labels: dev

#2197 COM-3358: display blended/elearning courses count from company
  src/helpers/constants.js
  src/helpers/users.js
  src/models/User.js
  src/routes/users.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#2201 Com 3405
  src/helpers/courses.js
  src/repositories/CourseRepository.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2202 MES 6/03
  src/controllers/stepController.js
  src/controllers/subProgramController.js
  src/helpers/attendanceSheets.js
  src/helpers/attendances.js
  src/helpers/constants.js
  src/helpers/courseHistories.js
  src/helpers/courses.js
  src/helpers/questionnaireHistories.js
  src/helpers/steps.js
  src/helpers/users.js
  src/models/User.js
  src/repositories/CourseRepository.js
  src/routes/preHandlers/attendances.js
  src/routes/preHandlers/courses.js
  src/routes/users.js
  tests/integration/attendances.test.js
  tests/integration/courses.test.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/integration/seed/attendancesSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/attendanceSheets.test.js
  tests/unit/helpers/attendances.test.js
  tests/unit/helpers/courseHistories.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/questionnaireHistories.test.js
  tests/unit/helpers/steps.test.js
  tests/unit/helpers/users.test.js
Labels: staging

#2203 Com 3403
  src/helpers/questionnaires.js
  src/helpers/vendorHistoryExport.js
  tests/unit/helpers/questionnaires.test.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: dev

#2204 COM-3411 fix update role + run it every two weeks
  src/jobs/updateRole.js
  src/plugins/index.js
Labels: dev

#2205 MES 08/03
  src/helpers/questionnaires.js
  src/helpers/vendorHistoryExport.js
  src/jobs/updateRole.js
  src/plugins/index.js
  tests/unit/helpers/questionnaires.test.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: staging

#2206 COM-3413: add tests for attendance, attendance sheet and questionnaire history
  tests/integration/seed/attendancesSeed.js
  tests/integration/seed/questionnaireHistoriesSeed.js
  tests/integration/seed/seedsVerification.test.js
Labels: tests

#2207 Com 3414
  src/helpers/userCompanies.js
  src/routes/preHandlers/email.js
  tests/unit/helpers/userCompanies.test.js
Labels: dev

#2209 Com 3418
  src/controllers/trainingContractController.js
  src/helpers/trainingContracts.js
  src/helpers/translate.js
  src/models/TrainingContract.js
  src/routes/index.js
  src/routes/preHandlers/trainingContracts.js
  src/routes/trainingContracts.js
  tests/integration/seed/trainingContractsSeed.js
  tests/integration/trainingContracts.test.js
  tests/unit/helpers/trainingContracts.test.js
Labels: dev

#2211 Com 3417
  src/data/pdf/trainingContract.js
  src/helpers/courses.js
  src/helpers/trainingContracts.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/data/trainingContract.test.js
  tests/unit/helpers/courses.test.js
Labels: dev
