Repository CompaniTech/compani-api, pull requests merged in 2024-02, with the labels that each got.

#2353 Com 3607
  src/helpers/courses.js
  src/models/Course.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2359 COM-3645 - populate salesRepresentative to display it on ContactProfile
  src/helpers/users.js
  tests/unit/helpers/users.test.js
Labels: dev

#2355 COM-3647 : can display paid mention on bills
  src/controllers/courseBillController.js
  src/data/pdf/courseBilling/courseBill.js
  src/data/pdf/courseBilling/courseCreditNote.js
  src/data/pdf/courseBilling/utils.js
  src/helpers/courseBills.js
  src/routes/courseBills.js
  src/routes/preHandlers/courseBills.js
  tests/unit/data/courseBill.test.js
  tests/unit/data/courseCreditNote.test.js
  tests/unit/helpers/courseBills.test.js
Labels: dev

#2354 COM-3629: trainer can get own trainer missions
  src/controllers/trainerMissionController.js
  src/helpers/trainerMissions.js
  src/models/TrainerMission.js
  src/routes/trainerMissions.js
  tests/integration/seed/trainerMissionsSeed.js
  tests/integration/trainerMissions.test.js
  tests/unit/helpers/trainerMission.test.js
Labels: dev

#2362 MES 07/02/2024
  src/controllers/courseBillController.js
  src/controllers/trainerMissionController.js
  src/data/pdf/courseBilling/courseBill.js
  src/data/pdf/courseBilling/courseCreditNote.js
  src/data/pdf/courseBilling/utils.js
  src/data/pdf/trainerMission.js
  src/data/rights.js
  src/helpers/companies.js
  src/helpers/constants.js
  src/helpers/courseBills.js
  src/helpers/courseSlots.js
  src/helpers/courses.js
  src/helpers/gCloudStorage.js
  src/helpers/steps.js
  src/helpers/trainerMissions.js
  src/helpers/trainingContracts.js
  src/helpers/translate.js
  src/helpers/users.js
  src/helpers/vendorHistoryExport.js
  src/models/Company.js
  src/models/Course.js
  src/models/TrainerMission.js
  src/repositories/CourseRepository.js
  src/routes/authentication.js
  src/routes/companies.js
  src/routes/courseBills.js
  src/routes/preHandlers/companies.js
  src/routes/preHandlers/courseBills.js
  src/routes/preHandlers/trainerMissions.js
  src/routes/trainerMissions.js
  tests/integration/authentication.test.js
  tests/integration/companies.test.js
  tests/integration/seed/companiesSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/integration/seed/trainerMissionsSeed.js
  tests/integration/trainerMissions.test.js
  tests/unit/data/courseBill.test.js
  tests/unit/data/courseCreditNote.test.js
  tests/unit/data/trainerMission.test.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/companies.test.js
  tests/unit/helpers/courseBills.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/trainerMission.test.js
  tests/unit/helpers/users.test.js
Labels: staging

#2360 COM-3658 - yarn upgrade
  package.json
  src/helpers/activities.js
  src/helpers/payDocuments.js
  src/helpers/questionnaires.js
  src/models/preHooks/validate.js
  tests/unit/helpers/activities.test.js
  tests/unit/helpers/payDocuments.test.js
  tests/unit/helpers/questionnaires.test.js
  yarn.lock
Labels: dependancies

#2361 COM-3651 - can select a salesRepresentative at course creation + mutu…
  src/helpers/companies.js
  src/models/Course.js
  src/routes/courses.js
  src/routes/preHandlers/companies.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/utils.js
  tests/integration/courses.test.js
  tests/unit/helpers/companies.test.js
Labels: dev

#2363 COM-3658: fix yarn.lock
  yarn.lock
Labels: bug

#2364 Com 3652
  src/helpers/courses.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2366 COM-3518 : can remove trainer from course
  src/helpers/courses.js
  src/routes/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
Labels: dev
