Repository CompaniTech/compani-api, pull requests merged in 2024-10, with the labels that each got.

#2431 COM-3802: fix big number bug on course bills
  src/data/pdf/courseBilling/courseBill.js
  src/data/pdf/courseBilling/utils.js
  tests/unit/data/courseBill.test.js
Labels: bug

#2433 Com 3813
  .eslintrc.js
  .github/workflows/integration.js.yml
  .github/workflows/lint.yml
  eslint.config.mjs
  package.json
  src/helpers/email.js
  src/models/Google/Drive.js
  yarn.lock
Labels: dependancies

#2436 Com 3815
  src/controllers/courseController.js
  src/helpers/courses.js
  src/helpers/translate.js
  src/models/Course.js
  src/routes/courses.js
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2439 COM-3809: sms history with trainers
  src/routes/preHandlers/courses.js
  tests/integration/courses.test.js
Labels: dev

#2435 COM-3792: order the sequence card is 3 propositions
  src/helpers/constants.js
  src/models/Card.js
  src/models/validations/cardValidation.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/activitiesSeed.js
  tests/integration/seed/cardsSeed.js
  tests/integration/seed/seedsVerification.test.js
Labels: dev
