Repository CompaniTech/compani-api, pull requests merged in 2024-03, with the labels that each got.

#2368 Com 3576
  package.json
  src/controllers/scriptController.js
  src/data/rights.js
  src/helpers/email.js
  src/helpers/emailOptions.js
  src/helpers/eventsRepetition.js
  src/jobs/billDispatch.js
  src/jobs/eventConsistency.js
  src/jobs/eventRepetitions.js
  src/jobs/updateRole.js
  src/plugins/cron.js
  src/plugins/index.js
  src/repositories/BillRepository.js
  src/repositories/EventRepository.js
  src/routes/index.js
  src/routes/scripts.js
  tests/integration/scripts.test.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/eventsRepetition.test.js
  tests/unit/jobs/billDispatch.test.js
  tests/unit/jobs/eventRepetitions.test.js
  yarn.lock
Labels: compani-outils

#2370 MES 06-03-2024
  package.json
  src/controllers/scriptController.js
  src/data/rights.js
  src/helpers/activities.js
  src/helpers/companies.js
  src/helpers/courses.js
  src/helpers/email.js
  src/helpers/emailOptions.js
  src/helpers/eventsRepetition.js
  src/helpers/payDocuments.js
  src/helpers/questionnaires.js
  src/jobs/billDispatch.js
  src/jobs/eventConsistency.js
  src/jobs/eventRepetitions.js
  src/jobs/updateRole.js
  src/models/Course.js
  src/models/preHooks/validate.js
  src/plugins/cron.js
  src/plugins/index.js
  src/repositories/BillRepository.js
  src/repositories/CourseRepository.js
  src/repositories/EventRepository.js
  src/routes/courses.js
  src/routes/index.js
  src/routes/preHandlers/companies.js
  src/routes/preHandlers/courses.js
  src/routes/preHandlers/utils.js
  src/routes/scripts.js
  tests/integration/courses.test.js
  tests/integration/scripts.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/activities.test.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/companies.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/eventsRepetition.test.js
  tests/unit/helpers/payDocuments.test.js
  tests/unit/helpers/questionnaires.test.js
  tests/unit/jobs/billDispatch.test.js
  tests/unit/jobs/eventRepetitions.test.js
  yarn.lock
Labels: staging

#2371 COM-3666: can get holding admins when request on users
  src/helpers/users.js
  src/routes/preHandlers/companies.js
  tests/integration/companies.test.js
  tests/integration/seed/seedsVerification.test.js
  tests/integration/users.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#2375 MES 19/03/2024
  src/helpers/activityHistories.js
  src/helpers/dates/companiDurations.js
  src/helpers/dates/utils.js
  src/helpers/users.js
  src/models/ActivityHistory.js
  src/models/Card.js
  src/models/Step.js
  src/models/validations/cardValidation.js
  src/routes/activityHistories.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  src/routes/preHandlers/companies.js
  src/routes/validations/utils.js
  tests/integration/activities.test.js
  tests/integration/activityHistories.test.js
  tests/integration/cards.test.js
  tests/integration/companies.test.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/integration/seed/cardsSeed.js
  tests/integration/seed/coursesSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/questionnaireHistoriesSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/integration/seed/userCompaniesSeed.js
  tests/integration/users.test.js
  tests/unit/helpers/activityHistories.test.js
  tests/unit/helpers/dates/utils.test.js
  tests/unit/helpers/questionnaires.test.js
  tests/unit/helpers/users.test.js
Labels: staging

#2373 COM-3670 - add program in GET /questionnaires query
  src/helpers/constants.js
  src/models/Questionnaire.js
  src/routes/preHandlers/questionnaires.js
  src/routes/questionnaires.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/questionnairesSeed.js
Labels: dev

#2374 Com 3671
  src/data/rights.js
  src/helpers/authorization.js
  src/helpers/companies.js
  src/helpers/courseBills.js
  src/routes/companies.js
  src/routes/preHandlers/companies.js
  src/routes/preHandlers/courseBills.js
  src/routes/preHandlers/courseCreditNotes.js
  tests/integration/companies.test.js
  tests/integration/courseBills.test.js
  tests/integration/courseCreditNotes.test.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/courseCreditNotesSeed.js
  tests/unit/helpers/authorization.test.js
  tests/unit/helpers/companies.test.js
  tests/unit/helpers/courseBills.test.js
Labels: dev

#2376 Com 3674
  src/helpers/cards.js
  src/helpers/constants.js
  src/models/Card.js
  src/models/validations/cardValidation.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/cardsSeed.js
  tests/integration/seed/seedsVerification.test.js
Labels: dev

#2379 Com 3678
  src/helpers/constants.js
  src/helpers/questionnaires.js
  src/models/QuestionnaireHistory.js
  tests/integration/cards.test.js
  tests/integration/questionnaires.test.js
  tests/integration/seed/seedsVerification.test.js
  tests/unit/helpers/questionnaires.test.js
Labels: dev
