Repository CompaniTech/compani-api, pull requests merged in 2024-12, with the labels that each got.

#2456 COM-3852: sort slots
  src/repositories/CourseRepository.js
Labels: bug

#2455 Com 3845
  src/controllers/attendanceSheetController.js
  src/helpers/attendanceSheets.js
  src/helpers/translate.js
  src/routes/attendanceSheets.js
  src/routes/preHandlers/attendanceSheets.js
  tests/integration/attendanceSheets.test.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/unit/helpers/attendanceSheets.test.js
Labels: dev

#2459 Com 3849
  src/helpers/courses.js
  tests/integration/seed/seedsVerification.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2467 MES 10/12/2024
  .github/workflows/integration.js.yml
  src/controllers/attendanceSheetController.js
  src/helpers/attendanceSheets.js
  src/helpers/courses.js
  src/helpers/translate.js
  src/helpers/vendorHistoryExport.js
  src/models/AttendanceSheet.js
  src/repositories/CourseRepository.js
  src/routes/attendanceSheets.js
  src/routes/preHandlers/attendanceSheets.js
  tests/integration/attendanceSheets.test.js
  tests/integration/exports.test.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/unit/helpers/attendanceSheets.test.js
  tests/unit/helpers/courses.test.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: master

#2470 Com 3866
  package.json
  yarn.lock
Labels: dependancies

#2468 COM-3851: add field signatures in attendance sheet
  src/controllers/attendanceSheetController.js
  src/helpers/attendanceSheets.js
  src/helpers/courses.js
  src/helpers/gCloudStorage.js
  src/models/AttendanceSheet.js
  src/routes/attendanceSheets.js
  tests/integration/attendanceSheets.test.js
  tests/unit/helpers/attendanceSheets.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2469 Com 3853
  src/helpers/courses.js
  src/models/AttendanceSheet.js
  src/models/Course.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2472 COM-3870: sort slots
  src/helpers/courses.js
  tests/unit/helpers/courses.test.js
Labels: dev
