Repository CompaniTech/compani-api, pull requests merged in 2024-07, with the labels that each got.

#2400 COM-3736: add two new fields to vendorCompany
  src/models/VendorCompany.js
  src/models/utils.js
  src/routes/validations/utils.js
  src/routes/vendorCompanies.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/courseCreditNotesSeed.js
  tests/integration/seed/vendorCompaniesSeed.js
  tests/integration/vendorCompanies.test.js
Labels: dev

#2401 COM-3741: add verbatim on bills
  src/data/pdf/courseBilling/courseBill.js
  src/data/pdf/courseBilling/courseCreditNote.js
  src/data/pdf/courseBilling/utils.js
  tests/unit/data/courseBill.test.js
  tests/unit/data/courseCreditNote.test.js
Labels: dev

#2402 Com 3746
  src/data/pdf/courseBilling/courseBill.js
  src/helpers/vendorHistoryExport.js
  src/repositories/CourseRepository.js
  tests/integration/exports.test.js
  tests/integration/seed/exportsSeed.js
  tests/unit/data/courseBill.test.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: dev

#2403 MES 10/07/2024
  src/data/pdf/courseBilling/courseBill.js
  src/data/pdf/courseBilling/courseCreditNote.js
  src/data/pdf/courseBilling/utils.js
  src/helpers/vendorHistoryExport.js
  src/models/VendorCompany.js
  src/models/utils.js
  src/repositories/CourseRepository.js
  src/routes/validations/utils.js
  src/routes/vendorCompanies.js
  tests/integration/exports.test.js
  tests/integration/seed/courseBillsSeed.js
  tests/integration/seed/courseCreditNotesSeed.js
  tests/integration/seed/exportsSeed.js
  tests/integration/seed/vendorCompaniesSeed.js
  tests/integration/vendorCompanies.test.js
  tests/unit/data/courseBill.test.js
  tests/unit/data/courseCreditNote.test.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: master

#2406 COM-3754 - update mongodb version in ci
  .github/workflows/integration.js.yml
Labels: dev, tests

#2407 COM-3748: display holding name
  src/helpers/companies.js
  src/models/Company.js
  src/routes/companies.js
  tests/unit/helpers/companies.test.js
Labels: dev
