Repository CompaniTech/compani-api, pull requests merged in 2025-01, with the labels that each got.

#2473 Com 3854
  src/controllers/attendanceSheetController.js
  src/helpers/attendanceSheets.js
  src/helpers/courses.js
  src/routes/attendanceSheets.js
  src/routes/preHandlers/attendanceSheets.js
  tests/integration/attendanceSheets.test.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/unit/helpers/attendanceSheets.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2474 Com 3856
  src/controllers/attendanceSheetController.js
  src/data/pdf/attendanceSheet/interAttendanceSheet.js
  src/helpers/attendanceSheets.js
  src/routes/attendanceSheets.js
  src/routes/preHandlers/attendanceSheets.js
  tests/integration/attendanceSheets.test.js
  tests/integration/seed/attendanceSheetsSeed.js
  tests/unit/data/interAttendanceSheet.test.js
  tests/unit/helpers/attendanceSheets.test.js
  tests/unit/helpers/users.test.js
Labels: dev

#2480 COM-3770: rename field correct in isCorrect
  src/data/pdf/attendanceSheet/interAttendanceSheet.js
  src/helpers/attendanceSheets.js
  src/helpers/cards.js
  src/helpers/courses.js
  src/models/Card.js
  src/models/validations/cardValidation.js
  src/routes/cards.js
  src/routes/preHandlers/cards.js
  tests/integration/cards.test.js
  tests/integration/seed/activityHistoriesSeed.js
  tests/integration/seed/cardsSeed.js
  tests/integration/seed/seedsVerification.test.js
  tests/unit/data/interAttendanceSheet.test.js
  tests/unit/helpers/cards.test.js
  tests/unit/helpers/courses.test.js
Labels: dev

#2486 COM-3894 - fix undefined course in url
  src/helpers/questionnaires.js
Labels: bug

#2488 MES 22/01/2025
  src/helpers/questionnaires.js
Labels: master

#2489 Com 3895
  src/helpers/vendorHistoryExport.js
  src/repositories/CourseRepository.js
  tests/integration/exports.test.js
  tests/integration/seed/exportsSeed.js
  tests/unit/helpers/vendorHistoryExport.test.js
Labels: dev

#2491 COM-3882: make the method more robust
  src/helpers/utils.js
  tests/unit/helpers/utils.test.js
Labels: bug

#2495 MES intermediaire 27/01/2025
  src/helpers/utils.js
  tests/unit/helpers/utils.test.js
Labels: master

#2494 COM-3893 - fork node/qrcode and linked it in package.json
  package.json
  yarn.lock
Labels: dependancies

#2492 Com 3882
  src/helpers/courses.js
  tests/integration/courses.test.js
  tests/integration/seed/coursesSeed.js
  tests/unit/helpers/courses.test.js
Labels: dev
